### ISSUE TITLE
Fatal memory error with large response

### ISSUE THREAD

**Issue by mtoothman** [postmanlabs/newman#1700] opened 2018-09-03 00:09 UTC
1. Newman Version (can be found via `newman -v`):
4.1.0
 2. OS details (type, version, and architecture):
Alpine Linux 3.7.0, in docker container
 3. Are you using Newman as a library, or via the CLI? 
CLI
 3. Did you encounter this recently, or has this bug always been there:
Recently
 4. Expected behaviour:
No timeouts during long collection or test script execution when options are omitted. 
No out-of-memory errors
 5. Command / script used to run Newman:
newman run ./collections/$COLLECTION_NAME.json -e ./env/$ENV_NAME.json
 6. Sample collection, and auxiliary files (minus the sensitive details):

 7. Screenshots (if applicable):

Steps to reproduce the problem:

1. Run attached collection (JSON, saved with bogus .txt extension). Randomly selected large JSON file from the internet.
```
→ get_all_episodes
  GET https://raw.githubusercontent.com/zemirco/sf-city-lots-json/master/citylots.json [200 OK, 21.79MB, 19.4s]

<--- Last few GCs --->

[1:0x55698c4e2000]    28027 ms: Mark-sweep 655.2 (666.6) -> 439.2 (450.6) MB, 280.1 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3337 ms) allocation failure GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x4c364725ee1 <JSObject>
    1: toJSON [buffer.js:~938] [pc=0x15daddbc657d](this=0x2d8a4dcf68d1 <Uint8Array map = 0xee6886417b9>)
    3: /* anonymous */ [/usr/lib/node_modules/newman/node_modules/postman-collection/lib/collection/property-base.js:133] [bytecode=0x17720956b749 offset=100](this=0x3b2e4f48bde9 <JSGlobal Object>,accumulator=0x2d8a4dc84931 <Object map = 0x21f9f4330a39>,value=0x2d8a4dcf68d1 <Uint8Array map = 0...

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
```
[episode-editor.json.txt](https://github.com/postmanlabs/newman/files/2343855/episode-editor.json.txt)

I noticed this problem initially when a job was failing with `Script execution timed out`, but adjusting timeout settings and upgrading to 4.10.0 to use its default Infinite setting didn't help.

**Comment by kunagpal** [comment] 2018-09-03 05:28
@mtoothman As we can see from your shared CLI snippet, the 21.79MB response is not being handled all that well. As a workaround, could you try the following command and confirm that the collection runs correctly?
```console
NODE_OPTIONS="--max-old-space-size=2048" newman run ./collections/$COLLECTION_NAME.json -e ./env/$ENV_NAME.json
```
Note that you may have to adjust the value of --max-old-space-size, which is in megabytes.

A proper long-term fix is to allow ignoring responses from the underlying collection run layer.

Similar to https://github.com/postmanlabs/newman/issues/1516.

**Comment by shamasis** [comment] 2018-09-10 19:00
Node v9 and above increases these limits. Please try this out and let us know.

**Comment by DieGraueEminenz** [comment] 2019-10-18 07:56
@shamasis The mentioned problem is still reproducable, even with node v11
Do you have any other suggestions to us, to solve this unfortunate issue?

**Comment by asi-postman** [comment] 2019-12-02 19:32
Another cutomer has experienced a simimiar issue. They have tried the following and the problem still persist. I have attached a .txt of the error output as well. 

```
newman version: 4.5.6
Node version: v12.13.1
```

```
[NODE_OPTIONS="--max-old-space-size=2048"](url
[error.txt](https://github.com/postmanlabs/newman/files/3913004/error.txt)
) newman run ./collections/$COLLECTION_NAME.json -e ./env/$ENV_NAME.json
```

```
Set NODE_OPTIONS first
SET NODE_OPTIONS="--max-old-space-size=2048"
```

```
Run newman next
newman run <collection_filenam> -e <environment_filename>
```

**Comment by codenirvana** [comment] 2020-03-12 08:17
We've made significant performance improvements to handle large response payloads.
Is this issue still reproducible in the latest version of Newman?

**Comment by codenirvana** [comment] 2020-05-25 21:33
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 21:33 UTC
Labels: bug, performance, runtime

**Comment by sahanakrishnaiyer** [comment] 2020-05-30 00:15
I am seeing similar issue running collection using newman: 

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x7f64f33ba011 [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [node]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [node]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [node]
10: 0x7f64f33dfe46 [node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
12: 0x7f64f2d38b62 [node]
13: 0x7f64f2d390af [node]
14: 0x1439df7040bd
Aborted (core dumped)`

**Comment by toolmania1** [comment] 2020-06-04 20:21
<--- Last few GCs --->

n 2643 steps since start of marking, biggest step 9.7 ms, walltime since start of marking 1759 ms) finalize incremental marking via stack guard GC i[13346:0x31c3840]    38894 ms: Mark-sweep 1046.6 (1081.3) -> 551.2 (564.9) MB, 3.5 / 0.0 ms  (+ 40.3 ms in 8 steps since start of marking, biggest step 11.2 ms, walltime since start of marking 12114 ms) finalize incremental marking via stack guard GC in o[13346:0x31c3840]    38926 ms: Scavenge 551.9 (564.9) -> 551.4 (564.9) MB, 1.3 / 0.0 ms  allocation failure 





<--- JS stacktrace --->



==== JS stack trace =========================================



Security context: 0x35e132d25729 <JSObject>

    1: utf8Slice(aka utf8Slice) [evalmachine.<anonymous>:~13632] [pc=0xd135aa36432](this=0x265a68d822d1 <undefined>,e=0x1a4820c02201 <Uint8Array map = 0x3b2c7547901>,t=0,r=129301023)

    2: slowToString [evalmachine.<anonymous>:13632] [bytecode=0x89ae9f85931 offset=207](this=0x1a4820c02201 <Uint8Array map = 0x3b2c7547901>,e=0x35e132d34749 <String[4]: utf8>,t=0,r=129301023)

    3: arguments adapt...



FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

 1: node::Abort() [node]

 2: 0x11dd81c [node]

 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]

 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]

 5: v8::internal::Heap::AllocateRawFixedArray(int, v8::internal::PretenureFlag) [node]

 6: v8::internal::Heap::AllocateFixedArrayWithFiller(int, v8::internal::PretenureFlag, v8::internal::Object*) [node]

 7: v8::internal::Factory::NewUninitializedFixedArray(int) [node]

 8: 0xde8473 [node]

 9: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]

10: 0xd135a8842fd

Aborted (core dumped)

script returned exit code 134

**Comment by swedkg** [comment] 2021-03-16 17:18
This issue still exists. This is a VM with 10GB of ram with NODE_OPTIONS="--max-old-space-size=8192". The response is a file of 137.98MB. The file is downloaded, but then we get the fatal memory error. Smaller responses are fine. 

$ newman -v
5.2.2

$ node -v
v14.16.0


```
<--- Last few GCs --->

[7232:000000BAE331C240]    93192 ms: Scavenge 1163.6 (1200.8) -> 1163.6 (1200.8) MB, 105.5 / 0.0 ms  (average mu = 0.985, current mu = 0.981) allocation failure
[7232:000000BAE331C240]    94383 ms: Scavenge 1546.2 (1583.3) -> 1546.2 (1583.3) MB, 161.4 / 0.0 ms  (average mu = 0.985, current mu = 0.981) allocation failure
[7232:000000BAE331C240]    96250 ms: Scavenge 2120.0 (2157.1) -> 2120.0 (2157.1) MB, 243.3 / 0.0 ms  (average mu = 0.985, current mu = 0.981) allocation failure

<--- JS stacktrace --->

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 00007FF6E461052F napi_wrap+109311
 2: 00007FF6E45B5256 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NumberOfElementsOffset+33302
 3: 00007FF6E45B6026 node::OnFatalError+294
 4: 00007FF6E4E8163E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6E4E664BD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6E4D1094C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF6E4D3547F v8::internal::Factory::NewUninitializedFixedArray+111
 8: 00007FF6E4BFB3C0 v8::Object::GetIsolate+8128
 9: 00007FF6E4A851F7 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+169671
10: 00007FF6E4F09FED v8::internal::SetupIsolateDelegate::SetupHeap+463949
11: 000003D543A02C98
```

**Comment by matuszabojnik** [comment] 2021-05-10 08:28
Same issue here. 64 bit VM with 32GB available ram, NODE_OPTIONS="--max-old-space-size=8192".
$ newman -v
5.2.3

$ node -v
v10.24.0

Response is ~110 MB
```
<--- Last few GCs --->

[23820:0x238b920]    89082 ms: Mark-sweep 963.0 (1014.2) -> 525.7 (579.9) MB, 19.7 / 0.0 ms  (+ 17.5 ms in 4 steps since start of marking, biggest step 13.9 ms, walltime since start of marking 2307 ms) (average mu = 0.982, current mu = 0.989) finalize inc
[23820:0x238b920]    93302 ms: Mark-sweep 526.2 (579.9) -> 525.6 (578.9) MB, 12.3 / 0.0 ms  (+ 17.4 ms in 5 steps since start of marking, biggest step 9.3 ms, walltime since start of marking 3082 ms) (average mu = 0.989, current mu = 0.993) finalize incre

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x580db1d452b]
Security context: 0x395feb22ede9 <JSObject>
    1: E(aka E) [0x2d7f3cd8f9e1] [evalmachine.<anonymous>:~58] [pc=0x580db3c11df](this=0x1385aff025d9 <undefined>,e=0x3f7e3e787bd1 <Uint8Array map = 0x1be21f4639f1>,t=0,n=114353052)
    2: d [0x2d7f3cd8f761] [evalmachine.<anonymous>:58] [bytecode=0x8301cc5b659 offset=204](this=0x3f7e3e787bd1 <Uint8Array map = 0x1be21f4639f1>,e=0x395feb272a29 <String[4]: utf8>...

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0x7f1fd66402d8 node::Abort() [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7f1fd6640321  [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7f1fd68215c2 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7f1fd6821818 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7f1fd6bb0542  [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x7f1fd6b92863 v8::internal::Factory::AllocateRawFixedArray(int, v8::internal::PretenureFlag) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 7: 0x7f1fd6b92c34 v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 8: 0x7f1fd6b595fd  [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 9: 0x7f1fd6db793c v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
10: 0x580db1d452b 

```

**Comment by Seayon** [comment] 2021-06-03 16:17
same issue herea

**Comment by Seayon** [comment] 2021-06-03 16:17
same issue here
