### ISSUE TITLE
Typo in Docker Hub example

### ISSUE THREAD

**Issue by SabriH10** [postmanlabs/newman#2546] opened 2020-10-28 13:41 UTC
Opening on behalf of a User:

In https://hub.docker.com/r/postman/newman/ there's an example section.

"Examples
Run a remote collection, pass it a local environment, and save JUnit XML test report on the host

docker run -v ~/collections:/etc/postman -t postman/newman \
https://www.getpostman.com/collections/df0a40ef41d570c48154 \
--environment="HTTPBinNewmanTest.json.postman_environment" \
--reporters junit --reporter-junit-export="newman-report.xml"
"

The example command should have been
"docker run -v ~/collections:/etc/postman -t postman/newman run \
https://www.getpostman.com/collections/df0a40ef41d570c48154 \
--environment="HTTPBinNewmanTest.json.postman_environment" \
--reporters junit --reporter-junit-export="newman-report.xml""

There's a 'run' missing after 'postman/newman'.

**Comment by DannyDainton** [comment] 2020-10-29 08:18
Duplicate of #2064

**Closed** 2020-10-29 08:18 UTC
Labels: duplicate
