### ISSUE TITLE
Response times 3x-4x larger than in postman

### ISSUE THREAD

**Issue by dannycohn** [postmanlabs/newman#209] opened 2015-05-29 20:04 UTC
I've written a suite of test cases for my API, including response times. Via postman, the response time reported is typically 65-130ms. In newman, it's rather consistently 400ms. My test cases have a max response time of 200ms, so they're failing.

**Comment by chrfritsch** [comment] 2015-06-06 13:03
I have this issue to. Postman needs just 150ms for a request and newman needs about 5 secounds for every request

**Comment by cameronoxley** [comment] 2015-12-10 12:34
Also having the same issue, however in my case the response times are about 5x-10x longer in newman.

**Comment by shamasis** [comment] 2016-07-25 23:55
What would be a sure-shot way to reproduce this on OSX? Based on that, I can check whether the upcoming v3.x fixes this issue. Try it out if possible - https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by shamasis** [comment] 2016-09-16 05:29
Since v3.0, I couldn't spot much difference between Newman and postman response times. So closing this ticket. Please reopen if otherwise.

**Closed by shamasis** 2016-09-16 05:29 UTC
Labels: needs-investigation
