### ISSUE TITLE
Custom reporters are not loaded to newman run

### ISSUE THREAD

**Issue by sambenison66** [postmanlabs/newman#1550] opened 2018-05-25 22:50 UTC
I tried to install a custom report 'teamcity' and tried to use it during newman run, and eventhough the package is installed properly, it throws 'reporter could not be loaded' error.

Please find the below details:
<img width="667" alt="newman" src="https://user-images.githubusercontent.com/5916505/40569011-257efb38-6033-11e8-9cd6-01006be90ce0.png">

Same issue happens when I created my own report locally and tried to use it. But the in-built reporters such as html, cli works fine. Is there an issue here or am I doing something wrong here? Please advise.

**Comment by kunagpal** [comment] 2018-05-26 07:53
@sambenison66 I was unable to reproduce this on Node v10.2.1, and npm v6.1.0 with the following steps in a temporary folder that had just the collection file:
```shell
npm i newman newman-reporter-teamcity
newman run APITesting.postman_collection.json -r teamcity # The collection file will have to be added
```

Could you try the above out and confirm that there is an issue?

**Comment by junghanChoi** [comment] 2018-06-03 14:08
May I ask how to see the report? Do I have to install team city program?

**Comment by kunagpal** [comment] 2018-06-04 06:14
@junghanChoi https://github.com/postmanlabs/newman#creating-and-using-custom-reporters

**Comment by sambenison66** [comment] 2018-06-04 17:13
@kunagpal - The issue is fixed for team-city when I used -g to install globally, but I still see the issue for my own custom reports. Were you able to run your JSON with your own HBS file?

**Comment by kunagpal** [comment] 2018-06-09 07:11
@sambenison66 Apologies for the delay. To answer your question: yes, I was to use local reporters correctly. As a rule of thumb, reporters need to be installed on the same level as Newman, i.e., global for a global Newman installation and likewise for local installs.

**Comment by shamasis** [comment] 2018-06-13 23:19
I guess this issue has been resolved. Closing it. Please reopen otherwise or create a new issue if it’s a different issue than originally reported. 

Keeping the issue tracker clean! 🌲🎄🌿☘️

**Closed by shamasis** 2018-06-13 23:19 UTC
Labels: await user response, needs-investigation, reporters
