### ISSUE TITLE
Newman HTML report does not shows correct assertion count and URL for the original request which has used pm.sendRequest method in tests tab, instead it takes the pm.sendRequest url as the original url and shows no assertions.

### ISSUE THREAD

**Issue by swejaljain** [postmanlabs/newman#1646] opened 2018-07-31 05:55 UTC
1. Newman Version (can be found via `newman -v`): 3.10.0
 2. OS details (type, version, and architecture): Windows 8 64 bit
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Always
 4. Expected behaviour: Count should be correct in report
 5. Command / script used to run Newman: newman run API_Automation.postman_collection.json --reporters cli,html --reporter-html-export EChallan_Test.html -g postman_globals.json
--folder E-Challan -d test_data.csv -n 1
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment] 2018-07-31 06:03
Duplicate of #1303

**Closed by kunagpal** 2018-07-31 06:03 UTC
