### ISSUE TITLE
the case is no test when add pm.sendrequest () on Tests, only repro when run it with newman

### ISSUE THREAD

**Issue by wangdongna** [postmanlabs/newman#1631] opened 2018-07-19 05:14 UTC
Version and environment information:

Newman Version (can be found via newman -v): **3.9.4**
OS details (type, version, and architecture): **Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.43-2 (2017-04-30)**
Are you using Newman as a library, or via the CLI? : **CLI**
Did you encounter this recently, or has this bug always been there:  **Always**
Expected behaviour: It should be all run and without no test
I use the following command:
**newman run xxx.postman_collection.json --environment xxx.postman_environment.json --delay-request 1000 --timeout-request 3000 --reporters html --reporter-html-export xxx/${folder}/xxx${file}.html --reporter-html-template xxx/htmlreqres.hbs>>xxx/log/info${folder}.log**
Command / script used to run Newman: **Script**
Sample collection, and auxiliary files (minus the sensitive details):
Screenshots (if applicable):

**Comment by kunagpal** [comment] 2018-07-19 08:13
Hey @wangdongna, I'm not quite sure what the issue is here. Did you mean that the tests don't show up when `pm.sendRequest` is used in a test script? If so, could you share the smallest possible collection that helps us reproduce this issue? Thanks! 😄

**Comment by wangdongna** [comment] 2018-07-19 09:08
Hi,
 
Thanks for your quick reply.
 
When pm.sendRequest is used in a test script, like this:
 <
var jsonData = pm.response.json();
var sid = String(jsonData.Result.Id);
var delUrl = pm.environment.get('host') + "/api/chart/deletetreenode/"+ sid;
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});

pm.sendRequest(delUrl, function (err, response) {});
>
And run the collection which include the above test script in some cases, the result display no test.

Thanks a lot!

--Emma

**Comment by wangdongna** [comment] 2018-07-19 09:12
Sorry for close it with incorrect operation and now reopen it. I am sorry for that

**Comment by filipeamaral** [comment] 2018-08-08 14:14
@kunagpal Isn't this issue related with [1303](https://github.com/postmanlabs/newman/issues/1303)?

**Comment by codenirvana** [comment] 2020-05-25 21:20
Duplicate of https://github.com/postmanlabs/newman-reporter-html/issues/180

**Closed by codenirvana** 2020-05-25 21:20 UTC
Labels: reporters
