### ISSUE TITLE
Test for cookies is cleared by response  fails in Newman/ pass in Postman

### ISSUE THREAD

**Issue by rkatsyuryna** [postmanlabs/newman#429] opened 2016-06-21 17:07 UTC
I have test that check if logout clear cookie for "token" and redirect to some page. I expect in response to receive  Set-Cookie header with value "token=;".

And i receive this and validate by executing:

tests["Token is cleared from cookie"] = postman.getResponseHeader("Set-Cookie").has("token=;");

or 

responseHeaders["Set-Cookie"] === "token=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT";

Both works in Postman with Interceptor as i use redirects.
This *NOT WORKING * in Newman with -R attribute.

What is wrong&

**Comment by jannemann** [comment] 2016-07-14 16:25
looks like a duplicate of #242

**Comment by calebrepkes** [comment] 2016-08-23 19:18
@jannemann @shamasis Ticket #242 is closed. :)

**Comment by kunagpal** [comment] 2016-09-06 13:49
@calebrepkes @jannemann @rkatsyuryna This issue should have been fixed in Newman v3.1.0, do get back to us if that is not the case.

**Comment by calebrepkes** [comment] 2016-09-06 15:53
Hey @kunagpal regarding your remark, I updated to Newman v3.1.0 and then I added some console login to my request:
`console.log('>>> ABOUT TO READ COOKIE FROM postman.getResponseCookie("blabla")')
            var cookieLongevity = postman.getResponseCookie("LBCSS");
            console.log('>>> JUST READ THE COOKIE, and I think it failed.... because the cookie should now not be UNDEFINED and it is: '+cookieLongevity)`

Then I executed and I got the following result:
![image](https://cloud.githubusercontent.com/assets/16575936/18280789/a778559c-745a-11e6-8d0d-83df01955599.png)

Maybe Im missing something, though at first glance it looks not fixed.

**Comment by shamasis** [comment] 2016-09-06 17:47
Curious - this test is passing - https://github.com/postmanlabs/newman/blob/develop/test/integration/cookie-jar.postman_collection.json

**Comment by calebrepkes** [comment] 2016-09-08 09:24
Hey @shamasis 

Im trying out the snippet you supplied. I copied it and paste as import in Raw Text of Postman. 
Then I executed (within a XenDesktop Wind 7 environment). 

I get this error when executing via Postman: 
![image](https://cloud.githubusercontent.com/assets/16575936/18342746/94a1c3f2-75b0-11e6-9440-43f0444822cf.png)
![image](https://cloud.githubusercontent.com/assets/16575936/18342760/a0e8cb60-75b0-11e6-98b9-9511bfe4719e.png)

And when I run it via Newman command line I get:
![image](https://cloud.githubusercontent.com/assets/16575936/18342804/da443e6c-75b0-11e6-88fa-975d32efd40c.png)


I verified if it makes a difference with HTTPS or HTTP but I didnt see it in Postman.

**Comment by shamasis** [comment] 2016-09-08 22:50
From the Newman CLI output - I am seeing that your request itself is erroring out - even before anything related to cookie can be done. 

Is it a local server? If yes, check with 127.0.0.1 instead of localhost.

**Comment by calebrepkes** [comment] 2016-09-09 06:13
Hey I think you missed the point where I said that I used the same collection as you. :-) So Im trying to hit: "url": "https://echo.getpostman.com/cookies/set?foo=bar",

Where as I verified it also in Postman itself by hitting it without SSL: 
"url": "http://echo.getpostman.com/cookies/set?foo=bar",

And in both cases I dont get Cookies.

**Comment by calebrepkes** [comment] 2016-09-09 08:07
Wow this is strange, the first time I call it, its undefined. But then second time calling it, (or third, fourth) its always finding it. 

Plus, Im also unable to ping http://echo.getpostman.com when in CMD. So I figure there is a problem there somewhere.

**Comment by shamasis** [comment] 2016-09-10 09:32
I think we need to do a more realtime chat and get this sorted. Can you ping me on our slack community and then we can work on solving this together.

**Comment by kunagpal** [comment] 2016-09-29 12:01
@shamasis @calebrepkes Has this issue been resolved?

**Comment by calebrepkes** [comment] 2016-09-29 12:19
Yes, as stated in my last reply, once I used .value directly on the cookie function it works flawless. 

Thnx for your time.

**Comment by kunagpal** [comment] 2016-09-29 12:21
@calebrepkes Cool :+1:

**Closed by kunagpal** 2016-09-29 12:21 UTC
Labels: in progress, pending-close
