### ISSUE TITLE
newman 5.0.0 still throws the Invalid URI error which means it is unable to read through the environment file

### ISSUE THREAD

**Issue by adilsyed-github** [postmanlabs/newman#2343] opened 2020-05-09 04:29 UTC
1. i have my collection and env files in a specific path and I go to the path in cmd prompt, it throws error
newman run collection.json -e env.json --reporter htmlextra
2. the report shows all failed requests but when running from the postman, all are fine
3. I have attached the htmlextra report 

![image](https://user-images.githubusercontent.com/56809535/81464150-6462ae00-9202-11ea-935b-2703a16210ec.png)

![image](https://user-images.githubusercontent.com/56809535/81464200-b277b180-9202-11ea-8033-0241f7e6aa56.png)

**Comment by amandeep0511** [comment] 2020-05-09 11:24
Please assign this bug to me

**Comment by adilsyed-github** [comment] 2020-05-09 23:14
How do i assign this defect to you? do you need anything from me....

**Comment by codenirvana** [comment] 2020-05-10 03:52
@adilsyed-github are you sure `http://communication/` is a valid URL?

Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by adilsyed-github** [comment] 2020-05-11 02:35
- this is the Url: https://dev-api2.racq.com.au/external/qa/v1/communication/interactions/sms  but the first part of it is paramterised in the env. file as {{ApimUrl}}/communication/interactions/sms 
- 
[RACQAZAPI.Communication.SMSandInteractionMgmt.postman_environment.txt](https://github.com/postmanlabs/newman/files/4607277/RACQAZAPI.Communication.SMSandInteractionMgmt.postman_environment.txt)

[RACQAZAPI.Communication.SMSandInteractionMgmt.v1.txt](https://github.com/postmanlabs/newman/files/4607278/RACQAZAPI.Communication.SMSandInteractionMgmt.v1.txt)

I have uploaded above files to be txt files, you can rename it to .json for both and run by going to the file location: newman run collectionname.json -e envfilename.json --reporters cli, htmlextra

if you dont have the htmlextra you can just say html. I hope you have the enough info.

**Comment by codenirvana** [comment] 2020-05-11 05:42
@adilsyed-github This is because the environment variable `ApimUrl` is set to `""` empty string.
I hope updating the environment JSON with actual values will fix your issue.

I think this happened because the initial values in your Postman app's environment are not set.

**Closed by codenirvana** 2020-05-11 05:42 UTC
Labels: question

**Comment by adilsyed-github** [comment] 2020-05-11 23:09
@codenirvana  I updated the environment file to have the initial values as well and it ran fine. but my question why is it looking at the initial value but why not at the current value?
here is the sample result: Thanks for the suggestion.
![image](https://user-images.githubusercontent.com/56809535/81620850-2b0f8580-9430-11ea-80f0-26179fb36c3f.png)

**Comment by adilsyed-github** [comment] 2020-05-13 00:24
when I hit a request in postman that brings the response but running the same from the newman command prompt says: 404 resource not found. unsure what's happening?

**Comment by adilsyed-github** [comment] 2020-05-13 01:20
environment file has both initial and current value as the URL i am passing but still says resource not found

**Comment by adilsyed-github** [comment] 2020-05-14 01:52
I am also getting an error in newman
![image](https://user-images.githubusercontent.com/56809535/81883762-6a2d0a80-95d9-11ea-81a6-af2544aeb109.png)

**Comment by codenirvana** [comment] 2020-05-17 00:19
@adilsyed-github Only initial values are exported (+ synced) and the current values stay local to your Postman app instance.

The `ETIMEDOUT` is probably because of some proxy setup. Not sure because the endpoint is not publically available.

**Comment by adilsyed-github** [comment] 2020-05-19 03:53
Thanks for the comment but by the way when I'm running the collection from Postman runs fine but in Newman only one request is failing but NOT all and it says 404 resource not found. If that is the case why would it pass in Postman? See the error here:
![image](https://user-images.githubusercontent.com/56809535/82282787-fe331380-99d7-11ea-8e30-2f2db932d9d8.png)

![image](https://user-images.githubusercontent.com/56809535/82282815-08551200-99d8-11ea-941d-1fd7191a2e12.png)

**Comment by codenirvana** [comment] 2020-05-19 04:10
@adilsyed-github Can you share a scaled-down collection (or the API endpoint) which we can use to reproduce this issue?

**Comment by adilsyed-github** [comment] 2020-05-19 04:50
I have shared both the files in txt here... you can rename it to json before downloading in postman.
[RACQAZAPI.ApttusPymntMgmnt.Test.Env.postman_environment.txt](https://github.com/postmanlabs/newman/files/4648257/RACQAZAPI.ApttusPymntMgmnt.Test.Env.postman_environment.txt)
[RACQAZAPI.Assistance.PaymentManagement.Apttus.v1.Test.txt](https://github.com/postmanlabs/newman/files/4648258/RACQAZAPI.Assistance.PaymentManagement.Apttus.v1.Test.txt)

**Comment by codenirvana** [comment] 2020-05-19 05:08
@adilsyed-github looks like the endpoint is private, I am not able to execute the collection locally.

**Comment by adilsyed-github** [comment] 2020-05-21 23:38
@codenirvana what about the collection or the env. file? has it got any missing info becoz of which it says 404 but when ran locally in collection runner it goes fine
