### ISSUE TITLE
self-defined header can not run correctly in newman.

### ISSUE THREAD

**Issue by wxqanl** [postmanlabs/newman#1872] opened 2019-01-29 08:08 UTC
1. Newman Version (node_modules/newman/bin/newman.js -v
3.6.1 ):
 2. OS details (type, version, and architecture):--linux
 3. Are you using Newman as a library, or via the CLI?--CLI
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by codenirvana** [comment] 2019-02-04 06:39
@wxqanl Can you verify if this issue persists for you in the latest version of Newman?

**Comment by codenirvana** [comment] 2020-05-25 21:59
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 21:59 UTC
Labels: await user response
