### ISSUE TITLE
Displaying "[Error: ENOENT: no such file or directory, {UID}]" error message, when user forgets to specify postmanApiKey(when the user sends UID of collection/enviroment in the request)

### ISSUE THREAD

**Issue by csk1827** [postmanlabs/newman#2259] opened 2020-03-08 07:51 UTC
1. Newman Version (can be found via `newman -v`): 4.6.0
 2. OS details (type, version, and architecture): Windows 10
 3. Are you using Newman as a library, or via the CLI? CLI and Library
 4. Did you encounter this recently, or has this bug always been there: recently

If a user forgets to send **postmanApiKey** in the request as below(when the user sends UID for collection/environment), it is better to suggest the user to input the postmanApiKey, rather than showing the above error message i.e. "no such file or directory"

### Command
```
newman.run({
  collection: '7337586-64084678-a735-4b2e-9292-163bccfe6eca',
  environment: '7476980-b2dda329-72ea-40b8-afac-dcac8cca5f89',
  reporters: 'cli'
}
```
### Actual Result: 
```
[Error: ENOENT: no such file or directory, open 'C:\Repos\postman-demo\7337586-64084678-a735-4b2e-9292-163bccfe6eca'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Repos\\postman-demo\\7337586-64084678-a735-4b2e-9292-163bccfe6eca',
  help: 'unable to read data from file "7337586-64084678-a735-4b2e-9292-163bccfe6eca"'
}
```

 ### Expected Result
Suggest the user that postmanApiKey is missing in the command request

This bug came from the issue: #2217

**Comment by csk1827** [comment] 2020-03-08 07:51
#2217

**Comment by csk1827** [comment] 2020-03-08 07:54
@codenirvana @shamasis I want to work on this issue

**Comment by shamasis** [comment] 2020-03-08 09:47
Umm, it seems that the issue is a duplicate of the referred issue. There’s no requirement to create a duplicate issue for contribution. Please feel free to send PR referring the original issue. 😊

**Closed by shamasis** 2020-03-08 09:47 UTC
