### ISSUE TITLE
Latest postman api not working through Newman

### ISSUE THREAD

**Issue by allyn-psyonix** [postmanlabs/newman#1438] opened 2018-02-20 19:58 UTC
1. Newman Version (can be found via `newman -v`): **Newman v3.5.2 with Node v4.3.0**
 2. OS details (type, version, and architecture): **Google Kubernetes**

The tests are run from a docker image in Kubernetes. The base image is
`gcr.io/cloud-solutions-images/jenkins-k8s-slave:latest`

 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: **always**
 4. Expected behaviour: **ability to use newer test API commands (i.e. "pm" as opposed to "postman")**
 5. Command / script used to run Newman:

`newman run {collection}} --environment {{environment.json}} --globals {{globals.json}} --reporter cli,html,junit --reporter-html-export results/newman/index.html --reporter-html-template /app/Postman/failures-template-psynet.hbs --reporter-junit-export results/newman/index.xml`

 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Steps to reproduce the problem:**
1) Any postman test command starting with "pm" results in the error "ReferenceError  pm is not defined". We are able to use the older "postman" API without issue and the "pm" API is working just fine from within the standalone client (v5.5.3).

**I will also note that the json schema validation library, "tv4", gives a similar error ("ReferenceError tv4 is not defined").**

It looks like the latest Newman version is 3.9.3 so if we are simply on a version that doesn't support the latest postman API we will look into upgrading. I know that last time we looked into upgrading there were some bugs that were non-starters for us, but those may have been addressed by now (I did not do that work so I don't know what those issues were).

**Comment by kunagpal** [comment] 2018-02-20 22:01
Duplicate of https://github.com/postmanlabs/newman/issues/1439

**Closed by kunagpal** 2018-02-20 22:01 UTC

**Comment by rohitkashyapvatta** [comment] 2018-03-29 13:42
@allyn-psyonix : How did you resolve this issue. I am still getting this error even though i am using latest newman version3.9.3

**Comment by allyn-psyonix** [comment] 2018-03-29 17:39
@rohitkashyapvatta Upgrading to the latest Newman at the time did the trick for us. We didn't have to do anything else special.
