### ISSUE TITLE
EventEmitter memory leak when running more than 11 requests from a collection in Newman run

### ISSUE THREAD

**Issue by alexandramartinez** [postmanlabs/newman#2098] opened 2019-08-21 19:11 UTC
[PMCollection-and-additional-info.zip](https://github.com/postmanlabs/newman/files/3526888/PMCollection-and-additional-info.zip)

Attaching Postman Collection and text file for command used and console output.

The issue appears to happen only when the responses are coming back very quickly (less than 1-2 seconds) and so it would appear that Newman attempts to create all those listeners at a close time.

Attached a sample PM Collection doing a very quick GET call (12 times) without any tests or js code. The error always appears at the 11th call.

Command: NODE_OPTIONS='--trace-warnings' newman run newman-issue-tests.postman_collection.json --iteration-count 1

Error:
(node:41401) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:267:17)
    at Socket.addListener (events.js:283:10)
    at Socket.Readable.on (_stream_readable.js:863:35)
    at tickOnSocket (_http_client.js:670:10)
    at onSocketNT (_http_client.js:717:5)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

$ newman -v
4.5.4
$ npm -v
6.11.1
$ node -v
v12.9.0

Feel free to reach out for more questions/missing information.

**Comment by shamasis** [comment] 2019-08-21 21:47
We do extensive memory leak testing. If you take a peek at some of our major PRs you’d see memory profiling graphs. In any case, we would re-check memory profile and post here. Meanwhile, you can even help us confirm if it’s a memory leak by observing whether after running the collection the usage returns to normal after averaging out a few runs?

This warning is a “potential” leak check suggestion, detected in a very simple way. Someone has a good article about it on the net: https://www.stefanjudis.com/today-i-learned/nodejs-sends-warnings-when-you-add-too-many-listeners-to-an-event-emitter/ 

All event registrations are unregistered or dereferenced as the run progresses. We can set max listeners value to eliminate this warning, but since the listener count is unknown owing to support for external reporters, this would be pointless. We can also simply disable the warning from inside Newman code as described in documentation here - https://nodejs.org/api/events.html

**Comment by codenirvana** [comment] 2019-08-22 07:40
@alexandramartinez I am able to reproduce this issue only on `Node v12.9.0`.
With `v12.6.0` or `v10` there's no `MaxListenersExceededWarning` warning.

Can you also confirm this is specific to Node version upgrade?

**Comment by codenirvana** [comment] 2019-08-22 07:59
@alexandramartinez Followed the stack trace and `v12.9.0` changelog and looks like there's already an issue reported for this here: https://github.com/nodejs/node/issues/29239

I see there's already a revert PR up and scheduled to be fixed in `v12.9.1`, until then I hope downgrading to an older version of Node will fix this.

**Closed by codenirvana** 2019-08-22 07:59 UTC

**Comment by alexandramartinez** [comment] 2019-08-22 14:56
Thank you @codenirvana. It was fixed when downgrading to v10 and I do see that issue (#29239) was just created yesterday as well.

I confirm the issue can be closed.
