### ISSUE TITLE
Postman - Newman Error:407 Proxy Authentication Required

### ISSUE THREAD

**Issue by SMES03** [postmanlabs/newman#1599] opened 2018-06-28 13:48 UTC
Hi everyone,

Informations first:

 1. Newman Version (can be found via `newman -v`):3.9.4
 2. OS details (type, version, and architecture):Windows Server 2016 x64
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: this bug always been there (but i use it only since few days)
 4. Expected behaviour: a response from the server (with status 200)
 5. Command / script used to run Newman: something like

`C:\Users\[USER]\AppData\Roaming\npm\node_modules\newman\bin\newman.js run C:\collection\AuthentificationTFS.postman_collection.json -e C:\environment\DevCI.postman_environment.json -g 'C:\global\My Workspace.postman_globals.json'`

for each request i have the same result (Request POST and/or GET)

here is the result
![capture1](https://user-images.githubusercontent.com/40665114/42037969-fba3e072-7ae9-11e8-8109-44c1dc27b6a3.JPG)

The same request send by browser works fine
![capture2](https://user-images.githubusercontent.com/40665114/42037979-0556514a-7aea-11e8-8cb7-0872e7d20a46.JPG)

For your information, the server who receive the requests is in local network.

Thanks

**Comment by kunagpal** [comment] 2018-06-28 19:19
Hey @SMES03, it looks like you're using Newman within a Proxy network environment, and that your proxy requires authentication. Unfortunately, Newman does not support Proxy authentication at the moment. I'm more than happy to mark this as a feature request, though 😄

**Comment by codenirvana** [comment] 2019-04-30 03:59
@SMES03 As a workaround, check if setting `HTTP_PROXY`/`HTTPS_PROXY` environment variable fixes this issue?

```
HTTP_PROXY=http://USERNAME:PASSWORD@PROXYIP:PROXYPORT
```

**Comment by doughless** [comment] 2019-12-16 21:48
I tested the workaround above, and it does work with our corporate proxy. That said, it would be preferable to not have to store passwords in environment variables.

**Comment by someshkoli** [comment] 2020-03-14 14:16
I

**Comment by someshkoli** [comment] 2020-03-14 14:17
I just got started to add proxy auth feature to newman cli.

**Comment by someshkoli** [comment] 2020-03-16 16:01
Added a proxy parameter to cli optioins as shown below:
`node bin/newman.js run examples/sample-collection.json --proxy username:password
`
is this what was required ?

**Comment by codenirvana** [comment] 2020-05-25 21:17
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 21:17 UTC
Labels: feature request, runtime
