### ISSUE TITLE
newman 3.7.4 failed with "TypeError: this is not a typed array". on "reducedExecution.response.body"

### ISSUE THREAD

**Issue by malaubay** [postmanlabs/newman#1107] opened 2017-07-05 05:54 UTC
reducedExecution.response.body = Buffer.from(reducedExecution.response.stream).toString();
Newman execution failed with "TypeError: this is not a typed array".

**Comment by kunagpal** [comment] 2017-07-05 07:51
Duplicate of #1102

**Closed by kunagpal** 2017-07-05 07:51 UTC
Labels: duplicate
