### ISSUE TITLE
How to Stop NEWMAN when any assertion fails

### ISSUE THREAD

**Issue by Sripathi1983** [postmanlabs/newman#841] opened 2016-12-27 12:32 UTC
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by Sripathi1983** [comment] 2016-12-27 12:35
Please let me know any command line option is available so that the postman collection stops getting executed when any in-between collection fails

**Comment by kunagpal** [comment] 2016-12-27 13:06
@Sripathi1983 You can use the `--bail` option to stop collection runs on the first failure, like so:
```terminal
newman run coll.json --bail
```

**Comment by Sripathi1983** [comment] 2016-12-28 09:22
That works for only one collection, suppose two collections are getting executed by two newman commands one after the other and if first one fails then the second collection also should n't get executed as their is a failure in the first collection, is it possible

**Comment by Sripathi1983** [comment] 2016-12-28 09:25
eg- first collection : newman run firstcoll.json --bail 
second collection: newman run secondcoll.json --bail

the second collection shouldn't run as first collection there is assertion failure , so that overall result should be a failure

**Comment by kunagpal** [comment] 2016-12-29 06:56
This can be accomplished via the CLI, or via programmatic usage:

**CLI**
```terminal
newman run firstcoll.json --bail && newman run secondcoll.json --bail
```

**Programatically**
```javascript
var async = require('async'), // https://www.npmjs.com/package/async
    newman = require('newman');

async.series([
  function (next) {
    newman.run({
      collection: 'firstcoll.json',
      bail: true
    }, next);
  },
  function (next) {
    newman.run({
      collection: 'secondcoll.json',
      bail: true
    }, next);
  }
], process.exit);
```

**Comment by Sripathi1983** [comment] 2016-12-29 07:03
can you please give complete list flags that is used for newman cli

**Comment by kunagpal** [comment] 2016-12-30 05:33
To use Newman programmatically in your Jenkins setup, one of the steps in your test pipeline must include:
```terminal
node newman.test.js // newman.test.js contains the sample code specified above ^
```

The complete list of flags is here: https://github.com/postmanlabs/newman#command-line-options

**Comment by kunagpal** [comment] 2017-01-02 06:31
Closing issue on our end, feel free to reach out for any other suggestions or issues :smile:

**Closed by kunagpal** 2017-01-02 06:31 UTC
Labels: documentation, question

**Comment by svenkat1** [comment] 2017-04-12 05:45
Hi i am having an issue with newman integration. I am running newman parallely which will execute 5000+ test conditions, when i am using junit,html,cli reporter it running fine but in case i use json reporter means it throwing this error 

1347905 ms: Mark-sweep 1226.7 (1422.5) -> 1216.6 (1424.5) MB, 539.5 / 0.0 ms [allocation failure] [GC in old space requested].
 1348451 ms: Mark-sweep 1216.6 (1424.5) -> 1216.6 (1423.5) MB, 546.1 / 0.0 ms [allocation failure] [GC in old space requested].
 1349035 ms: Mark-sweep 1216.6 (1423.5) -> 1216.6 (1378.5) MB, 583.8 / 0.0 ms [last resort gc].
 1349607 ms: Mark-sweep 1216.6 (1378.5) -> 1216.6 (1363.5) MB, 572.2 / 0.0 ms [last resort gc].

If i execute with increased heap size it working fine by using the command --max-old-space-size=4000,
but this is not a good solution, in case if testcondition increased to some amount means then i want to increase the size while running every time it makes my system slower.

I tried garbage collector cleaning but it also failed. I tried to find the root cause in my code their is no issue,
the issue occurs only when i am using newman json reporter as it produces bulk files and its object size inceases. so kindly suggest me the solution to solve the issue.

**Comment by kunagpal** [comment] 2017-04-12 07:21
@svenkat1 Although using `--max-old-space-size` is a quick workaround, a more lasting solution is to stream reports to files, as has been discussed here:

https://github.com/postmanlabs/newman/issues/935#issuecomment-284329866
https://github.com/postmanlabs/newman/issues/564#issuecomment-242437859

**Comment by svenkat1** [comment] 2017-04-12 07:47
@kunagpal
I am declaring newman script like this
Example:-
 newman.run({
            collection: collectionFileName,
            globals : globalsEnv,
            environment : runtimeEnv,
            reporters: ['json','junit'']
        });

Here i declared json and junit in my reporters. Error occuring only when i give json in reporters, so while in runtime, newman produces json reports which is a bulk file and i execute newman parallely more than 20.

How can I add stream report in newman json reports?

**Comment by kunagpal** [comment] 2017-04-12 07:49
@svenkat1 I was referring to streamed reports as an improvement within Newman, not something that can be enabled with an option. This is an important change, and we will keep you updated on any progress that happens on this.

**Comment by svenkat1** [comment] 2017-04-12 07:53
@kunagpal Thank you for your response. once you made the changes let me update.

**Comment by mchippag** [comment] 2018-05-14 22:46
Hi, I am trying to execute a Jenkins pipeline in which one stage is dedicated for newman run(using collection). I want to know if I can abort the build if my newman assertions are failed.

**Comment by michaelajr** [comment] 2019-07-12 19:11
IMO there needs to be a `newman verify` command that can look at a summary report and exit with an error if there test run failures. We have `newman run` happening and we do not fail if there were test failures (need to do other things like dump a coverage report and stop the server) - so we need a way to programatically fail a pipeline after the test run exits. I suppose we could use the exit code of the run command. But that is hard to do in a Maven if you want to bind to the verify goal. Anyway just a thought.
