### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by hlubovac** [postmanlabs/newman#1434] opened 2018-02-16 15:43 UTC
Could you take a look at this please:
https://github.com/postmanlabs/newman-docker/issues/86

The error that I reported there originates in newman, but I saw it trying to run tests within a docker container that's running it.

The example bash script currently in readme at https://github.com/postmanlabs/newman-docker:

![image](https://user-images.githubusercontent.com/3127736/36315033-e47bdf34-12f3-11e8-8d4f-23112c5fbf28.png)

... works, but when I replace the collection URL to point to my own, then I get the error that I reported there. Here's another screenshot:

![image](https://user-images.githubusercontent.com/3127736/36315090-06c7b428-12f4-11e8-8e9b-84c860716b08.png)

Perhaps I do have something in my collection that causes this. However, the same collection gets processed just fine when I execute the exact same `docker run` command from within Windows CLI.

Yes, I'm on Windows. I executed that bash script that I'm taking about via bash that comes with git. I'm new to most of things involved in this process, so I'm not 100% sure that I'm doing everything correctly, but it's still odd that that error occurs. Thanks!

**Comment by hlubovac** [comment] 2018-02-16 17:06
I realized that the error is within presentation of the table within the console, so my workaround at the moment is `--reporter-cli-no-summary`.

**Comment by kunagpal** [comment] 2018-02-20 22:03
Closing as a duplicate of https://github.com/postmanlabs/newman/issues/885

**Closed by kunagpal** 2018-02-20 22:03 UTC
Labels: duplicate

**Comment by newmantester** [comment] 2020-08-17 20:35
I am getting the below error 

 Cannot read property 'Envelope' of undefined ,at assertion:0 in test-script  when I run my postman collections

newman run collection.josn, I tried with newman run collection.josn -k option as well still same error
