### ISSUE TITLE
Newman does not include header pre-set at collection level

### ISSUE THREAD

**Issue by emiliovmq** [postmanlabs/newman#2187] opened 2019-12-04 18:28 UTC
Newman does not set the request headers pre-set at the collection level. It works perfectly in Postman.

 1. Newman Version: 4.5.6

 2. OS details (type, version, and architecture): windows 10

 3. Are you using Newman as a library, or via the CLI? CLI

 4. Did you encounter this recently, or has this bug always been there: Recently

 5. Expected behaviour: work the same as in Postman

 6. Command / script used to run Newman: 
newman run "..\<collection_name>.json" -k -e "..\<environment_name>.json" -g "..\<globals_name>.json" -n 1 -r cli

 7. Sample collection, and auxiliary files (minus the sensitive details):

**Collection pre-request-scripts: (code snippet)**
var correlationHeaderCounterValue = pm.globals.get('correlation-header-value-counter');
if(typeof correlationHeaderCounterValue === "undefined") {
    correlationHeaderCounterValue = 0;
}
correlationHeaderCounterValue++;
pm.globals.set('correlation-header-value-counter', correlationHeaderCounterValue);

var correlationHeaderValue = "GLOBAL-API-INFORMATION-" + correlationHeaderCounterValue.toString();
pm.globals.set('correlation-header-value', correlationHeaderValue);

pm.request.headers.add({
  key: pm.globals.get('correlation-header-name'),
  value: correlationHeaderValue
});

**Collection tests**

pm.test("Is the expected header(correlationID) value in response", function () {
    var headerName = pm.globals.get('correlation-header-name');
    var headerValue = pm.globals.get('correlation-header-value');
    
    pm.response.to.have.header(headerName, headerValue);
});

 8. Screenshots (if applicable):

result in postman
![image](https://user-images.githubusercontent.com/28937991/70169877-ae66c700-1699-11ea-9486-60cad9859f8e.png)

result in newman
![image](https://user-images.githubusercontent.com/28937991/70169974-d8b88480-1699-11ea-8048-e5d1e34381aa.png)

**Comment by coditva** [comment] 2019-12-13 06:08
Hey @emiliovmq,
I was not able to reproduce this on my end.
> I created a local server which sent back whatever headers were present in request as headers in response and ran the collection you shared. The tests passed for me.

Can you try to run this request with url set to an echo server (`postman-echo.com/get`) to see if the headers are sent correctly?
If they are sent correctly, it can be a bug in the server you're testing against.

Also, can you check if the required variables are set in your `global.json` file?

Let me know how it works out! :)

**Comment by emiliovmq** [comment] 2019-12-13 13:39
Hey @coditva,

Thanks for the reply. I'm still having the same issue. I've double-checked the global.json file and everything seems to be okay there. If I run my collections through Postman all tests pass, however, as soon as I try to run the same set of collections, same env var, same global var, but instead using Newman, then, all tests pass except those tests (defined at collection level, not per request) where the request headers are set in the Pre-request scripts.

**Comment by adrijshikhar** [comment] 2020-02-24 11:07
@emiliovmq can you please provide the collection data, i would like to debug this issue of yours. Thanks

**Comment by coditva** [comment] 2020-03-09 09:06
Hey @emiliovmq, sorry for the delay. I tried the case that you described but was not able to reproduce it. Here's the `collection`, `environment` and `globals` file I used.

The header is set at pre-request script at collection level and the test for the presence of this header is also at collection level in tests script.

The command I used to run this was:
```
newman run collection.json -e environment.json -g globals.json
```

[test-newman-test.zip](https://github.com/postmanlabs/newman/files/4305614/test-newman-test.zip)

Could you provide us with more information about this issue?

**Comment by codenirvana** [comment] 2020-05-25 22:55
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 22:55 UTC
