### ISSUE TITLE
SyntaxError with nullish coalescing operator (??)

### ISSUE THREAD

**Issue by seyguai** [postmanlabs/newman#2621] opened 2021-02-17 14:24 UTC
Postman v8.0.6, Windows 10 Pro
newman v5.2.0, inside docker image postman/newman:ubuntu

Using the CLI to run the sample provided (`newman run <file>`), with this pre-request script:
`let test = null ?? "foo";`
Works perfectly fine with Postman, but fails with newman.

[nullish-coalescing-operator.postman_collection.json.txt](https://github.com/postmanlabs/newman/files/5996289/nullish-coalescing-operator.postman_collection.json.txt)

![image](https://user-images.githubusercontent.com/12875409/108217319-bcd0bf80-7133-11eb-9f20-e0bdf3079b89.png)
![image](https://user-images.githubusercontent.com/12875409/108217296-b5a9b180-7133-11eb-817c-31c78c888c59.png)

**Comment by adityaofficial10** [comment] 2021-03-11 05:43
@codenirvana @vvs11
I think this one is related to postman-runtime.

**Comment by nik-kill** [comment] 2021-03-15 20:45
@seyguai @adityaofficial10
I think the syntax error is because 'Null Coalescing operator(??)' feature was added in node v14. Please check your node version if that's  <v14. 
Alternatively,
`let test = null ?? "foo";`
can be changed to 
` let test = null || "foo";`

I've made changes in the json file below.
[nullish-coalescing-operator.postman_collection.json.txt](https://github.com/postmanlabs/newman/files/6144315/nullish-coalescing-operator.postman_collection.json.txt)

**Comment by shamasis** [comment] 2021-03-15 20:57
I'm close to 90% sure that the cause is because of older NodeJS version in the system where Newman is running. 

Here's one quick Google search around updating NodeJS version if it helps - https://www.whitesourcesoftware.com/free-developer-tools/blog/update-node-js/

Closing this. In case my 90% surety is wrong (and that does happen, please comment here to reopen.)

**Closed by shamasis** 2021-03-15 20:57 UTC
