### ISSUE TITLE
When unicode is enabled runner result summary is truncated

### ISSUE THREAD

**Issue by Sidrock28** [postmanlabs/newman#904] opened 2017-02-09 15:04 UTC
Newman v3.4.2
OS: Mac
CLI: Terminal
Script: newman run Collection.postman_collection.json -e EnvVariables.postman_environment.json -d UserVariables.csv -k --insecure --color -r cli

When there is a failed assertion the result summary is truncated. Workaround is to disable unicode.

![newman error](https://cloud.githubusercontent.com/assets/6657673/22788722/b8aba994-eeae-11e6-9195-bdb4e7e6e1d7.png)

**Comment by kunagpal** [comment] 2017-02-14 14:21
@Sidrock28 With Newman v3.4.3 on MacOSX, I'm unable to reproduce this issue. Does this happen consistently for you? If possible, share your newman run files (sans the sensitive details), and we'll take a closer look at this.

**Comment by Sidrock28** [comment] 2017-02-14 15:46
@kunagpal Run file as in my collection?

**Comment by kunagpal** [comment] 2017-02-14 17:02
@Sidrock28 Yes, the collection, environment, and data files.

**Comment by kunagpal** [comment] 2017-03-09 14:01
@Sidrock28 This might shed some more context: https://github.com/gotwarlost/istanbul/issues/620.

@czardoz @shamasis This appears to be a cli-table2 bug.

**Comment by kunagpal** [comment] 2017-05-15 07:30
@Sidrock28 A fix for this issue has been added in #1026, we'll update this thread when it has been released.

**Comment by kunagpal** [comment] 2017-06-09 17:31
This issue has been fixed in Newman v3.6.1, do check it out 😄

**Closed by kunagpal** 2017-06-09 17:31 UTC
Labels: dormant, non-newman, pending-close, reporters
