### ISSUE TITLE
Newman cannot handle GET requests with non empty rawModeData

### ISSUE THREAD

**Issue by stamtesteng** [postmanlabs/newman#821] opened 2016-12-15 13:33 UTC
**Versions used**
Windows 7
Newman 1.1.2
Postman 4.9.0
win / x86-32
Chrome 54.0.2840.99

**Issue**
This seems to be an integration issue between Postman and Newman.

Consider the case that a user in Postman duplicates (or make a Save As to) a POST (or a PUT or any other method that includes a body-raw data) request.
Then user goes to the new request created (the duplicate) and make changes. If user change the method used in the request to be a method that does not include request body (e.g. GET), then the Body tab is correctly disabled from selection. User saves the request.
After this, user exports the collection.

In the collection exported, the specific request (GET) includes the body of the request of the original (POST) request (the one before the transformation of the method from POST to GET) inside the property “rawModeData” of the json file of the collection. This has the following result. 

**Run in Postman** 
In case the collection is imported in Postman and runs through Postman or Postman runner, everything runs correctly.

**Run through Newman**
In case the same collection runs through Newman, then the specific will fail due to a “_SyntaxError in test-script_”.

**Expected Result**
The Test Suite should run correctly in both Postman and Newman.

It seems that in this case Newman does not handle correctly the GET requests that include some content inside “rawModeData" property. This issue may occur in all methods that have no request body :
-	Get
-	Copy
-	Head
-	Purge
-	Unlock

There are 2 different approaches in order to resolve this issue:
- Postman prevents the creation of such files : for this one Postman perspective is that the body is still stored there in order to remain available if user decides to change the method back from GET to POST method again (https://github.com/postmanlabs/postman-app-support/issues/2561).
- Newman handle these cases without an error.

So, can you please fix at Newman?

**Comment by czardoz** [comment] 2016-12-15 13:37
Hi @stamtesteng, we will be allowing GET requests to have bodies in Postman soon. There are a lot of use cases (especially when using Elasticsearch) where GET requests need to have bodies.

The correct fix for this is in Postman, where we will enable GET requests to have bodies, and allow them to be removed as well :-)

Thanks for reporting this!

**Comment by mykhaylo-** [comment] 2016-12-23 14:35
issue exists in newman 3.3.1 also.

**Comment by kunagpal** [comment] 2017-04-03 11:46
Closing as a duplicate of #751

**Closed by kunagpal** 2017-04-03 11:46 UTC
Labels: non-newman
