### ISSUE TITLE
_.indexBy is not a Function error occurs while running collections with environments

### ISSUE THREAD

**Issue by srpramod** [postmanlabs/newman#970] opened 2017-03-30 07:29 UTC
1. Newman Version (can be found via `newman -v`): 
 2. OS details (type, version, and architecture): Windows 7 64 bit
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour: Need to install specific version
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment] 2017-03-30 07:35
@srpramod While you can install any desired version using `npm i newman@<version>`, like `npm i newman@3.2.0`, could you also share why this is needed? 😄

**Comment by czardoz** [comment] 2017-03-30 07:36
You can use `npm install -g newman@<version>`.

E.g: `npm install -g newman@3.2.0`

**Comment by srpramod** [comment] 2017-03-30 08:49
Need of the older version is the newer version 3.5.2, unable to run the collection suite which every time i am getting the error message as _.indexBy is not a function. please look into the issue which i have mentioned:
Steps to reproduce the problem:

1. I have updated the newer version of newman 3.5.2 
2. While running suite in newman command line, every time it is showing as _.indexBy is not a function. 
3. With the older version 3.2.0, we were able to run the collections without any interrupt. 
Please help me with this issues and if need to go with the newer version 3.5.2, please provide me the newman command line options if there is any change in it.

**Comment by srpramod** [comment] 2017-03-30 09:10
Thanks you 'czardoz' & 'kunagpal'  for the information where i can go for the previous versions and install.

**Comment by srpramod** [comment] 2017-03-30 10:36
Update on the above question:
when i try to run the collection as : "newman run collection.json -e enviro.json " and enter.
in the cmd prompt it is displaying as _.indexBy is not a function. but no where i haven't use the  function in collection.

**Comment by kunagpal** [comment] 2017-03-30 10:40
@srpramod Could you also provide the following details?
* The node version (Found using `node -v` on the command prompt)
* The stack trace of the error (A series of lines below the actual error message itself).

**Comment by srpramod** [comment] 2017-03-30 12:43
Thank you kunagpal.
Install Node version is v6.5.0. Please let me know do i need to upgrade node version, if there is any dependency with the latest newman version 3.5.2.
Sorry i couldnt get on stack trace of the error, please give me some time i will recheck and provide the details.
And i have posted my comments on https client call, "Https calls return empty results #944". Please have a look.

**Comment by kunagpal** [comment] 2017-03-30 13:34
**EDIT:**
@srpramod I've update the issue title for better clarity.
@czardoz This could be root cause: https://github.com/postmanlabs/postman-collection/blob/cd7f4beb2be451bbc8df506d6abc037d8b61224c/lib/collection/variable-list.js#L264

**Comment by kunagpal** [comment] 2017-03-31 10:20
@srpramod We've identified and created a fix for this bug, and will update this thread when the Newman release has completed.

**Comment by srpramod** [comment] 2017-03-31 15:54
Thanks Kunal Nagpal for your replay. Will be waiting for the new version.

**Closed** 2017-04-03 09:28 UTC
Labels: bug, in progress

**Comment by kunagpal** [comment] 2017-05-12 15:14
@srpramod Newman v3.6.0 has been released with a fix for this issue, do go ahead and try it out. 😄
