### ISSUE TITLE
upgrading to newman 3.0.1 on OSX 10.12 betas

### ISSUE THREAD

**Issue by wkuckro** [postmanlabs/newman#551] opened 2016-08-21 21:03 UTC
OSX 10.12 Beta (16A286a), node 6.3.0, npm 3.10.5

When installing newman 3.0.1 on top of an existing newman install (2.1.2), the install process fails using either `npm install newman --global;` or `npm upgrade newman --global;`.

An alias file `newman` is left at `/Users/USER/.nvm/versions/node/v6.3.0/bin/` that must first be deleted.

Deleting that file allows you to then use `npm install newman --global;` to successfully upgrade

**Comment by shamasis** [comment] 2016-08-21 21:34
Interesting. This must have caused quite a headache to figure out! Thinking aloud - could this be an NPM bug since NPM is supposed to fully take over the creation and deletion of aliases?

**Comment by wkuckro** [comment] 2016-08-21 21:36
Not that hard to figure out, just a while to verify. The install error told me where the file was. Possibly an npm bug, but I have not had the issue with anything else, so I can't say for certain.

**Comment by shamasis** [comment] 2016-08-21 21:39
Ok one thing I can tell you is a difference between Newman v2 and v3 is that we changed the file name of the bin script. Previously it was just newman -> newman, and this time we made it newman.js -> newman. This should not cause any issue and NPM should remove old and add new binary. Let us check if we can reproduce it locally and maybe put some check in Newman v3 script to do that by itself during pre install.

**Comment by wkuckro** [comment] 2016-09-19 15:56
ran this in the latest gold master release for 10.12, same issue

**Comment by kunagpal** [comment] 2016-10-12 16:03
@wkuckro Does the issue persist for Newman v3.1.2 as well?

**Comment by shamasis** [comment] 2016-10-23 22:42
seems like this issue has been resolved with latest releases of the involved components. I recently upgraded in Sierra using latest node and NPM from Newman v2 to v3. The alias creation worked just fine. Closing.

If the issue recurs, please let us know and we will reopen. Don't forget to mention your OSX version, NPM and NodeJS version along with older and newer Newman version.

**Closed** 2016-10-23 22:42 UTC
Labels: needs-investigation
