### ISSUE TITLE
403 Error while running with Newman,

### ISSUE THREAD

**Issue by SDixit1** [postmanlabs/newman#1845] opened 2019-01-02 14:50 UTC
I am getting 403 Forbidden error while running script via Newman. Its working fine when running with Postman

**Comment by shamasis** [comment] 2019-01-02 16:21
There might be a million reason for this. 

- missing variables 
- issue with scripts
- network setup issue
- cookie issue
- collection export issue
- Newman bug

I can help narrow down if you can help me reproduce this locally and also eliminate some of the points above by checking the same at your end.

**Comment by SDixit1** [comment] 2019-01-03 11:04
Shamasis, My scripts are not new script those were working fine since long .Recently they are failed. I can look into cookie issue ,if you can suggest what to do. what is Newman bug? Is there any bug introduced in Newman?

**Comment by codenirvana** [comment] 2019-01-03 11:34
@SDixit1 Can you please provide more information regarding this issue? How can we reproduce this locally?

**Comment by codenirvana** [comment] 2020-05-25 21:49
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 21:49 UTC
Labels: question
