### ISSUE TITLE
Environment variables that are not enabled are found by pm.environment.get

### ISSUE THREAD

**Issue by josuamanuel** [postmanlabs/newman#1710] opened 2018-09-07 22:51 UTC
1. Newman Version (can be found via `newman -v`): 4.1.0
 2. OS details (type, version, and architecture): macOS Sierra 10.12.6
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: I encounter this recently. I dont know if it was present before or always.
 4. Expected behaviour: Environment variables that are not enabled are found by pm.environment.get
 5. Command / script used to run Newman: newman run disableVar-collection.json -e disableVar-environment.json
 6. Sample collection, and auxiliary files (minus the sensitive details):

disableVar-environment.json
----------------------------

{
  "id": "f0f52496-a8f7-4e2f-804c-47e8953c37c4",
  "name": "newman enabled disable env var with not effect",
  "values": [
    {
      "description": {
        "content": "",
        "type": "text/plain"
      },
      "value": "enableVar",
      "key": "enableVar",
      "enabled": true
    },
    {
      "value": "disableVar",
      "key": "disableVar",
      "enabled": true
    }
  ],
  "_postman_variable_scope": "environment",
  "_postman_exported_at": "2018-09-06T13:07:59.804Z",
  "_postman_exported_using": "Postman/6.2.5"
}

disableVar-collection.json.json
------------------------------

{
	"info": {
		"_postman_id": "ae0d0f39-6cb6-4165-8eab-fe3fc1635329",
		"name": "runner-test",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "https://postman-echo.com/get",
			"event": [
				{
					"listen": "prerequest",
					"script": {
						"id": "dcf46d9f-f96d-415d-9366-c0796dd64c2b",
						"type": "text/javascript",
						"exec": [
							"console.log(pm.environment.get('enableVar'));",
							"console.log(pm.environment.get('disableVar'));",
							"",
							""
						]
					}
				}
			],
			"request": {
				"method": "GET",
				"header": [],
				"body": {},
				"url": {
					"raw": "https://postman-echo.com/get",
					"protocol": "https",
					"host": [
						"postman-echo",
						"com"
					],
					"path": [
						"get"
					]
				}
			},
			"response": []
		}
	]
}

 7. Screenshots (if applicable):

**Comment by kunagpal** [comment] 2018-09-08 08:41
Closing as a duplicate of https://github.com/postmanlabs/newman/issues/1446

**Closed by kunagpal** 2018-09-08 08:41 UTC
Labels: duplicate
