### ISSUE TITLE
Unknown Encoding: latin1

### ISSUE THREAD

**Issue by sneela787** [postmanlabs/newman#1959] opened 2019-04-02 15:43 UTC
1. Newman Version (can be found via `newman -v`):4.4
 2. OS details (type, version, and architecture):Windows 10
 3. Are you using Newman as a library, or via the CLI? Both
 3. Did you encounter this recently, or has this bug always been there:Recently after updating to the latest version
 4. Expected behaviour: Should run the collection successfully
 5. Command / script used to run Newman:newman run "postman_collection.json"
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/48291331/55416208-5c830580-553c-11e9-925a-6007a4dfd552.png)
8. The issue happens only when collections is passed along with Data and/or environment file. The issue doesn't happen with Node v10.7

**Comment by codenirvana** [comment] 2019-04-02 17:11
@sneela787 Can you share a sample collection file (minus the sensitive details) which can be used to reproduce this issue?
Also, please share the Node version used to run Newman.

**Comment by sneela787** [comment] 2019-04-02 17:14
@codenirvana I tried to run with these "https://www.getpostman.com/collections/cb208e7e64056f5294e5" collection and I still got the issue. I am using node v10.7.0.

**Comment by codenirvana** [comment] 2019-04-02 17:32
@sneela787 That's odd, Its working fine for me (macOS).
Is it failing with collection URL as well? Like this:
```console
$ newman run https://www.getpostman.com/collections/cb208e7e64056f5294e5
```

**Comment by sneela787** [comment] 2019-04-02 17:42
I installed 4.4.1 again and tried testing it. Its working now. I will try on a different machine and will send you more details. It happened to many machines in my workplace. Thanks for the quick reply.

**Comment by shamasis** [comment] 2019-04-02 20:15
@codenirvana - I think we should put a protection around character encoding being passed to buffer.toString while fetching files in https://github.com/postmanlabs/newman/blob/develop/lib/util.js

Could it be that very old node version does not have this `latin1` name of CHARDET_BUFF_MAP enum?

**Comment by sneela787** [comment] 2019-04-03 17:41
@codenirvana @shamasis 
Its happening with Node version 6.2.2 and Newman version 4.4.1. It is successful if I don't pass Data file or environment. It throws error when I pass data file or/and environment. I don't see the below issue with node 10.7.0

![image](https://user-images.githubusercontent.com/48291331/55500313-139f7f80-5616-11e9-99ec-d1d2a9b49810.png)

**Comment by shamasis** [comment] 2019-04-03 20:36
That’s a super useful information. @codenirvana, we might need to doublecheck on character encoding support per node version and either suppress error and fall back to utf8 or do version detection. I suggest the former.

**Comment by sneela787** [comment] 2019-04-03 21:11
@shamasis Thanks for the response!! The files (Collection and Environment) that I am using are downloaded directly from Postman. Is there any different way I can download, so that it saves in UTF8 encoding? Please let me know.

**Comment by codenirvana** [comment] 2019-04-03 21:55
@sneela787 I am able to reproduce this issue on Node v6.2.2.

The issue lies in the automatic file encoding detection logic which we added in `v4.4.0`.
Its detecting `ISO-8859-1` encoding for the exported files and since Node v6.2.2 Buffer doesn't support `latin1` encoding (supported in Node v6.4.0+) the file load fails with this error. However `utf8` will work just fine in this case.

**Comment by stephenwang1011** [comment] 2019-08-23 03:17
If I changed the environment file encoding to "UTF-8 with BOM", no this error happened again, hope can help you! You can use sublime text to change your file encoding!
![image](https://user-images.githubusercontent.com/3350356/63564429-a033e580-c597-11e9-86bb-12f6cbf8cb15.png)

**Comment by fermanjj** [comment] 2020-02-11 17:48
I ran command on the collections and env file before running newman and it worked.

`sed -i '1s/^/\xef\xbb\xbf/' file-encoded-with-utf8.txt`

It converts the file to UTF-8 w/BOM.

**Comment by Shivansh2407** [comment] 2020-02-29 16:28
What needs to be done here @codenirvana ? I would like to fix this issue

**Comment by codenirvana** [comment] 2020-05-25 22:11
Newman v5 drops support for Node v6.
Closing as this is happening only in Node v6, refer: https://github.com/postmanlabs/newman/issues/1959#issuecomment-479673334

**Closed by codenirvana** 2020-05-25 22:11 UTC
Labels: bug, getting-started, pull request needed

**Comment by pedroceja123** [comment] 2021-07-03 06:41
- 

1. file:///storage/emulated/0/Download/chrome_qrcode_1625294308009.png

**Comment by pedroceja123** [comment] 2021-07-03 06:41
que se puede aser

**Comment by pedroceja123** [comment] 2021-07-03 06:41
file:///storage/emulated/0/Download/chrome_qrcode_1625294308009.png
