### ISSUE TITLE
Docs miss describing the properties of the second argument object in callbacks.

### ISSUE THREAD

**Issue by bobotzzz** [postmanlabs/newman#2372] opened 2020-05-27 18:47 UTC
For the part of your documentation in regard to callbacks https://github.com/postmanlabs/newman#newmanrunevents there is this statement that is not true: _**All events receive two arguments (1) error and (2) args. The list below describes the properties of the second argument object.**_
That list only shows the callback name and a short description of it.
Please do describe what does the **args** object contain per each callback.

**Comment by codenirvana** [comment] 2020-05-28 07:42
@bobotzzz We started documented those earlier but got deferred 😞. We'll take this up soon!
Closing as duplicate of #2069

**Closed by codenirvana** 2020-05-28 07:42 UTC
