### ISSUE TITLE
JSON output is huge (120mb) vs JUnit (24kb)

### ISSUE THREAD

**Issue by intellix** [postmanlabs/newman#1510] opened 2018-04-26 14:44 UTC
1. Newman Version (can be found via `newman -v`): **3.9.3**
 2. OS details (type, version, and architecture): **OSX Sierra**
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: **n/a**
 4. Expected behaviour: **much smaller JSON reporter output**
 5. Command / script used to run Newman: `newman run fapi.postman_collection.json -e cc-production.postman_environment.json --reporters cli,json --reporter-json-export results.json`
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

We're trying to do automated API Response time tests via newman and are re-using a postman_collection that we use for testing. The plan is to take the JSON output, parse it and output the response times somewhere.

Some API calls have fairly large responses like 1mb and it seems the JSON reporter outputs a Stream Buffer of the response which is absolutely huge.

- JSON: **120mb** `newman run fapi.postman_collection.json -e cc-production.postman_environment.json --reporters cli,json --reporter-json-export results.json`
- JUnit: **24kb** `newman run fapi.postman_collection.json -e cc-production.postman_environment.json --reporters cli,junit --reporter-junit-export results.xml`

I suppose the biggest WTF was that the JSON Reporter includes Stream buffer responses for each API call

**Comment by kunagpal** [comment] 2018-04-26 16:34
@intellix The JSON report is indeed meant to be a holistic representation of the collection run, right down to the fine details. I'll mark this as a feature request for `--reporter-json-skip-responses` to avoid adding response data to the  inbuilt JSON reporter.

**Comment by xiaotang923** [comment] 2018-07-11 18:48
@kunagpal  Hi, I'd really appreciate it if you can solve this issue in the next release! I'm really troubled by this issue right now, it's exceeding the capacity of string, so I had to use a custom reporter to just keep the automated testing going. I'd really want to switch back to the built-in reporter ASAP, so please take consideration, thanks a lot!

**Comment by jimc404** [comment] 2020-02-29 05:28
Hey @kunagpal. Can I work on this one?

**Comment by jimc404** [comment] 2020-03-12 17:14
@codenirvana There are issues like this that have an assignee but no activity for quite a while. Is it okay to work on them?

**Comment by codenirvana** [comment] 2020-03-12 19:21
@jimc404 Yeah, no issues.
In this particular case, maybe bypassing the summary object which Newman uses to accumulate the execution result will fix the issue. _Obviously, that breaks the reporters who replying upon that._

**Comment by jimc404** [comment] 2020-03-17 21:18
@codenirvana I see, to not make any changes to the summary object I made its clone with lodash and removed the response body from that before sending it to `JSON.stringify()`. I'm linking the related PR

**Comment by codenirvana** [comment] 2020-05-25 21:08
Closing as duplicate of #941

**Closed by codenirvana** 2020-05-25 21:08 UTC
Labels: feature request, reporters
