### ISSUE TITLE
"Script execution timed out." on large json responses

### ISSUE THREAD

**Issue by pbellchambers** [postmanlabs/newman#1189] opened 2017-09-06 14:22 UTC
On a get request which returns a large json response (7.21MB and 369417 lines long in this case), newman fails with a script execution timeout. This collection doesn't have any tests/assertions, it receives the response and then hangs and fails. 

The same request runs fine in postman (v5.2.0 on windows and mac), though it does hang the app for a few seconds before becoming responsive again.

1. Newman Version (can be found via `newman -v`):
3.8.1

2. OS details (type, version, and architecture):
Linux (x86_64) - CentOS 7 

3. Are you using Newman as a library, or via the CLI?
CLI

4. Did you encounter this recently, or has this bug always been there:
Not sure, have only recently tried with this size of response.

5. Expected behaviour:
Newman finishes executing a collection successfully even with a large json response.

6. Command / script used to run Newman:
`node node_modules/newman/bin/newman.js run https://api.getpostman.com/collections/<collection-uid>?apikey=<apikey> --environment environment.json`

7. Sample collection, and auxilliary files (minus the sensitive details):
I can't really share this without any sensitive details, the entire request and response would be gone.

8. Screenshots (if applicable):
![screenshot](https://user-images.githubusercontent.com/6773269/30116630-fe0218a0-9315-11e7-8000-8db9f39396e5.png)

**Steps to reproduce the problem:**
1. Have an api endpoint that returns a large json response (my example is 369417 lines long and 7.21MB in size)
2. Add a new GET request for this endpoint to a collection (doesn't need to have any tests, a simple GET request will cause the error)
3. Run the collection via newman, the response will succeed but newman will fail

**Comment by prakharjoshi** [comment] 2017-09-07 13:44
@pbellchambers It looks like the memory issue with your system. I was not able to reproduce the same issue with huge response APIs. It will be helpful if you can provide the collection and environment for which you are facing those issues (excluding sensitive issues).

**Comment by pbellchambers** [comment] 2017-09-07 17:04
I don't think it is memory related. The machine has 16GB ram available, and I've tried increasing the memory available for the node process with the `--max_old_space_size` flag, but it still fails.

When it fails the memory used of the node process isn't always at the same value (varies between 1.2GB and 1.7GB ...further suggesting it's not a memory issue as otherwise it would always fail at the same point).

What is the same every single time however is that the process always fails after 45000ms, is this a configurable limit somewhere for script execution timeout?

**Comment by shamasis** [comment] 2017-09-09 19:17
Have you tried bumping up the timeout optios?

**Comment by pbellchambers** [comment] 2017-09-11 15:57
I can't find any option for increasing the script execution timeout, do you know what it is?

**Comment by prakharjoshi** [comment] 2017-09-12 06:12
@pbellchambers  Here is the list of CLI options you can pass https://github.com/postmanlabs/newman#newman-run-collection-file-source-options

**Comment by pbellchambers** [comment] 2017-09-12 11:20
@prakharjoshi yes, there's no option for increasing the script execution timeout in that list. The only timeout related option is `--timeout-request <ms>` which increases the request timeout, which in this case is never a problem as the request returns in 1080ms (as shown above).

**Comment by prakharjoshi** [comment] 2017-09-12 11:53
@pbellchambers is there anything you have done in `Pre-request Script` or `Test Script`. I am asking you this because I am not able to reproduce this on my machine. I tried with a huge response, even increased the latency of the endpoint still Newman runs as required.

**Comment by pbellchambers** [comment] 2017-09-12 12:00
There's nothing in the pre-request script or test script.

**Comment by otteroe** [comment] 2017-09-25 08:18
I just wanted to add in that I had the same problem using 3.8.2, the one who wrote the tests in question for me used version 3.4.3 and it worked fine for him. When he upgraded to 3.8.2 the tests ran much slower and we thought the tests which timed out for me would for him as well, but they managed to get done in time.

I now tested to downgrade to 3.4.3 and it ran smoothly without any problem. 

In our case it is not a big json-file though but an octet-stream with proprietary image-type data.

**Comment by pbellchambers** [comment] 2017-09-29 14:21
Just to confirm the above, 3.4.3 also works fine for me. Completes without hanging or timing out.

**Comment by kunagpal** [comment] 2017-10-04 07:23
@pbellchambers @otteroe Newman v3.8.3 has been released with a `timeout-script` option similar to the `timeout-request` option, you can now pass in a sufficiently high millisecond value to get your scripts working.

**Comment by kunagpal** [comment] 2017-10-09 07:16
Closing as we now have a `timeout-script` option. Feel free to get back if you have any questions 😄

**Closed by kunagpal** 2017-10-09 07:16 UTC
Labels: await user response, needs-investigation

**Comment by deepakmehra10** [comment] 2018-12-03 18:58
Hi, 
I have a situation where all my test cases would run fine on local machine i.e. request to a load balancer would be made and then assertion would be done works fine. However, it would always cause timeout when the same request would be made from DCOS, Any idea?

**Comment by alicja-malewska** [comment] 2019-01-15 14:11
Hi,
I have similar issue. I had Newman version 4.1.0 and it wokred fine, but on version 4.3.1 it throws "error: Script execution timed out" after request that has 14 MB response - request passes, response is received and tests pass, but instead of sending next request, it throws mentioned error.
