### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by kunalgoel2008** [postmanlabs/newman#2170] opened 2019-11-10 08:53 UTC
I was trying to run a postman collection using newman htmlfull by running the below command
newman run postman_collection.json -e environment.json -g Global.json -r cli,htmlfull -k

Its running fine on the command screen but, I am not getting the HTML Report, getting the below error:

<--- Last few GCs --->

[10856:02BDBF58]   300149 ms: Mark-sweep 693.8 (702.9) -> 693.8 (702.9) MB, 69.8 / 0.0 ms  (average mu = 0.159, current mu = 0.001) last resort GC in old space requested
[10856:02BDBF58]   300224 ms: Mark-sweep 693.8 (702.9) -> 693.8 (702.9) MB, 74.9 / 0.0 ms  (average mu = 0.081, current mu = 0.000) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 09E5209E]
    1: StubFrame [pc: 09E447D4]
Security context: 0x05012705 <JSObject>
    2: replace [0500B635](this=0x21504101 <Very long string[4340167]>,0x24e5f9f9 <JSRegExp <String[9]: [&<>"'`=]>>,0x24e5fa31 <JSFunction escapeChar (sfi = 2CEC8EE1)>)
    3: escapeExpression [24E5CF15] [C:\Users\kunal.goel\AppData\Roaming\npm\node_modules\newman-reporter-htmlfull\node_modules\handlebars\dist\cjs\handlebars\utils.js:97]...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0120F4FE node::MakeCallback+3982
 2: 01639062 v8::internal::Heap::MaxHeapGrowingFactor+8194
 3: 017B237A v8::internal::WasmJs::Install+126186

Can You please suggest the solution for this?

**Comment by tannushree17j** [comment] 2019-12-02 06:18
Is it fixed?

**Comment by RuggeriLuca** [comment] 2020-02-06 07:16
Is it fixed?I am facing same issue

**Comment by RuggeriLuca** [comment] 2020-02-06 07:59
Is it fixed?I am facing same issue

**Comment by codenirvana** [comment] 2020-05-25 22:52
Duplicate of #941

**Closed by codenirvana** 2020-05-25 22:52 UTC

**Comment by tannushree17j** [comment] 2020-05-26 10:27
> Is it fixed?I am facing same issue

hey this si fixed.
I was getting this error mainly because the response size was too large.
