### ISSUE TITLE
Redirects are automatically avoided 

### ISSUE THREAD

**Issue by beatsbears** [postmanlabs/newman#362] opened 2016-03-21 21:36 UTC
In version 2.0.3 all redirects are currently being avoided, making the -R flag redundant.  This should be changed so that redirects are automatically followed, unless the -R flag is supplied.

**Comment by czardoz** [comment] 2016-03-22 07:35
@beatsbears Thanks a lot for the PR!

I'm not able to reproduce this issue however. I have this collection: https://www.getpostman.com/collections/0b500894597958ffce2f which has a request that does a single redirect.

Without the "-R" option, I get the 200 response (which is expected):
```
$ newman -u https://www.getpostman.com/collections/0b500894597958ffce2f

Iteration 1 of 1
The return code I got is:  200
200 4173ms r1 [GET] http://httpbin.org/redirect/1
    ✗ Returned 302

Summary:

Parent                   	Pass Count	 FailCount
-------------------------------------------------------------
Collection redirectTest  	         0	         1

Total                    	         0	         1
```

When I run it with the "-R" option, it avoids the redirects, and shows the actual 302 response code:
```
$ newman -u https://www.getpostman.com/collections/0b500894597958ffce2f -R

Iteration 1 of 1
The return code I got is:  302
302 581ms r1 [GET] http://httpbin.org/redirect/1
    ✔ Returned 302

Summary:

Parent                   	Pass Count	 FailCount
-------------------------------------------------------------
Collection redirectTest  	         1	         0

Total                    	         1	         0
```

**Comment by beatsbears** [comment] 2016-03-22 12:13
Interesting I'll look into it a bit more if I get some time.  The only major difference that I'm seeing right now is that in my call I'm doing a POST, which gets redirected to a GET request rather than a GET redirecting to another GET. Looking at the HTTP spec, it doesn't sound like this is the 'correct' way to do things, but it is how it's commonly handled. 
[More here.](http://stackoverflow.com/questions/8138137/http-post-request-receives-a-302-should-the-redirect-request-be-a-get )

Besides that, we're using different servers and I have a few extra request headers such as Origin and Referer

**Comment by shamasis** [comment] 2016-07-27 14:49
@czardoz can we come to a conclusion on this?

**Comment by kunagpal** [comment] 2016-09-06 13:54
@shamasis @czardoz Are we good to close this issue?

**Comment by shamasis** [comment] 2016-09-07 20:41
I think our goal is to closely mimic XHR behaviour so that requests are as close to the browser as possible. closing this.

**Closed by shamasis** 2016-09-07 20:41 UTC
Labels: needs-investigation, pending-close
