### ISSUE TITLE
Unexpected end of file at request

### ISSUE THREAD

**Issue by shmup** [postmanlabs/newman#692] opened 2016-10-12 17:58 UTC
I created one hyper simple collection. A single call with this in the Tests:

```
var token = postman.getResponseHeader("Authorization");
postman.setEnvironmentVariable("token", token);

tests["Successfully authenticated"] = token !== null;
```

In the GUI, it runs successfully. Running with newman, it does show a checkmark next to the "Successfully authenticated" test, but there's still an [errored] which I imagine is because of the **unexpected end of file at request**. I'm running node v5.7.1 and newman v3.1.2

I'm not sure if this is related to https://github.com/postmanlabs/newman/issues/319 or not.

```
> newman run Compas_REST_Case_Tests.postman_collection.json -e Compas8_Blank.postman_environment.json
newman

Compas_REST_Case_Tests

→ Authenticate
  POST http://localhost/Foo/api/authentication [errored]
  √  Successfully authenticated

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        1 │        1 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        1 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 986ms                     │
├───────────────────────────────────────────────┤
│ total data received: 0B (approx)              │
├───────────────────────────────────────────────┤
│ average response time: 0ms                    │
└───────────────────────────────────────────────┘

  #  failure  detail

 1.  Error    unexpected end of file
              at request
              inside "Authenticate" of "Compas_REST_Case_Tests"
```

**Comment by kunagpal** [comment] 2016-10-12 18:02
@shmup Could you share your collection and environment file, sans the sensitive details?

**Comment by shmup** [comment] 2016-10-12 18:05
Sure, here's the environment:

```
{
  "id": "9019b4fa-8b57-2f64-b9a0-0e112e0e9eb1",
  "name": "Compas8_Blank",
  "values": [
    {
      "key": "domain",
      "value": "http://localhost/Foo",
      "type": "text",
      "enabled": true
    },
    {
      "key": "user",
      "value": "foo@bar.com",
      "type": "text",
      "enabled": true
    },
    {
      "key": "password",
      "value": "foo",
      "type": "text",
      "enabled": true
    },
    {
      "key": "type",
      "value": "application/json",
      "type": "text",
      "enabled": true
    },
    {
      "key": "token",
      "type": "text",
      "value": "Bearer BLAH BLAH BLAH BLAH",
      "enabled": true
    }
  ],
  "timestamp": 1476287729182,
  "_postman_variable_scope": "environment",
  "_postman_exported_at": "2016-10-12T17:54:37.016Z",
  "_postman_exported_using": "Postman/4.7.2"
}
```

And here's the collection:

```
{
	"variables": [],
	"info": {
		"name": "Compas_REST_Case_Tests",
		"_postman_id": "c0c0d90d-cc9d-58f1-0a66-8ed9a7f62757",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "Authenticate",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": "var token = postman.getResponseHeader(\"Authorization\");\npostman.setEnvironmentVariable(\"token\", token);\n\ntests[\"Successfully authenticated\"] = token !== null;"
					}
				}
			],
			"request": {
				"url": "{{domain}}/api/authentication",
				"method": "POST",
				"header": [
					{
						"key": "Authorization",
						"value": "Basic Og==",
						"description": ""
					}
				],
				"body": {
					"mode": "urlencoded",
					"urlencoded": [
						{
							"key": "UserName",
							"value": "{{user}}",
							"type": "text",
							"enabled": true
						},
						{
							"key": "Password",
							"value": "{{password}}",
							"type": "text",
							"enabled": true
						}
					]
				},
				"description": ""
			},
			"response": []
		}
	]
}
```

**Comment by kunagpal** [comment] 2016-10-12 18:15
@shmup Are you sure you're not missing a port number in the domain environment variable? Something like: `http://localhost:3000/Foo` or `http://localhost:8080/Foo`?

**Comment by shmup** [comment] 2016-10-12 18:18
@kunagpal yeah, we're running locally on port 80, and _just to be safe_ I threw a :80 at the end (just now) to reduce another variable. Same outcome.

**Comment by kunagpal** [comment] 2016-10-12 18:25
Interesting.

**Comment by shmup** [comment] 2016-10-12 20:04
I at least verified newman will work in another scenario, which I wan't 100% sure about before:

```
> newman run STASH.postman_collection.json
newman

STASH

→ Google
  GET https://jsonplaceholder.typicode.com/posts/1 [200 OK, 961B, 775ms]

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        0 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 822ms                     │
├───────────────────────────────────────────────┤
│ total data received: 292B (approx)            │
├───────────────────────────────────────────────┤
│ average response time: 775ms                  │
└───────────────────────────────────────────────┘
```

So... I'm going to investigate way further.

**Comment by shmup** [comment] 2016-10-12 20:06
I at least verified that newman _does_ run fine on this machine, in another scenario:

```
> newman run STASH.postman_collection.json
newman

STASH

→ Google
  GET https://jsonplaceholder.typicode.com/posts/1 [200 OK, 961B, 802ms]
  √  Offender RecID is correct

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        1 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 1747ms                    │
├───────────────────────────────────────────────┤
│ total data received: 292B (approx)            │
├───────────────────────────────────────────────┤
│ average response time: 802ms                  │
└───────────────────────────────────────────────┘
```

So.. I'll investigate my problem way further. Seems like I should be able to figure it out, really.

**Comment by kunagpal** [comment] 2016-10-12 20:09
@shmup Are these machines with different line ending styles?

**Comment by shmup** [comment] 2016-10-12 20:13
@kunagpal no, I did check to be sure though, heh.

OK so here's something I just discovered. I ditched my authentication POST and just stored a token in a GET, and it all went well. So I just need to investigate my authenticatation more. I do know the POST returns nothing in the body, at all. Would that cause problems? I read all information out of its Header.

To test, I was going to throw some data in the return body.

```
> newman run STASH.postman_collection.json -e Compas8_Blank.postman_environment.json
newman

STASH

→ GetPerson
  GET http://localhost/Compas/api/Foo?bar=baz [200 OK, 725B, 50ms]
  √  User ID is correct
```

**Comment by kunagpal** [comment] 2016-10-12 20:16
In that case, a closer look at the code behind your POST endpoint would shed some more light.

**Comment by shmup** [comment] 2016-10-12 20:24
Well, I fixed it. I'm not sure if this is considered a bug or what, but (I'll share heavily heavily reduced code):

Like I said, the HttpResponse was lacking any body content, and was just sending back header data.

So, I went from:

```
public HttpResponseMessage Post(LoginModel data)
{
	var response = Request.CreateResponse(HttpStatusCode.Created);
	response.Headers.Add("Foo", "Bar " + token.Value);
	return response;
}
```

to this:

```
public HttpResponseMessage Post(LoginModel data)
{
	var response = Request.CreateResponse(HttpStatusCode.Created);
	response.Headers.Add("Foo", "Bar " + token.Value);
	response.Content = new StringContent(Json.Encode(new Dictionary<string, dynamic> {{"Name", "Jared"}}));
	return response;
}
```

And all is well!

```
> newman run STASH.postman_collection.json -e Compas8_Blank.postman_environment.json
newman

STASH

→ Authenticate
  POST http://localhost:80/Compas/api/authentication [201 Created, 809B, 59ms]
  √  Successfully authenticated

→ GetPerson
  GET http://localhost:80/Foo?bar=baz [200 OK, 725B, 25ms]
  √ ID is correct

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        2 │        0 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        2 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        2 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 1274ms                    │
├───────────────────────────────────────────────┤
│ total data received: 488B (approx)            │
├───────────────────────────────────────────────┤
│ average response time: 42ms                   │
└───────────────────────────────────────────────┘
```

**Comment by kunagpal** [comment] 2016-10-12 20:27
@shmup Thanks a lot for sharing this with us, we'll try reproducing this on our end to measure the exact extent of this condition. :)

**Comment by shmup** [comment] 2016-10-12 20:32
@kunagpal Hey no sweat. Thanks for being responsive and allowing me to battle through this in less than one day. 👍

**Comment by shamasis** [comment] 2016-10-23 23:01
@czardoz @kunagpal can we check if runtime is misbehaving with POST or other methods with server returning no body? If not, then we can close this. Else we will need to deep dive.

**Comment by kunagpal** [comment] 2016-10-24 20:21
This is not an issue with runtime, as liquid-json throws errors while trying to parse empty strings into objects (just like native `JSON.parse`). In this case, the empty string in question is the response body.

**Comment by shamasis** [comment] 2016-10-26 07:34
Are we sure about this? The original query mentioned an end of file error, which should not be coming from JSON.parse

**Comment by kunagpal** [comment] 2016-10-26 14:39
Yes, running the collection in ultra-verbose mode, with logging on every event emitted by the runtime results in a stack trace for a JSON parse error being shown.

**Comment by shmup** [comment] 2016-10-26 15:39
I whipped up a blank .NET web api project with a single Get that only set a the response headers, and not any body content.

The test passed successfully, no end of file error. Unsure what this says about the project I'm actually trying to test, and the EOF problem. I may revisit it one day (removing my fix of adding in some filler body content) and let you know what the problem was.

But for now.. I cannot reproduce it on a new project. :)

**Comment by czardoz** [comment] 2016-10-31 09:09
I think I know what's going on. An HTTP response is supposed to look like this over the network:
```
GET /get HTTP/1.1
Host: httpbin.org

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 31 Oct 2016 09:01:51 GMT
Content-Type: application/json
Content-Length: 129
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true


```
(Note that the empty body is basically two `\n`s.

Some servers however close the connection after sending the headers. In that case, a client which expects some body to be sent will error out. I think that's what is happening here.

**Comment by shamasis** [comment] 2016-10-31 20:16
@czardoz you think we should handle this case?

**Comment by czardoz** [comment] 2016-11-08 10:17
@shamasis I think we should. This lies deep inside Node.js however, in the http parser implementation, so the resolution is pretty tricky.

@shmup Can you run Newman with request debugging turned on? Something like this:

```
$ NODE_DEBUG=request newman run <your run options>
```

**Comment by czardoz** [comment] 2016-11-10 10:06
possible duplicate #722

**Comment by bsingh727** [comment] 2017-02-23 12:01
hey guys m getting same error when m try to run my collection json with environment.
 1.  SyntaxError :  Unexpected end of input at prerequest-script can you help me.
Adv Thanks

**Comment by kunagpal** [comment] 2017-02-23 12:10
@bsingh727 It appears that your pre-request script contains mismatched brackets (`[, {, (`). Could you share the pre-request script code?

**Comment by kunagpal** [comment] 2017-06-30 10:03
@shmup @bsingh727 Does this issue persist for you with Newman v3.7.4?

**Comment by kunagpal** [comment] 2017-07-03 07:36
Closing due to inactivity. Feel free to revert here if you're facing issues 😄

**Closed by kunagpal** 2017-07-03 07:36 UTC
Labels: dormant, needs-investigation
