### ISSUE TITLE
Newman sometimes can not parse params from env file

### ISSUE THREAD

**Issue by keithmork** [postmanlabs/newman#725] opened 2016-10-27 02:01 UTC
Newman 3.2.0, node 6.8.1, centos 6.5

Sometimes newman just can't get the params, for no good reason. Re-run it then it'll be fine...
![image](https://cloud.githubusercontent.com/assets/5634347/19751920/a3d7f8ea-9c2b-11e6-973f-6090646f64cb.png)

![image](https://cloud.githubusercontent.com/assets/5634347/19751904/7672701a-9c2b-11e6-90e0-8dd4b3f8ebb6.png)

**Comment by kunagpal** [comment] 2016-10-27 07:25
@keithmork I'm unable to reproduce this issue on Node `v6.8.1`, could you provide the following details, so that we may dive deeper?

1. Is Newman being used in CLI, or library mode?
2. What is the command / script used to run the collection?
3. Also, please share your collection and data files, without any sensitive details.
4. Lastly, please re-confirm that you are indeed on Newman `v3.2.0` via `newman -v` in your terminal, or via the command used to install Newman (since this looks like Jenkins).

**Comment by keithmork** [comment] 2016-10-27 08:26
Sorry for the wrong title, those envs are actually from env file.

Newman version is 3.2.0, in library mode. I wrapped newman into [this](https://github.com/keithmork/MyNewman)(in order to run every collection in a dir, run every folder in a collection and automatically assign data files and loop counts etc.)

In this case, there isn't any data file, so it's sort of the async version of typing these commands:
newman -e env -c collection --folder foo
newman -e env -c collection --folder bar
......

- collection:
https://github.com/keithmork/MyNewman/blob/master/data/collections/smoke/drug.postman_collection.json
- env:
https://github.com/keithmork/MyNewman/blob/master/data/environments/dev.postman_environment.json

**Comment by keithmork** [comment] 2016-10-27 08:46
PS: 
I changed my code a bit, now I pass a parsed json object to `options.environment`. Seems solved, at least for me.  : P

**Comment by kunagpal** [comment] 2016-10-28 15:00
@keithmork Closing issue on our end, feel free to get back to us with any other suggestions / queries / issues you may have :)

**Closed by kunagpal** 2016-10-28 15:00 UTC
Labels: needs-investigation

**Comment by shamasis** [comment] 2016-10-30 16:21
@keithmork - can you share your before and after code? We will see if this is a sort of binding issue that we need to fix?

But, just to note that if you've done something like `async.apply(newman.run …`, it is an invalid JS usage. You'd need to do `async.apply(newman.run.bind(newman), …`

**Comment by keithmork** [comment] 2016-11-01 03:22
```js
exports.runCollections = (commandLineArgs, onDone) => {
  const args = Object.assign({}, commandLineArgs);
  // ...
  collectionFiles.forEach((collectionFile) => {
    // ...
    exports.runCollection(args, onDone);
  });
};

exports.runCollection = (commandLineArgs, onDone) => {
  const args = Object.assign({}, commandLineArgs);
    // ...
    const options = exports.getNewmanOptions(args);
    // ...
    exports.runNewman(options, onDone);
  }
};

exports.getNewmanOptions = (cliArgs) => {
  const args = Object.assign({}, cliArgs);
  const collectionFile = args.collection;

  return {
    collection: replaceScriptContent(collectionFile),
    environment: fsUtils.parseJsonFile(args.environment),
    folder: args.folder,
    iterationData: args.iterationData,
    iterationCount: args.iterationCount || 1,
    reporters: ['cli', 'json', 'junit', 'html'],
    reporter: args.reporter,
    timeoutRequest: args.timeoutRequest,
    delayRequest: args.delayRequest,
    ignoreRedirects: false,
    insecure: false,
    bail: false,
    suppressExitCode: false,
  };
};

exports.runNewman = (options, onDone) => {
  newman.run(options)
    .on('done', (err, summary) => {
      // ...
};
```

**Comment by keithmork** [comment] 2016-11-30 06:58
The root cause is here: 
https://github.com/postmanlabs/newman/issues/785
