### ISSUE TITLE
Running the postman collections using Newman on remote Jenkins server

### ISSUE THREAD

**Issue by oasis070** [postmanlabs/newman#2530] opened 2020-10-03 23:50 UTC
I have been trying to get the postman script to run successfully through a Jenkins pipeline job for last two days, but in vain. 
I get the below error. Can anyone provide some guidance :-

_sh: newman: Permission denied

npm ERR! Linux 3.10.0-1127.8.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "api-tests"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10_
************************************************************
My pipeline script:-

`pipeline {
  agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000 -p 5000:5000'
            args '-u 0:0'

        }
  }

   stages{
      stage('Postman tests') {
         steps{
           git 'git@gitlab.dev.com:tree-test-automation/tests.git'
           sh 'npm install -g n'
           sh 'npm run api-tests'
         
      
   }
      }
   }
}`

**Comment by DannyDainton** [comment] 2020-10-18 06:36
Hey @oasis070

Is this a duplicate of https://github.com/postmanlabs/newman/issues/2542?

Not sure what we can do on our end about a permission issue in you're environment.

**Closed** 2020-10-20 20:20 UTC
Labels: support
