### ISSUE TITLE
[Feature Request] - Add ability to TAG a test/folder

### ISSUE THREAD

**Issue by mtaylorSF** [postmanlabs/newman#2371] opened 2020-05-27 16:04 UTC
I would like to request the ability to TAG a test/folder with a common name.

## Goal/Use Case
lets say i have 10 folders that are name Folder A thru J with 5 tests in each (50 tests in total)
in each folder i would like to TAG a certain test as "sanity".  My goal is to  run a test or folder with a TAG = "Sanity"

### Newman
we can move any "sanity" tests into a folder named "sanity" and run the tests using the `-f ` command
### Postman GUI
we can move any "sanity" tests into a folder named "sanity" and select the folder in the Collection Runner

## Purposed NEW implementation
Provide the ability to set a TAG on a test/folder level and allow newman and the collection runner to run based on that tag.  

### WHY?
the current folder approach is only suitable of one way of solving a problem.  Yes, using folders works but some people do thing differently and require a bit more flexibility.  The Tagging approach allows users to keep they're current folder structure and provides them a simple mechanism to run test suites for different test levels.

This Feature Request is to continue the conversation of https://github.com/postmanlabs/newman/issues/276

**Comment by codenirvana** [comment] 2020-05-28 07:45
@mtaylorSF Thanks for this feature request and I see how tags will be useful in situations like this.
We are already tracking this feature request in the Postman app's issue tracker.

Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/6498

**Closed by codenirvana** 2020-05-28 07:45 UTC
