### ISSUE TITLE
HTML report generated shows the same value for all iterations when using a data file with multiple data sets

### ISSUE THREAD

**Issue by rohitparethodi** [postmanlabs/newman#1529] opened 2018-05-11 02:18 UTC
1. Newman Version : 3.9.3

 2. OS details : Windows 8 64 bit

 3. Are you using Newman as a library, or via the CLI? Node module and CLI. Both have the same issue

 3. Did you encounter this recently, or has this bug always been there: I encountered recently. Could have always been there

 4. Expected behaviour: the results for different data iterations on a collection should show up in the html report generated

 5. Command / script used to run Newman: newman run collectionname -e environment -d data -k

 6. Sample collection, and auxiliary files (minus the sensitive details): any collection would do as long as we use a data file with multiple data sets

 7. Screenshots (if applicable):N/A

**Comment by kunagpal** [comment] 2018-05-18 12:25
@rohitparethodi @chrisron95 This is intended behaviour, as the HTML report is meant to aggregate statistics across multiple runs. As for the request displayed in the markup, this is picked up from the first occurrence of that request, which would be the one from the first iteration.

**Comment by rohitparethodi** [comment] 2018-05-21 01:39
@kunagpal be that as it may, the report has separate entries for those iterations and the end result is misleading. This behaviour  has made the html report almost unusable for my data driven tests

**Comment by Patrik9** [comment] 2018-06-05 14:07
Yes, the template is not usable for multiple iterations. Do you plan to add tabs for example for multiple iterations of a same test? Thaaaat would be amazing. Otherwise good job on the template but I need to find something else because I need report with multiple iterations.

**Comment by kunagpal** [comment] 2018-06-14 12:12
@rohitparethodi That was due to a bug, which was fixed in https://github.com/postmanlabs/newman/pull/1553. This will be out with the next Newman release.

@Patrik9 That is a good suggestion, we could consider adding that in a future release.

**Comment by kunagpal** [comment] 2018-07-04 16:32
@rohitparethodi This has been fixed in Newman v3.10.0 😄

**Comment by chrisron95** [comment] 2018-07-11 13:55
In my opinion it's now worse than it was before the fix. Now each iteration is just combined into the first iteration of the call. So in my case, when I'm checking the status of the order and using delays and repeating the order status call until it's complete, if one of those order status calls has an error it's all combined into one because now any call that's the same as another gets mashed into one entry in the report. This gets confusing as there are multiple orders in my tests and I use the same order status call, but it only shows in the first spot. If there's an error, this makes it very difficult to tell which area the error occurred. At least before it would show each iteration of the calls where they were in the run. There should be an `iteration` node for each call or something so that we can have each iteration shown separately with their own pass/fail status and all that good stuff.

**Comment by kunagpal** [comment] 2018-07-24 09:16
@chrisron95 We're looking at ways to improve the arrangement of information in line with your suggestions above, which will be taken up as a part of the Newman v4 line of releases.

**Closed by kunagpal** 2018-07-24 09:16 UTC
Labels: pending-close, reporters
