### ISSUE TITLE
Unable to install newman

### ISSUE THREAD

**Issue by trevorhreed** [postmanlabs/newman#287] opened 2015-11-04 22:32 UTC
For the life of me, I cannot install this package. I've tried the following on both Windows and Mac machines and they all fail:

```npm install -g newman```
```npm install -g newman --unsafe-perm```
```sudo npm install -g newman```
```sudo npm install -g newman --unsafe-perm```

**Output of `npm install -g newman --unsafe-perm` on Windows**

```
c:\Users\Trevor\node>npm install -g newman --unsafe-perm

> contextify@0.1.14 install C:\Users\Trevor\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild

/
C:\Users\Trevor\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
cwd C:\Users\Trevor\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "newman" "--unsafe-perm"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\Trevor\node\npm-debug.log
```

I am unable to attach the `npm-debug.log` file because I don't have write permission for this repository.

**Comment by stuartking** [comment] 2015-11-05 00:46
Have the same issue. It's down to an issue with Contextify when using the latest version of Node: https://github.com/brianmcd/contextify/issues/188

**Comment by elssar** [comment] 2015-11-05 04:40
@trevorhreed @stuartking the current stable version of newman does not support node v4+. We have a beta version available that works with node v4+, can you try installing that instead?

```
npm install -g newman@beta
```

**Comment by trevorhreed** [comment] 2015-11-06 16:49
Sorry, yes, I tried that as well.

```npm install -g newman@beta```

results in the following error

```
/usr/local/bin/newman -> /usr/local/lib/node_modules/newman/bin/newman

> newman@2.0.0-beta.1 postinstall /usr/local/lib/node_modules/newman
> node scripts/postinstall.js

Could not install "jsdom"
/usr/local/lib/node_modules/newman/scripts/postinstall.js:25
                throw err; // Will cause the script to exit with a non zero code
                ^

Error: EACCES: permission denied, mkdir '/Users/thr6/.npm/jsdom/6.3.0'
    at Error (native)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "newman@beta"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! newman@2.0.0-beta.1 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the newman@2.0.0-beta.1 postinstall script 'node scripts/postinstall.js'.
npm ERR! This is most likely a problem with the newman package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls newman
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thr6/node/newman-test/npm-debug.log

```

**Comment by czardoz** [comment] 2015-11-06 17:23
@trevorhreed That's a permissions issue, and I believe it's a duplicate of #288.

**Comment by trevorhreed** [comment] 2015-11-06 22:52
```sudo npm install -g newman@beta --unsafe-perm``` worked.

**Closed** 2015-11-19 19:50 UTC

**Comment by RufusA1** [comment] 2020-06-22 13:41
> `sudo npm install -g newman@beta --unsafe-perm` worked.

This actually worked. Thank you

**Comment by Venkadasubramanian** [comment] 2023-05-05 06:34
> > > `sudo npm install -g newman@beta --unsafe-perm` worked.
> > 
> > 
> > This actually worked. Thank you
> 
> asking for password

Just enter your system password, you are good to go.
