### ISSUE TITLE
How to parameterised SOAP(xml) request. 

### ISSUE THREAD

**Issue by SDixit1** [postmanlabs/newman#1754] opened 2018-10-16 10:13 UTC
Hi want to run my request multiple time with different  data. Is it possible in POSTMAN? 
For Example in below xml I want to sent request multiple time with different {{CPWN}}

<soapenv:Header/>
   <soapenv:Body>
      <ipt:confirmOrder>
         <ipt:in0>
            <mes:CPWNRef>{{CPWN}}</mes:CPWNRef>

**Comment by codenirvana** [comment] 2018-10-16 10:51
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5367

**Closed by codenirvana** 2018-10-16 10:51 UTC
