### ISSUE TITLE
Running more than 10000 assertions seems to break the run

### ISSUE THREAD

**Issue by cbarrerah** [postmanlabs/newman#1691] opened 2018-08-26 09:57 UTC
1. Newman Version (can be found via `newman -v`):
3.9.4
 2. OS details (type, version, and architecture):
Newman  run on ubuntu 16.04
 3. Are you using Newman as a library, or via the CLI?
Run as a CLI command integrated into a Jenkins Job
 3. Did you encounter this recently, or has this bug always been there:
Wouldn't say, not arrived to 10000 assertions before, i think
 4. Expected behaviour:
If the job has 7161 iterations to run in the input json, they finish being run no matter how many assertions it is generating.
 5. Command / script used to run Newman:

 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/3441026/44626934-df4c3e00-a925-11e8-810b-7b53fb13ac6a.png)
This one fails at exactly 10000 assertions

But this same collection runs flawlessly at 3496 assertions:
![image](https://user-images.githubusercontent.com/3441026/44627003-c5f7c180-a926-11e8-877e-e2626b6a96f3.png)

I can't provide the collection itself as it is using a private API that would need auth tokens i am not allowed to distribute.

Let me know if this is enough to take a look at it.

Thanks

**Comment by kunagpal** [comment] 2018-09-03 05:44
@cbarrerah This is identical to https://github.com/postmanlabs/newman/issues/1145.

**Comment by cbarrerah** [comment] 2018-09-14 09:56
I attached an example collection that still shows the same bug and has been tested with npm 6.4.1

**Comment by cbarrerah** [comment] 2018-10-30 09:11
Hi @kunagpal  any update on this issue, it is kind of limiting the utility of newman for API testing in an automated proccess, because when it breaks the run, it ignores the reporters that you have set up and simply stops running without saving any results, and as you can assume, a run with 10000 assertions is kind of important and loosing all thoose results is kind of hurting.

Thanks

**Comment by ripplegupta03** [comment] 2019-02-26 09:24
Is this issue resolved now ?  
We are thinking to move to Postman but this issue sounds deal breaker.

**Comment by codenirvana** [comment] 2020-05-25 21:30
Duplicate of #941

**Closed by codenirvana** 2020-05-25 21:30 UTC
Labels: performance, reporters, runtime
