### ISSUE TITLE
Installation of newman 4.5 fails.  4.4.1 succeeds

### ISSUE THREAD

**Issue by dschwinn** [postmanlabs/newman#2011] opened 2019-05-20 18:40 UTC
When running:

sudo npm install newman liquid-json -g

The installation fails.  Here is a excerpt from the output:

npm http 200 https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz
npm http 200 https://registry.npmjs.org/form-data/-/form-data-2.3.3.tgz
npm http 405 https://registry.npmjs.org/postman/tunnel-agent
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Linux 4.4.0-96-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "newman" "liquid-json" "-g"
npm ERR! cwd /home/circleci/app
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm http 200 https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz
npm http 200 https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz

Expected behavior is newman being installed successfully.  When I specified the previous version of newman ( sudo npm install newman@4.4.1 liquid-json -g ) the installation succeeds.

**Comment by shamasis** [comment] 2019-05-20 19:18
Can you clear NPM cache and try again? Could be an intermittent issue.

**Comment by codenirvana** [comment] 2020-05-25 22:20
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 22:20 UTC
