### ISSUE TITLE
Problem using Globals variables 

### ISSUE THREAD

**Issue by jdiaz4517** [postmanlabs/newman#932] opened 2017-02-27 11:51 UTC
Hello

I have a few environments (that for us represent different scenarios) which we are trying to run for the same collection using newman. In these environments we have some variables which could have different values. So our idea was to define different Global files, where each file will have the different combinations we want to test. We can then using newman pass these globals files to our run commands and that way we can test all the combos we need. 

Below is a snippet of our shell script showing what we are trying to do: 

     for globalFile in ${GLOBALS}; do
        for filename in test/scenarios/*.json; do
            echo "Running scenario: " ${filename}
           **newman run test/*.json -e ${filename} -g ${globalFile}**
       done
    done

Example of one of our globals file:

```
 {
  "id": "a539eeba-45f2-5468-5635-4357cfd5eb2b",
  "name": "Postman Travelport Globals",
  "values": [
    {
      **"key": "ProviderToUse"**,
      "value": "1A",
      "enabled": true,
      "type": "text"
    },
    {
      **"key": "PointOfSaleToUse",**
      "value": "AMSAA31AT",
      "enabled": true,
      "type": "text"
    }],
  "_postman_variable_scope": "globals",
  "_postman_exported_at": "2017-02-27T10:10:31.553Z",
  "_postman_exported_using": "Postman/4.10.2"
}
```
An example of a section in one of our environment file using these global variables:

```
    {
      "key": "provider",
      "value": "{{ProviderToUse}}",
      "enabled": true,
      "type": "text"
    },
    {
      "key": "pointOfSale",
      "value": "{{PointOfSaleToUse}}",
      "enabled": true,
      "type": "text"
    },
```

For some reason the values of the Global variables are not being expanded when newman is running, so we are getting: {{ProviderToUse}} and {{PointOfSaleToUse}} instead of the actual value of those variables.

I would really appreciate if someone could please point out what I'm doing wrong.

Thanks a lot
Javier

**Comment by shamasis** [comment] 2017-02-28 06:42
Javier - can we first get any possible simple errors out of our way?

- is the file format of your environment and global a working? (Test by running one sample in Newman repository and if it works, compare databstructure with your file)

- the above bash script has *.json as collection file name instead of ${filename} and I'm not sure how it's working. Can you run a single item from your file list and see if it runs and then add for loop around it?

**Comment by czardoz** [comment] 2017-02-28 08:16
I just tried doing this same thing, 

My collection is this (basically, a single POST request that uses the variables `{{provider}}` & `{{pointOfSale}}` in the request body:
```
{
	"variables": [],
	"info": {
		"name": "gh #932",
		"_postman_id": "c88b8fcd-07c2-83da-f715-7e6fcbd5dbfb",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "vars",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"console.log(responseBody);"
						]
					}
				}
			],
			"request": {
				"url": "postman-echo.com/post",
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"value": "application/json",
						"description": ""
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\"var\": \"{{provider}}\",\n\t\"var2\": \"{{pointOfSale}}\"\n}"
				},
				"description": ""
			},
			"response": []
		}
	]
}
```

The environment is:
```
{
  "id": "e7b41285-e1b1-83ac-e011-16c3b2d56fc9",
  "name": "t",
  "values": [
    {
      "enabled": true,
      "key": "provider",
      "value": "{{ProviderToUse}}",
      "type": "text"
    },
    {
      "enabled": true,
      "key": "pointOfSale",
      "value": "{{PointOfSaleToUse}}",
      "type": "text"
    }
  ],
  "timestamp": 1488268585447,
  "_postman_variable_scope": "environment",
  "_postman_exported_at": "2017-02-28T07:56:27.351Z",
  "_postman_exported_using": "Postman/4.10.2"
}
```

And my globals file contains:
```
{
  "id": "20920a91-7e3a-32d7-47b1-22f9862831ae",
  "name": "Postman Globals",
  "values": [
    {
      "key": "ProviderToUse",
      "value": "1A",
      "type": "text",
      "enabled": true
    },
    {
      "key": "PointOfSaleToUse",
      "value": "AMSAA31AT",
      "type": "text",
      "enabled": true
    }
  ],
  "_postman_variable_scope": "globals",
  "_postman_exported_at": "2017-02-28T07:53:29.443Z",
  "_postman_exported_using": "Postman/4.10.2"
}
```

This worked perfectly for me, the response contained the correct variable values:
```
{
  "json": {
    "var": "1A",
    "var2": "AMSAA31AT"
  },
}
```

@jdiaz4517 Would you mind sharing a small example collection, environment & globals file that is not working for you? That'll help us figure out the problem faster :)

**Comment by jdiaz4517** [comment] 2017-02-28 13:44
Hi

Thanks a lot for your prompt response. I changed the logic to use directly on my .js files the globals variables instead of having env variables based on these globals variables.

That approach is working perfect and it good enough for what I need now but I would for sure like to understand why it wasn't working with the previous setup as I can see you have a working code in your post so I will try to give it another go and see if I can figure it out what could be happening.

Below is the collection I'm currently using. We build all our requests based on .js files which are using values from our different environment and plus values of the results of some of the previous responses.

Regarding to some of the questions ...

shamasis:
  - this collection has been working ok for some time already. The only change I did was instead of using specific values for env variables "pointOfSale" and "provider" I changed to use a global variable instead but when I did that, the collection was using {{ProviderToUse}} and {{PointOfSaleToUse}} as the values without expanding. (I was of course trying to achieve the same result that czardoz got when he tested this)

- The line in the script:
      newman run test/*.json -e ${filename} -g ${globalFile}
  is working as we have now only one collection file so, it's resolving to something like:
       newman run test/MyCollection.json -e $Enviroment_1.json -g $globals_1.json

Please find below the current collection I'm currently using. I will attempt more tests and and I will let you know.

Thanks a lot
Javier

{
	"variables": [],
	"info": {
		"name": "Success Platform Price",
		"_postman_id": "b58fa2bd-0729-c8c3-66e9-194dc0bd5664",
		"description": "Successful do a Shop, select first fare and do a Price",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "Fetch  Functions",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"postman.setGlobalVariable(\"functions\", responseBody);",
							"try {",
							"    eval(responseBody);",
							"    tests[\"functions.js was fetched successful\"] = true;",
							"} catch (e) { ",
							"    tests[\"Error during fetch the functions.js\"] = e === null;",
							"}"
						]
					}
				}
			],
			"request": {
				"url": "http://localhost:8889/dist/functions.js",
				"method": "GET",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": ""
				},
				"description": "Call functions.js file that have all functions we need to execute the flow.\n\nThis file was created by Grunt"
			},
			"response": []
		},
		{
			"name": "I do shop",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"eval(postman.getGlobalVariable(\"functions\"));",
							"",
							"var shopAssertionFunction = eval(postman.getEnvironmentVariable(\"shopAssertionFunction\"));",
							"",
							"shopAssertionFunction.apply();"
						]
					}
				},
				{
					"listen": "prerequest",
					"script": {
						"type": "text/javascript",
						"exec": [
							"eval(postman.getGlobalVariable(\"functions\"));",
							"",
							"shop.buildRequest();"
						]
					}
				}
			],
			"request": {
				"url": "https://air-shop.{{environmentUrl}}/flights/shop",
				"method": "POST",
				"header": [
					{
						"key": "Client_Id",
						"value": "{{clientId}}",
						"description": ""
					},
					{
						"key": "Content-Type",
						"value": "application/json",
						"description": ""
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{{platformShopRequest}}"
				},
				"description": "Do the shop request against air-shop service\n\nSending the environment variables\nAsserting the result using functions.js assertion functions"
			},
			"response": []
		},
		{
			"name": "I do price",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"eval(postman.getGlobalVariable(\"functions\"));",
							"",
							"var priceAssertionFunction = eval(postman.getEnvironmentVariable(\"priceAssertionFunction\"));",
							"",
							"priceAssertionFunction.apply();"
						]
					}
				},
				{
					"listen": "prerequest",
					"script": {
						"type": "text/javascript",
						"exec": [
							"eval(postman.getGlobalVariable(\"functions\"));",
							"",
							"price.buildRequest();"
						]
					}
				}
			],
			"request": {
				"url": "https://air-price.{{environmentUrl}}/flights/price",
				"method": "POST",
				"header": [
					{
						"key": "Client_Id",
						"value": "{{clientId}}",
						"description": ""
					},
					{
						"key": "Content-Type",
						"value": "application/json",
						"description": ""
					},
					{
						"key": "Accept",
						"value": "{{serviceVersion}}",
						"description": ""
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{{platformPriceRequest}}"
				},
				"description": "Do the Price request for a selected fare from the shop response\n\nAsserting the result using functions.js assertion functions"
			},
			"response": []
		}
	]
}

**Comment by czardoz** [comment] 2017-03-06 14:17
Glad it's working for you now! I'm closing this issue, because I'm not able to reproduce it, but if you come across this again, please do re-open it. Thanks!

**Closed by czardoz** 2017-03-06 14:17 UTC
Labels: question
