### ISSUE TITLE
error: Invalid Record Length: header length

### ISSUE THREAD

**Issue by rubencm** [postmanlabs/newman#2182] opened 2019-11-26 16:54 UTC
1. Newman Version (can be found via `newman -v`): 4.5.5
 2. OS details (type, version, and architecture): Ubuntu bionic
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: just now
 4. Expected behaviour: Run collection
 5. Command / script used to run Newman: `newman run collection.json -e environment.json -d data.csv`
 6. Sample collection, and auxiliary files (minus the sensitive details): Can't share it probably, but in postman it works
 7. Screenshots (if applicable):

I reformated the csv file to have all strings enclosed with double quotes and it works now

1. Run:
```
$ newman run collection.json -e environment.json -d data.csv
```
Output:
```
error: Invalid Record Length: header length is 55, got 56 on line 21
```

**Comment by Cazaimi** [comment] 2020-03-11 11:39
Looks like an issue with the csv parser at a first glance. Check: https://github.com/adaltas/node-csv-parse/blob/078e017b0ddd7de5f23974113be85b224ff686cc/lib/es5/index.js#L823

**Comment by fangjiantan** [comment] 2020-05-21 06:46
Hi, I reported this error when executing with Newman command：
error: Invalid Record Length: header length is 9, got 1 on line 5

**Comment by codenirvana** [comment] 2020-05-25 22:52
This is fixed in Newman v5.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 22:52 UTC
Labels: getting-started
