### ISSUE TITLE
Newman SSL Cert - tunneling socket could not be established, statusCode=403

### ISSUE THREAD

**Issue by luisfestevez** [postmanlabs/newman#1747] opened 2018-10-10 15:03 UTC
1. Newman version: 4.1.0
 2. OS details: Windows 7 - 64 bits
 3. Using Newman via the CLI
 3. Recent issue.

 4. Expected behaviour: The API Request correctly reach the server and returns a 200 OK response (like in Postman).

 5. Command / script used to run Newman:
set HTTPS_PROXY=myproxy:8080 && newman run mycollection.json --insecure --ssl-client-cert mycertificate.crt --ssl-client-key mycertificate.key

 6. Actual behaviour:
The collection has only one request, which is a GET that receives an OK 200 in Postman. On Postman the proxy configuration is the machine one. The certificates are configured with a .crt and .key, besides I have to introduce the host without 443 to make it work. However, on postman I received an error 'tunneling socket could not be established, statusCode=403'

**Comment by kunagpal** [comment] 2018-10-12 12:29
@luisfestevez Could you prepend `https://` to your `HTTPS_PROXY` value?

**Comment by luisfestevez** [comment] 2018-10-15 08:54
Thank you @kunagpal for your response. I appreciate the assistance you provide.

I am actually using `http://` which is working for other API requests that don´t have certificate validation.
E.g. `set HTTPS_PROXY=http://myuser:mypassword@myproxy:8080 && newman run mycollection.json --insecure --ssl-client-cert mycertificate.crt --ssl-client-key mycertificate.key`

I might be wrong, but I think that the problem is related to the way we stablish the certificate host on Newman. On Postman I have to introduce the certificate host without the 443 port or it fails. However, on Newman I don´t know how to introduce the certificate host, so I assume it's using the 443 port and failing due this reason.

Attached you can see the Postman certificate settings and how the request works.

![postmancert](https://user-images.githubusercontent.com/44030083/46940111-376f0900-d068-11e8-8aa8-223816f0faa2.png)

![postmanapi](https://user-images.githubusercontent.com/44030083/46940127-42299e00-d068-11e8-9ef1-23cf7f6925cc.png)

**Comment by codenirvana** [comment] 2019-04-30 04:51
@luisfestevez This looks similar to https://github.com/postmanlabs/postman-app-support/issues/4707
Can you test this with the latest Newman and the Postman App (v7.0.9) and check if the issue persists?

**Comment by codenirvana** [comment] 2020-05-25 21:37
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 21:37 UTC
Labels: question
