### ISSUE TITLE
Report does not show results for all the iterations if Data file is used

### ISSUE THREAD

**Issue by arkils** [postmanlabs/newman#1867] opened 2019-01-25 09:41 UTC
I'm using Newman CLI command to run my postman request and iterating it with data sets available in my Data file.
but while generating report it only shows result of last iteration in report.xml, even though test failed in previous iterations.
the detail is available in attached file.
[NewmanIssue.docx](https://github.com/postmanlabs/newman/files/2795485/NewmanIssue.docx)
also I've attached my script files-

[Collection_data.txt](https://github.com/postmanlabs/newman/files/2795492/Collection_data.txt)
[postman_collection.txt](https://github.com/postmanlabs/newman/files/2795493/postman_collection.txt)
[postman_globals.txt](https://github.com/postmanlabs/newman/files/2795495/postman_globals.txt)

**Comment by codenirvana** [comment] 2020-05-25 21:58
It looks like this issue is fixed in the latest version of Newman.

<img width="979" alt="Screenshot 2020-05-26 at 3 28 14 AM" src="https://user-images.githubusercontent.com/4865836/82845145-f3f5a580-9f00-11ea-8758-39326a4b8c6e.png">

Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 21:58 UTC
