### ISSUE TITLE
When Scripts run in Postman all test passed but throws error in Newman

### ISSUE THREAD

**Issue by arshadsalmani** [postmanlabs/newman#3088] opened 2023-03-26 10:53 UTC
1. Newman Version:5.3.2,Postman Version:10.12.6
2. OS details (type, version, and architecture): Windows 11 Pro, 64-bit operating system, x64-based processor
3. Newman via the CLI
4. Did you encounter this recently, or has this bug always been there: Recently started using
5. Expected behaviour: Scripts run through Postman passed and Newman should also have passed
6. Command / script used to run Newman: newman run SlashData-Automation.postman_collection.json -e DEV-SlashData.postman_environment.json -g workspace.postman_globals.json -r htmlextra,cli
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/30316830/227770514-917d983b-02c5-4b9e-8263-196cc524ded6.png)

![image](https://user-images.githubusercontent.com/30316830/227770557-0a2493a0-4fff-4958-a087-9def6fe48f44.png)

**Comment by malvikach** [comment] 2023-03-27 06:50
@arshadsalmani Could you share the Newman command you are using? Want to confirm if you are using the environment file in the command.

**Comment by arshadsalmani** [comment] 2023-03-27 07:29
@malvikach Please find Newman command below
newman run SlashData-Automation.postman_collection.json -e DEV-SlashData.postman_environment.json -g workspace.postman_globals.json -r htmlextra,cli

**Comment by arshadsalmani** [comment] 2023-03-27 07:59
@malvikach I have exported the JSON Collection and environments in my computer and giving the same path in Newman.
I don't know why its showing localhost.

**Comment by malvikach** [comment] 2023-03-27 08:23
Are you using variables for base urls? If yes- Can you add some console log statements in your pre-request scripts and see what those variable values are resolving using `console.log(pm.environment.get("variable_name"))`

Console logs will appear in your CI and help you debug why an incorrect url is being requested from newman.

**Comment by malvikach** [comment] 2023-03-27 09:28
Glad that it worked! 👍 

On a similar note, I am also doing some research around Automated API Testing reporting and API Performance Testing (specifically Load Testing). If you have any feedback/thoughts to share, would love to hear them. Please drop me a note at malvika.chaudhary@postman.com or use my [calendly link](https://calendly.com/malvika-chaudhary/v10-feedback) to block some time for a short discussion.  

Closing this issue.

**Closed by malvikach** 2023-03-27 09:28 UTC

**Comment by TheCoderGuyVlad** [comment] 2023-05-11 04:57
To give explanation about this for anyone who might come across this thread:
- The reasons this happened is because the Postman "Current Value" is specific to a user's session, so it doesn't get exported by Postman when you export your environment variables.

To be able to user your Current Values outside of your Postman session, you'll need to click "Persist All" in your environment prior to exporting.

Please be careful though:
- If you're storing any sensitive information in your Environment variables (i.e. keys, usernames, password, etc.), then persisting your "Current Value" to the "Initial Value" will cause these things to be visible to anyone you share your environment with.
- For @arshadsalmani 's use case, this just so happens to be exactly the right course of action, but this may not be the cause for you. For example, if you're using shared collections across multiple users, then doing so will cause your "Current Value" to leak out to other user (and in some cases you don't want this). If you find yourself in this situation, there are a number of things you can do to avoid the leak: For example, you can create a personal copy of the share environment and then persist the values _within your personal copy_ so they'll never get shared out.
