### ISSUE TITLE
Environment and Data doesn't work together. 

### ISSUE THREAD

**Issue by siddhant-curious** [postmanlabs/newman#1973] opened 2019-04-15 06:35 UTC
Running `newman run collection.json -e env.json -d userdata.csv` doesn't take values from data file but instead use the initial value of the collection only. 

Both the environment and data file contain '_user_id_' variable which is used while forming the request. 

1. Newman Version (can be found via `newman -v`):
`4.4.1`
 2. OS details (type, version, and architecture): 
`Windows 10 Pro, 64Bit `
 3. Are you using Newman as a library, or via the CLI?: 
`CLI`
 3. Did you encounter this recently, or has this bug always been there:
 `Always`
 4. Expected behaviour: 
_Data variables value take precedence over Environment value_
 5. Command / script used to run Newman: 
`newman run collection.json -e env.json -d userdata.json`
 6. Sample collection, and auxiliary files (minus the sensitive details):

Sample Request : 

`
{
username: "{{user_id}}",
pwd: "{{pin}}"
}
`

Environment contains variables : `user_id`, `pin`, `url `etc.

Data File: 

```
user_id,pin
helloworld,1234
foobar,1234 

```

**Comment by siddhant-curious** [comment] 2019-04-15 06:35
Do note the same collection and data file work perfectly fine in Postman.

**Comment by siddhant-curious** [comment] 2019-04-15 09:51
Finally found a solution. I observed the first column of the csv is being ignored and so I just duplicated the first column, in nth column and it worked. Weird.

**Comment by shamasis** [comment] 2019-04-15 19:58
It’s weird. Can you post a sample collection and the errant data file as well as your fix?

 cc @codenirvana

**Comment by siddhant-curious** [comment] 2019-04-16 06:14
It contains confidential data. I'll try to make a similar request / data file. Can you confirm that it works as intended for you though?

**Comment by lucietriskova** [comment] 2019-05-05 10:27
hi, I was having the same issue like you, but today it started working for me... maybe the issue got resolved in the meantime?

**Comment by shamasis** [comment] 2019-05-05 13:12
Nothing was released since March 25. @lucietriskova - can you share a scaled down variant of a collection that was causing this issue?

**Comment by lucietriskova** [comment] 2019-05-05 13:39
@shamasis unfortunately it was also a collection for verification of login functionality, so confidential data :/ 
But I just tried to checkout an older version of my CSV data file from the repository and I could reproduce the problem again. So it looks like the problem is in the file itself.
I succeeded to fix the problem in following way:
1. open Notepad++
2. create a new file, copy and paste there the content of the file that was not working
3. save it as a new file - in my case, I called it "login_data2.csv" and from the filetype dropdown selected "All Types (*.*)". Please note that just replacing the old file doesn't help.
4. run the collection with the new file - it works!

**Comment by shamasis** [comment] 2019-05-05 18:10
Could this possibly be a file encoding issue @lucietriskova - perhaps it was generated on a non-windows machine or saved from a machine that has a locale setting that is not supported? I know that it got fixed for you, but I can also imagine that it must have been frustrating at the time when it wasn’t working. So, if you can remove the sensitive data from your CSV file and send me a copy. In fact, if you want,  you can send it to help@getpostman.com referencing this issue and ping back here. I will check back with the team and try out the file.

**Comment by Avinger27** [comment] 2019-09-04 05:40
This happens for me when, I copy data from an excel, save it in a csv file, specifically csv utf-8.

**Comment by codenirvana** [comment] 2020-05-25 22:13
Can you share a scaled-down collection using some [echo endpoint](http://postman-echo.com/) which we can use to reproduce this issue?

**Comment by DannyDainton** [comment] 2020-08-17 14:12
Hey @siddhant-curious, @Avinger27 

If you're able to provide some steps/scaled-down collection to reproduce the issue, we can open it up and take a look but for now,I'm going to close the issue.

**Closed by DannyDainton** 2020-08-17 14:12 UTC
Labels: await user response
