### ISSUE TITLE
Is there any easy way to get ReponseBody by using json reporter with Newman? (Newbee question)

### ISSUE THREAD

**Issue by dhananjayparab** [postmanlabs/newman#2525] opened 2020-09-26 23:10 UTC
1. Newman Version (can be found via `newman -v`): 5.2.0
 2. OS details (type, version, and architecture): MacsOs 10.15.7
 3. Are you using Newman as a library, or via the CLI? Via CLI, JSON/HML/JUNIT
 3. Did you encounter this recently, or has this bug always been there: Not sure
 4. Expected behaviour: Not Sure
 5. Command / script used to run Newman: newman run Details.postman_collection.json --reporters cli,json --reporter-json-export details.json
 6. Sample collection, and auxiliary files (minus the sensitive details):
"stream": {
            "type": "Buffer",
            "data": [
              60,
              63,
              120,
              109,
              108,

 7. Screenshots (if applicable): 
![image](https://user-images.githubusercontent.com/8953651/94351757-9d20e980-0022-11eb-8016-a10560142113.png)

Steps to reproduce the problem:

1. Save the GET Request JSON from POSTMAN which you need to run using CLI
2. Use json reporter which comes in newman by default
3. The JSON reporter does not display the Response body and shows some random numbers
4. Tried the same with POSTMAN, it works fine

Needs: Is there any workaround for this? Why does Json reporter does not display RepsoneDate in json output file, is that by Design? If yes, then is there a way to get around and get the Response Data?

**Comment by cHaLkdusT** [comment] 2020-10-06 02:09
It seems like it is by design that response is not part of the JSON output, however, as a workaround you can use newman as library. Sample usage: https://gist.github.com/vdespa/8b2d209867cc10e40939b0ce3696e3c8

**Comment by DannyDainton** [comment] 2020-10-18 06:27
By using the solution that @cHaLkdusT provided, that will log the responseBody to the console.

There are several over reporters available if you require this data in a file with the requests.

Going to close this out as it's not really the intended behaviour of the JSON reporter.

**Closed** 2020-10-18 06:33 UTC

**Comment by dhananjayparab** [comment] 2020-10-19 15:10
Thanks @DannyDainton @cHaLkdusT
