### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by kunalgoel2008** [postmanlabs/newman#2166] opened 2019-11-05 13:44 UTC
I was trying to run a postman collection using newman htmlextra by running the below command 
newman run postman_collection.json -e environment.json -g Global.json -r cli,htmlextra --insecure --reporter-htmlextra-export <some path>

its running fine on the command screen but, I am not getting the HTML Report, getting the below error:

<--- Last few GCs --->

[17420:0089A938]   312113 ms: Mark-sweep 690.1 (700.8) -> 690.1 (700.8) MB, 78.3 / 0.0 ms  (average mu = 0.179, current mu = 0.001) last resort GC in old space requested
[17420:0089A938]   312192 ms: Mark-sweep 690.1 (700.8) -> 690.1 (700.8) MB, 79.5 / 0.0 ms  (average mu = 0.094, current mu = 0.001) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 35DD209E]
    1: StubFrame [pc: 35DC47D4]
Security context: 0x2a512705 <JSObject>
    2: replace [2A50B635](this=0x18b04101 <Very long string[3174815]>,0x04da84bd <JSRegExp <String[9]: [&<>"'`=]>>,0x04da84f5 <JSFunction escapeChar (sfi = 3FCC427D)>)
    3: escapeExpression(aka escapeExpression) [04E28F91] [C:\Users\kunal.goel\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\node_modules\handlebars\dist\cjs\...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 010AF4FE node::MakeCallback+3982
 2: 014D9062 v8::internal::Heap::MaxHeapGrowingFactor+8194
 3: 01648D00 v8::internal::WasmJs::Install+87664

Can You please suggest the solution for this?

**Comment by kunalgoel2008** [comment] 2019-11-06 16:22
Is there any solution for this?

**Comment by abilous86** [comment] 2019-11-26 07:50
Hello, Facing the same issue. Any ideas where the problem is?

**Comment by tannushree17j** [comment] 2019-12-02 06:20
I am facing the same issue, please help

**Comment by shamasis** [comment] 2019-12-06 03:33
This looks like a possible issue with the reporter or coupled with the way events are accumulated at the reporter interface.

The external reporter is maintained by @DannyDainton. Since this issue has already been moved through once by @kamalaknn, not moving it again to the reporter’s issue tracker!! Instead, @DannyDainton can you please have a look at this?

**Comment by DannyDainton** [comment] 2019-12-06 12:26
Hey @kunalgoel2008 

Let's see if I can help you out 👍 

Could you please provide more environment based details, please?
- Your OS
- Node Version
- Newman Version
- htmlextra version

Is this also the _full_ Newman CLI command that you're using?

```
newman run postman_collection.json -e environment.json -g Global.json -r cli,htmlextra --insecure --reporter-htmlextra-export
```

Can you explain more about the Collection you're running? The number of folders/requests? Types of Requests?

Are you seeing the same Issue using the Postman `html` Newman reporter?

Sorry for all the questions but I'm just trying to gather all the known information I can so that I can help you further. :)

**Comment by RuggeriLuca** [comment] 2020-02-06 07:20
i don't think that this is relative to the external report. 
I have try to run my collection using the defoult report as below 

`newman run C:\temp\004_L10_Orchestrator_L10_UAT_V4.0.postman_collection.json -g C:\temp\Euro_globals.json -e C:\temp\UAT-L10-WagerOperations.postman_environment.json --folder “5104 - Tzoker (Channel 2)” -k -n 200`

after 100 iteration we take the below error :
```
<— La
st few GCs —>

[10028:000001BE90168DD0] 355619 ms: Scavenge 2042.2 (2049.5) -> 2041.1 (2049.5) MB, 4.4 / 0.0 ms (average mu = 0.234, current mu = 0.129) allocation failure
[10028:000001BE90168DD0] 355636 ms: Scavenge 2042.7 (2049.7) -> 2041.9 (2050.7) MB, 5.8 / 0.0 ms (average mu = 0.234, current mu = 0.129) allocation failure
[10028:000001BE90168DD0] 355660 ms: Scavenge 2044.7 (2052.0) -> 2043.9 (2056.1) MB, 5.7 / 0.0 ms (average mu = 0.234, current mu = 0.129) allocation failure

<— JS stacktrace —>

==== JS stack trace =========================================

0: ExitFrame [pc: 00007FF788EA154D]
1: StubFrame [pc: 00007FF788F11F49]
Security context: 0x00d1dc3c0921
2: baseClone [0000008D72BE2A39] [C:\Users\Agent\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:1] [bytecode=000001855E0FE891 offset=0](this=0x0098e94c2531 ,0x011436a82d41 <String[#7]: integer>,5,0x0110437ab189 <JSFunction (sfi = 00000150CA97CAB1)>,0x011436a83259 <String[#4]…

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200122.122008.10028.0.001.json
Node.js report completed
1: 00007FF788290BEF napi_wrap+126287
2: 00007FF78822DF26 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+34950
3: 00007FF78822EBF6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+38230
4: 00007FF788A57FEE private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+9

```

so i think that the error is not on the external report

**Comment by cchretien** [comment] 2020-02-06 21:36
I'm seeing the same issue with the latest version.

 1. Newman Version (can be found via `newman -v`): 4.5.7
 2. OS details (type, version, and architecture): Window 10.0.18362 N/A Build 18362
 3. Are you using Newman as a library, or via the CLI? Using it as a library. Script attached
 3. Did you encounter this recently, or has this bug always been there: Recently, moving to 4.5.7 from 4.4.0
 4. Expected behaviour: Expecting it to stand up like it does in 4.4.0
 5. Command / script used to run Newman:
     * `json-server.js` - http server
     * `dataset.json` - json data served by http server
     * `memleak-bug.js` - newman script
     * [newman-test.zip](https://github.com/postmanlabs/newman/files/4167828/newman-test.zip)
 6. Sample collection, and auxiliary files (minus the sensitive details):
     * `MemLeakJson.postman_collection.json`
 7. Screenshots (if applicable):
**Failure**
```
Iteration 600/1000

└ DataSet
  GET http://localhost:8090/dataset.json [200 OK, 1.52MB, 10ms]

<--- Last few GCs --->

[14828:0000029DC4B37E10]   316144 ms: Mark-sweep 1379.8 (1431.3) -> 1379.8 (1431.3) MB, 49.7 / 0.0 ms  allocation failure GC in old space requested
[14828:0000029DC4B37E10]   316195 ms: Mark-sweep 1379.8 (1431.3) -> 1379.8 (1400.3) MB, 51.5 / 0.0 ms  last resort GC in old space requested
[14828:0000029DC4B37E10]   316257 ms: Mark-sweep 1379.8 (1400.3) -> 1379.8 (1400.3) MB, 61.3 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000007606AA5879 <JSObject>
    1: utf8Slice(aka utf8Slice) [evalmachine.<anonymous>:~13329] [pc=000000F493FBDF9E](this=000000FDE9F822D1 <undefined>,e=000001D1EAFE7A99 <Uint8Array map = 0000000B77B9DE79>,t=0,r=1594707)
    2: slowToString [evalmachine.<anonymous>:13329] [bytecode=0000023BF86C0FC9 offset=207](this=000001D1EAFE7A99 <Uint8Array map = 0000000B77B9DE79>,e=0000007606AB5001 <String[4]: utf8>,t=0,r=1594707)
    ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewUninitializedFixedArray
 5: v8::internal::WasmDebugInfo::SetupForTesting
 6: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 7: 000000F493E043C1

C:\workspace>
C:\workspace>
C:\workspace>
C:\workspace>node --version
v8.11.3

C:\workspace>node_modules\.bin\newman -v
4.5.7
```


**Success**
```
Iteration 1000/1000

└ DataSet
  GET http://localhost:8090/dataset.json [200 OK, 1.52MB, 10ms]
  ┌
  │ 'Number of records: 1064'
  │ 'JSON keys: _id,index,guid,isActive,balance,picture,age,eyeColor,name,company,email,phone,address,about,registered,latitude,lon       
  │ gitude,tags,range,friends,greeting,favoriteFruit'
  │ 'Saved JSON data'
  └
  √  Obtained JSON

┌─────────────────────────┬───────────────────┬──────────────────┐
│                         │          executed │           failed │
├─────────────────────────┼───────────────────┼──────────────────┤
│              iterations │              1000 │                0 │
├─────────────────────────┼───────────────────┼──────────────────┤
│                requests │              1000 │                0 │
├─────────────────────────┼───────────────────┼──────────────────┤
│            test-scripts │              1000 │                0 │
├─────────────────────────┼───────────────────┼──────────────────┤
│      prerequest-scripts │                 0 │                0 │
├─────────────────────────┼───────────────────┼──────────────────┤
│              assertions │              1000 │                0 │
├─────────────────────────┴───────────────────┴──────────────────┤
│ total run duration: 56m 13.9s                                  │
├────────────────────────────────────────────────────────────────┤
│ total data received: 1.49GB (approx)                           │
├────────────────────────────────────────────────────────────────┤
│ average response time: 17ms [min: 8ms, max: 550ms, s.d.: 59ms] │
└────────────────────────────────────────────────────────────────┘
collection run complete!

C:\workspace\postman\newman\target>
C:\workspace\postman\newman\target>node --version
v8.11.3

C:\workspace\postman\newman\target>node_modules\.bin\newman --version
4.4.0
```
[newman-test.zip](https://github.com/postmanlabs/newman/files/4167828/newman-test.zip)

To run:
* launch the http server `node json-server.js`
* In another shell, launch script `node memleak-bug.js`

**Comment by codenirvana** [comment] 2020-05-25 22:51
Duplicate of #941

**Closed by codenirvana** 2020-05-25 22:51 UTC
Labels: reporters/community
