### ISSUE TITLE
Newman can't upload image when API request

### ISSUE THREAD

**Issue by 370672701** [postmanlabs/newman#2161] opened 2019-10-21 02:09 UTC
Newman 4.5.4
OS: windows 10, centos 6.8
As below code, I want to upload a image with api when run on CLI
_"formdata": [
								{
									"key": "img",
									"type": "file",
									"src": "icon.jpg"
								}
							]_
I have put the icon.jpg file on same folder with the collection json file.
However, it can't work, even I use the complete path, it still can't work.
(Note: it can be run on collections runner)

**Comment by codenirvana** [comment] 2020-05-25 22:47
Can you share a scaled-down collection/steps which we can use to reproduce this issue?

**Comment by DannyDainton** [comment] 2020-08-11 11:01
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by DannyDainton** 2020-08-11 11:01 UTC
