### ISSUE TITLE
Getting error - "TypeError handler._sign is not a function" in jenkins

### ISSUE THREAD

**Issue by vinaysuri1** [postmanlabs/newman#1486] opened 2018-04-04 12:46 UTC
I have created postman scripts - exported my collection - pushed to my GIT repo - ran collection using newman - created a job in jenkins with GIT URL - triggered the job

Scripts are working fine in POSTMAN.
Scripts are working fine in NEWMAN.
But I am getting following error in JENKINS - console output - 
TypeError handler._sign is not a function

Please help...
Thanks in advance

**Comment by kunagpal** [comment] 2018-04-04 12:47
Closing as a duplicate of #1484

**Closed by kunagpal** 2018-04-04 12:47 UTC
