### ISSUE TITLE
POST with nested JSON obj

### ISSUE THREAD

**Issue by krutkowski86** [postmanlabs/newman#224] opened 2015-07-03 08:44 UTC
Newman has problem while doing POST with content type JSON. It doesn't read nested objects.
`[
  {
    "user": {
      "login": "123",
      "password":"pass"
    }
  }
}`

and in body it looks like this
`{
  "login":"{{user.login}}",
  "password":"{{user.password}}"
}`

But when I make JSON data
`[
  {
    "login": "123",
    "password":"pass"
  }
]`
and body
`{
  "login":"{{login}}",
  "password":"{{password}}"
}`

It works! 

Is it possible to use nested JSON obj while doing POST?

**Comment by abhijitkane** [comment] 2015-07-03 09:14
To send raw JSON data, you need to use dataMode: raw, and set the rawModeData property. 

Check https://www.getpostman.com/collections/171ad15d3c38f76f5193

**Comment by irhabi** [comment] 2015-07-03 09:36
@abhijitkane 
I'm doing it as you said. It works in Postman, but it doesn't in Newman.
The main problem is to pass nested JSON in POST.

**Comment by abhijitkane** [comment] 2015-07-03 09:39
Are you using the -d option in Newman to use JSON data files?
If so, only files like `[ { "login": "123", "password":"pass" } ]` are supported. CSV is also supported, and there's no easy way to include nested objects in CSV files.

**Comment by irhabi** [comment] 2015-07-03 09:50
Yes, I'm using -d to include JSON file with data.
Nested objects works in test scripts but they don't in rawModeData.

In postman everything works fine, only newman got this issue.

Is there any chance to update newman with this feature?

**Comment by ChristianLegault** [comment] 2016-01-04 01:54
I would like this feature as well! Any progress or target date?

**Comment by shamasis** [comment] 2016-07-26 00:01
What would be a sure-shot way to reproduce this? Maybe a scaled down collection and other details would help.

**Comment by kunagpal** [comment] 2016-09-29 13:00
@irhabi Apologies for the delay, but could you try with latest release of Newman (v3.1.1), and let us know how that works for you?

**Comment by shamasis** [comment] 2016-10-23 22:36
@kunagpal can you reproduce this issue based on your interpretation of the original issue? Maybe also let know of what's interpreted. If you cannot reproduce, then let's close this until we have more details.

**Comment by kunagpal** [comment] 2016-10-28 23:07
@irhabi Based on our current interpretation, this is what the situation looks like:
You wish to use nested data variables, in JSON format, but the variables are not resolved. This has been confirmed for both, Newman `v3.2.0`, and Postman `v4.8.0`, as nested JSON variables are not supported (for any kind of request)... yet.

We're adding this to our internal issue tracker, and marking this as closed. However, updates will be posted here, whenever any progress occurs. Thanks a lot for your contribution! :)

**Comment by fasatrix** [comment] 2016-12-01 07:01
Will be very nice to have this feature soon.

**Comment by allienn** [comment] 2017-01-09 23:18
I would like this feature as well! Any progress or target date?

I'm having the same problem when running my collection from newman
in one test i try to post with JSON nested objects.
data.json ex:
[
    {
        "name": "john doe",
        "address": [
            {
                "address": "address example",
                "postcode": "123",
                "type": "HOME"
            },
            {
                "address": "address example",
                "postcode": "456",
                "type": "OFFICE"
            }
        ]
    }
]

When i see the server log file this request body is received like this:
{"name": "john dow", "address": [Object, Object]}

In postman my request body looks like this:
{
    "name": "{{name}}",
    "address": "{{address}}"
}

Using newman v. 3.3.0

**Comment by kunagpal** [comment] 2017-01-10 05:35
@fasatrix @allienn There's no E.T.A on this as of now, but we'll be keeping this thread updated with any progress that occurs :smile:

**Comment by abhshekkec322** [comment] 2017-07-06 06:19
Any update on this issue?  I am also facing similar problem.

**Comment by kulanup** [comment] 2017-07-20 04:55
I am also facing similar problem https://github.com/postmanlabs/newman/issues/1136

**Comment by marcelogaray** [comment] 2017-09-06 19:49
In the request body, I need to use something like your question:
"and in body it looks like this
{ "login":"{{user.login}}", "password":"{{user.password}}" }"

Any update?

Please, thx

**Comment by kindrix** [comment] 2017-09-12 07:43
I was facing the same problem with nested objects in Postman - not sure if it applies to the problems mentioned above but this is what I did.

1. Added in  the Pre-request Script
```
var temp = JSON.stringify(data);
postman.setGlobalVariable("temp", temp);
```

2. In the body:
`{{temp}}`

Hope it works for someone else too.

**Closed** 2018-06-09 07:29 UTC
Labels: feature request, tracked

**Comment by shamasis** [comment] 2018-06-13 06:13
@kunagpal can you please provide closing reasons? i.e link to the app repo issue where this resides, etc

**Comment by mimranfaruqi** [comment] 2020-03-24 09:20
I am facing this issue in 2020. Strange!!!

**Comment by johnwyles** [comment] 2021-01-21 02:56
If I do the following in the `Pre-request Script` it will work in both Postman and Newman:

```// The following is needed to interoperate between Postman and Newman
var iterationData = pm.variables.get("requestBody");
if (pm.iterationData.get("requestBody") != null) {
    iterationData = JSON.stringify(pm.iterationData.get("requestBody"));
}

pm.globals.set("iterationData", iterationData);```

I would like to avoid having to do this - does anyone have any idea how I can?
