### ISSUE TITLE
Something is broken within upgrade from 4.5.1 to 4.5.2

### ISSUE THREAD

**Issue by dobryakov** [postmanlabs/newman#2119] opened 2019-09-13 13:24 UTC
We have strange behavior with upgrading from 4.5.1 to 4.5.2

The same collection (literally the same file and same shell command to run) works on 4.5.1 and works on Postman GUI, but produces _HTTP 500 Error_ or _Request too large_ on 4.5.2 and higher. Could anyone assist with debug?

Possibly related to #2116

Affected version: 4.5.2 and higher
OS: Ubuntu Linux 18.04
Run as: CLI

**Comment by codenirvana** [comment] 2019-10-01 16:03
@dobryakov  Can you try updating the Newman to latest (v4.5.5) and check if that fixes this issue?

**Comment by codenirvana** [comment] 2020-05-25 22:37
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 22:37 UTC
