### ISSUE TITLE
Newman request response time is extremely slower than in Postman Runner.

### ISSUE THREAD

**Issue by artiya4u** [postmanlabs/newman#366] opened 2016-03-23 05:14 UTC
I've notice that request response time on Newman is extremely slower than Postman runner (2 Times). Maybe the DNS Prefetching in Chromium does play in this situation. 

![runner](https://cloud.githubusercontent.com/assets/3830524/13976256/b658fcda-f0f0-11e5-9842-df0dfda98cf9.png)

![newman](https://cloud.githubusercontent.com/assets/3830524/13976125/352fe76e-f0ef-11e5-8cc0-b3a4c28f18b9.png)

**Comment by czardoz** [comment] 2016-03-23 05:21
I'll see if I can reproduce this :-)

**Comment by czardoz** [comment] 2016-03-23 12:26
I tried this, and while I'm able to reproduce it, I'm pretty sure it's because DNS is not cached as you said.

There's not much we can do about that, Newman internally uses https://github.com/request/request which is what actually makes the request.

**Comment by artiya4u** [comment] 2016-03-25 09:51
I ran another test without using DNS (use fixed IP) the result is seem like Postman Runner using persistent connection to reduce latency in another request.

![runner2](https://cloud.githubusercontent.com/assets/3830524/14042144/b2a5c0a4-f2a9-11e5-9487-ea2cd7bd6fce.png)

![newman2](https://cloud.githubusercontent.com/assets/3830524/14042146/b8b69d1a-f2a9-11e5-90a8-ef1d77a0dee3.png)

**Comment by artiya4u** [comment] 2016-03-25 10:01
I checked the connection in Wireshare and I found that Postman Runner use persistent connection. Maybe we could improve Newman performance using same technique.

**Comment by shamasis** [comment] 2016-07-27 14:51
This is addressed in Newman v3 https://github.com/postmanlabs/newman/tree/feature/v3

If otherwise, please reopen.

**Closed by shamasis** 2016-07-27 14:51 UTC
Labels: deferred

**Comment by andreportela** [comment] 2019-11-04 14:55
I've got the same issue.
The request I'm making takes 9ms in postman and 43ms on newman. This is almost 5x slower.

Versions:
**newman** 4.5.5
**postman** 7.10.0
**mac os x** 10.14.6

**Comment by coditva** [comment] 2019-11-05 05:56
@andreportela We would need more context about this situation to fully understand the problem:
1. How many requests are you running for the collection?
2. Are the requests to the same URL?
3. Does the request take the same time for the second iteration as well (when you run multiple iterations via `newman run -n 3 -- collectionFile.json`)?

When looking for the issue, I ran a collection with 3 requests to the same url for 4 iterations in *Newman*. When running this collection, the first request takes some time (because a new connection is established), but all other requests had a response time of ~5ms.
Since *Newman* cannot keep a connection alive between different invocations, the first request takes a longer time.

Waiting for your response! :)

**Comment by andreportela** [comment] 2020-02-18 20:04
> How many requests are you running for the collection?

I was running batches of 10, 100, 1000 and 2000 requests. Same behavior on all test cases.

> Are the requests to the same URL?

Yes, all requests were made to the exactly same URL.

> Does the request take the same time for the second iteration as well (when you run multiple iterations via newman run -n 3 -- collectionFile.json)?

This was exactly the way I was running the tests.

Sorry for the long time to answer your questions. I had to give up using newman to accomplish the tests I needed.

**Comment by shamasis** [comment] 2020-02-18 20:51
@andreportela one more quick help needed from you. Can you set the header `Connection: keep-alive` in your requests and see what difference it makes in both Postman and Newman. Also try `Connection: close` and let us know.

Another best thing would be if you could make calls to one of our servers `https://postman-echo.com` and do same tests as above. 

The reason we are asking these is because the code that powers Postman is same in Newman and that we tried reproducing this and failed. Hence we are trying to eliminate anything in the request definition itself as a possible cause.

**Comment by flsimoes96** [comment] 2020-06-22 09:50
I'm having a problem where, in some specific requests there is a very significant difference in request time between postman and newman. Newman's request time is sometimes 16x slower than postman. This problem might be tied to the request I'm making, but nevertheless it is strange to have such a difference between making that request in newman and postman. I've tried to replicate the error using a publicly acessable REST request, but haven't been sucessfull doing it. Anyone else with this kind of behaviour?

Below are the result of the same request made in postman (1st picture) and newman (2nd picture):
![image](https://user-images.githubusercontent.com/67265099/85272499-277e0e00-b474-11ea-88ac-75b44334b9fe.png)
![image](https://user-images.githubusercontent.com/67265099/85273314-52b52d00-b475-11ea-91f7-0a137820990b.png)

**Comment by akava** [comment] 2026-05-27 10:35
For me this was "--delay-request 1500" parameter. Now newman is faster than postman
