### ISSUE TITLE
Send and download response body

### ISSUE THREAD

**Issue by ShilAggarwal** [postmanlabs/newman#782] opened 2016-11-28 12:00 UTC
Is there any option similar to Postman's "send and download" response body in newman cli.

Version and environment information:
-->
 1. Newman Version - 3.3.0:
 2. OS details  - Windows 7-x64:
 3. Using Newman via the CLI
 
<
3. For Postman Cloud / personal information related issues, send an email to: [help@getpostman.com](mailto:help@getpostman.com)

4. Verify that you have checked the documentation at https://www.getpostman.com/docs/newman_intro, and searched through previously closed issues.

5. Please ensure that all supporting files (collections or screenshots) do not contain any sensitive information.
-->

**Comment by kunagpal** [comment] 2016-11-28 12:07
Related to #413

**Comment by kunagpal** [comment] 2016-11-30 08:10
@czardoz @shamasis This would involve adding download helpers on a per-request basis.

**Comment by kunagpal** [comment] 2017-07-06 09:55
Closing as a duplicate of #413

**Closed by kunagpal** 2017-07-06 09:55 UTC
Labels: feature request
