### ISSUE TITLE
newman 5.0.0 crashes

### ISSUE THREAD

**Issue by seansensus** [postmanlabs/newman#2357] opened 2020-05-18 15:59 UTC
newman 5.0.0

Running against a postman collection which is purposely setup as an infinite loop to help me test for memory leaks in another application. After a day or so of running newman crashes.

Running from a windows 10 (1909) command prompt.
Expected behavior is newman runs until I hit cntl-c to stop it.
Couple crash dumps below.

-----------------------------------------------------------------------------------------------
<--- Last few GCs --->

[10636:000001948C7867B0] 97041151 ms: Mark-sweep 2030.4 (2051.0) -> 2029.4 (2052.0) MB, 1889.6 / 0.0 ms  (average mu = 0.258, current mu = 0.008) allocation failure scavenge might not succeed
[10636:000001948C7867B0] 97045445 ms: Mark-sweep 2030.4 (2052.0) -> 2029.4 (2051.0) MB, 2272.7 / 0.0 ms  (average mu = 0.388, current mu = 0.471) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF739FB730D]
Security context: 0x00c9f39408d1 <JSObject>
    1: push [000000C9F39575B9](this=0x021267188771 <JSArray[0]>,0x03741d5bb341 <Socket map = 000002AB0FCF59A9>)
    2: /* anonymous */ [000003741D5BA741] [_http_agent.js:118] [bytecode=000000C2462D3DF1 offset=402](this=0x01e67a1f28f1 <Agent map = 0000013EB45E7E49>,0x03741d5bb341 <Socket map = 000002AB0FCF59A9>,0x03741d5bc891 <Object map = 000002AB0FCF4059>...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200516.002719.10636.0.001.json
Node.js report completed
 1: 00007FF7393ACF2F napi_wrap+112799
 2: 00007FF73934CF26 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+55702
 3: 00007FF73934DDB3 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+59427
 4: 00007FF739B6A27E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF739B52351 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF739A1E8AC public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF739A29AE0 public: void __cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) __ptr64+1312
 8: 00007FF739A26604 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF739A1BE03 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF739A1A474 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2452
11: 00007FF739A3B67D public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType,enum v8::internal::AllocationOrigin) __ptr64+61
12: 00007FF7397A13D1 public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __ptr64+1665
13: 00007FF739FB730D public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+546637
14: 00007FF739F6132E public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+194414
15: 00007FF739F3C2BC public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+42748
16: 00000201F0B45EB8

<--- Last few GCs --->

[1348:000002AC34DD9F30] 97116321 ms: Mark-sweep 2029.5 (2051.5) -> 2029.4 (2051.5) MB, 1508.2 / 0.0 ms  (average mu = 0.205, current mu = 0.163) allocation failure GC in old space requested
[1348:000002AC34DD9F30] 97118166 ms: Mark-sweep 2029.8 (2051.5) -> 2029.4 (2051.5) MB, 1533.6 / 0.0 ms  (average mu = 0.188, current mu = 0.169) allocation failure GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF739FB730D]
    1: StubFrame [pc: 00007FF739F3CAA7]
Security context: 0x026ff56c08d1 <JSObject>
    2: new constructor(aka Request) [000002133618CDE9] [C:\Users\tester\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\postman-request\request.js:183] [bytecode=0000027492CDC979 offset=365](this=0x028117f00e91 <Request map = 000003189513EEB9>,0x028117f01489 <Object map = 000001BC697...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7393ACF2F napi_wrap+112799
 2: 00007FF73934CF26 v8::base::CPU::has_sse+55702
 3: 00007FF73934DDB3 v8::base::CPU::has_sse+59427
 4: 00007FF739B6A27E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF739B52351 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF739A1E8AC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF739A29AE0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF739A26604 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF739A1BE03 v8::internal::Heap::CollectGarbage+1283
10: 00007FF739A1A474 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF739A38E72 v8::internal::Factory::NewBytecodeArray+114
12: 00007FF7399847D6 v8::internal::interpreter::BytecodeArrayWriter::ToBytecodeArray+102
13: 00007FF739993781 v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray+129
14: 00007FF73997561C v8::internal::interpreter::BytecodeJumpTable::ConstantPoolEntryFor+1068
15: 00007FF73996525A v8::internal::UnoptimizedCompilationInfo::operator=+1274
16: 00007FF739AC23C9 v8::internal::Compiler::FinalizeBackgroundCompileTask+1065
17: 00007FF739AC2B39 v8::internal::Compiler::FinalizeOptimizedCompilationJob+1817
18: 00007FF739AC2977 v8::internal::Compiler::FinalizeOptimizedCompilationJob+1367
19: 00007FF739AC1050 v8::internal::Compiler::Compile+1392
20: 00007FF739AC0985 v8::internal::Compiler::Compile+213
21: 00007FF7397BA36A v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+103962
22: 00007FF739FB730D v8::internal::SetupIsolateDelegate::SetupHeap+546637
23: 00007FF739F3CAA7 v8::internal::SetupIsolateDelegate::SetupHeap+44775
24: 00007FF739F3C2BC v8::internal::SetupIsolateDelegate::SetupHeap+42748
25: 00007FF739F37850 v8::internal::SetupIsolateDelegate::SetupHeap+23696
26: 00007FF73A01BAF0 v8::internal::SetupIsolateDelegate::SetupHeap+958256
27: 00007FF739F3C2BC v8::internal::SetupIsolateDelegate::SetupHeap+42748
28: 00007FF739F3C2BC v8::internal::SetupIsolateDelegate::SetupHeap+42748
29: 00007FF739F3C2BC v8::internal::SetupIsolateDelegate::SetupHeap+42748
30: 00007FF739F355EC v8::internal::SetupIsolateDelegate::SetupHeap+14892
31: 00007FF739F3C2BC v8::internal::SetupIsolateDelegate::SetupHeap+42748
32: 00007FF739F355EC v8::internal::SetupIsolateDelegate::SetupHeap+14892
33: 000002C26B0E11AD

**Comment by codenirvana** [comment] 2020-05-18 16:04
@seansensus Thanks for reporting this issue, this is happening because Newman internally accumulates all the interaction data to generate the report.
We are thinking of adding an option to stop the accumulation completely for use-cases like this.

Closing as duplicate of #941.

**Closed by codenirvana** 2020-05-18 16:04 UTC
