### ISSUE TITLE
Not able to run the Postman as Job in kubernetes

### ISSUE THREAD

**Issue by uttamanand-whs** [postmanlabs/newman#2840] opened 2021-09-15 22:04 UTC
Version and environment information:
-->
 1. Newman Version (can be found via `newman -v`): 5.3.0
 2. OS details (type, version, and architecture): minikube version: v1.17.0 
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: I am using it newly
 4. Expected behaviour: Test result should come
 5. Command / script used to run Newman:

Kubectl apply -f newman.yml

newman.yml -: 

-----
apiVersion: batch/v1
kind: Job
metadata:
  name: api-tests
  namespace: default
spec:
  parallelism: 1
  template:
    metadata:
      name: api-tests
    spec:
      containers:
      - name: api-tests
        image: postman/newman
        command: ["run"]
        args: ["./VS-workspace/contract-tests-postman.yml","--reporters","cli","--reporter-cli-no-failures"]
      restartPolicy: Never

-------

Error -: 
  Warning  Failed     39s   kubelet            Error: failed to start container "api-tests": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "run": executable file not found in $PATH: unknown

**Comment by bioslikk** [comment] 2022-03-02 16:43
Hi @uttamanand-whs 
Not sure if you solved this issue already but have you heard about [Testkube](https://github.com/kubeshop/testkube) ? It allows you to run your postman tests in Kubernetes without needing to use newman or configuring any docker image. Feel free to give it a shot! 
In case there's something missing for you, feel free to open an issue for it. I'm someone deeply involved in that project and I'll be able to help you :)

**Comment by jbusuttil83** [comment] 2022-05-19 09:21
@uttamanand-whs did you solve this? I am having the same issue when trying to run newman as a job in kubernetes

**Comment by dilee** [comment] 2022-08-09 11:59
This is not a bug. Please refer to this answer: https://stackoverflow.com/a/49657024/4699073

**To quote:** 

Kubernetes provides us with multiple options on how to use these commands:
When you override the default Entrypoint and Cmd in Kubernetes .yaml file, these rules apply:

- If you do not supply command or args for a Container, the defaults defined in the Docker image are used.
- If you supply only args for a Container, the default Entrypoint defined in the Docker image is run with the args that you supplied.
- If you supply a command for a Container, only the supplied command is used. The default EntryPoint and the default Cmd defined in the Docker image are ignored. Your command is run with the args supplied (or no args if none supplied).

Refer to the following example:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: job-1
spec:
  template:
    metadata:
      name: job-1
    spec:
      containers:
      - name: newman
        image: postman/newman:alpine
        imagePullPolicy: IfNotPresent
        args: ["run", "-h"]
      restartPolicy: OnFailure
```

Since the command "newman" is already set as the entrypoint in the [Dockerfile](https://github.com/postmanlabs/newman/blob/develop/docker/images/alpine/Dockerfile), you only need to provide arguments here

**Comment by malvikach** [comment] 2022-12-14 13:57
Closing this issue, please feel free to reopen if this doesn't solve the problem

**Closed by malvikach** 2022-12-14 13:57 UTC
Labels: bug, kubernetes, product/newman
