### ISSUE TITLE
exporting a collection - sends body in GET requests, if the previously had a body

### ISSUE THREAD

**Issue by Eli-Goldberg** [postmanlabs/newman#868] opened 2017-01-15 12:53 UTC
1. Newman Version **3.4.2**
 2. OS details: **Ubuntu 16.04**
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: **First time**
 4. Expected behaviour: **exporting collections to JSON should not include body in get requests**
 5. Command / script used to run Newman: **newman run <collection> -e <env path> --bail --folder <folder_name>**
 6. Sample collection, and auxilliary files (minus the sensitive details): **can't supply**
 7. Screenshots (if applicable): **can't supply**

Steps to reproduce the problem:

1. Create a collection, a folder and a GET request
2. save, and export the request to JSON (v2 format for instance)
3. change the request to POST, add a body to the request and repeat step 2
4. change the request to GET (body should be disabled in GUI), repeat step 2
5. when running the exported collection, the body will be actaully sent in the GET request

**Comment by shamasis** [comment] 2017-01-16 04:51
Not keeping the old body saved is data loss we cannot have. We can stop sending the body though. However, there are apis (such as elastic search API) which use get body.

@czardoz - are we sending get body in app? If not then we should stop it in Newman too.

**Comment by Eli-Goldberg** [comment] 2017-01-16 04:59
in the app, body is not sent, but also disabled- and there is not indication it has anything in it (no green dot).

**Comment by kunagpal** [comment] 2017-04-03 11:36
Closing as a duplicate of #751

**Closed by kunagpal** 2017-04-03 11:36 UTC
Labels: duplicate, runtime
