### ISSUE TITLE
Newman html report displays chained requests as only one request.

### ISSUE THREAD

**Issue by saradraj** [postmanlabs/newman#1757] opened 2018-10-17 04:23 UTC
In my collection, I am looping one request multiple times with different data set. When I view the newman html report, chained requests are displayed as one request. Is this by design in newman html report? I am expecting each request to be displayed separately with its assertions in html report even though same request is looped. 
![2018-10-16_23-18-29](https://user-images.githubusercontent.com/1631595/47062142-2aeacd80-d19a-11e8-8d23-43bdcee4763d.png)

All four assertions for same looped request is displayed as one whole request, Is there a way to show separately in html report?

**Comment by codenirvana** [comment] 2018-10-17 06:39
Duplicate of #1688

@saradraj https://github.com/postmanlabs/newman/issues/1688#issuecomment-415644238

**Closed by codenirvana** 2018-10-17 06:39 UTC
