### ISSUE TITLE
Error: unexpected end of file at Zlib._handle.onerror

### ISSUE THREAD

**Issue by davenewza** [postmanlabs/newman#379] opened 2016-04-07 14:10 UTC
Running newman 2.0.6 on our build is now throwing the following error:

> RequestError: [3da18a82-79ca-abd8-20e5-390b4e6affd8] 'Some Action' terminated. Complete error: 
> Error: unexpected end of file
> at Zlib._handle.onerror (zlib.js:363:17)
> ├ù Is 401
>  Finished running Newman tests.

The collection is built using Postman 4.1.3.  The collection runs perfectly fine in the Postman Collection Runner.

It's happening on a few items in our collection.  This is one of them:

```
{
	"id": "f6c21354-80f0-ddd2-8782-fe9ff7331dde",
	"headers": "Content-Type: application/json\nAccept: application/json\n",
	"url": "{{Url}}/something",
	"preRequestScript": "",
	"pathVariables": {},
	"method": "GET",
	"data": [ ],
	"dataMode": "params",
	"version": 2,
	"tests": "tests[\"Is 401\"] = responseCode.code === 401;",
	"currentHelper": "normal",
	"helperAttributes": {},
	"time": 1449121531396,
	"name": "Some Action",
	"description": "",
	"collectionId": "0d31daa7-e3ae-094b-4ff5-920ca7683748",
	"responses": []
},
```

I have tried replacing it but to no avail.

**Comment by davenewza** [comment] 2016-04-07 14:30
This seems to be happening on around half of our requests out of the blue.

**Comment by czardoz** [comment] 2016-04-07 16:08
@davenewza, what Node version are you using?

**Comment by davenewza** [comment] 2016-04-08 06:21
@czardoz v5.10.1

**Comment by czardoz** [comment] 2016-04-08 06:45
Ah, looks like a duplicate of https://github.com/postmanlabs/newman/issues/319

1. Are you able to consistently reproduce this issue?
2. Do you run into this with Node v4.x as well?

**Comment by davenewza** [comment] 2016-04-08 07:06
1. Yes, it consistently fails on specific requests.
2. Just tested this and it runs fine on Node v4.x. Will have to downgrade (thanks)

**Comment by czardoz** [comment] 2016-04-18 10:02
Fixed on develop, will be available in the next release.

**Closed by czardoz** 2016-04-18 10:02 UTC
