### ISSUE TITLE
newman fails on 2000th interation, consistently

### ISSUE THREAD

**Issue by filfreire** [postmanlabs/newman#2044] opened 2019-06-24 15:47 UTC
It seems that when running a large number of iterations of the same collection, for example, with a single request in each iteration, newman will consistently fail upon reaching the 2000th iteration.

I've seen this happening at least 3 times in a row.

More information:
 1. Newman Version `4.5.0`
 2. OS details: MacOS Mojave `10.14.4`
 3. Are you using Newman as a library, or via the CLI? `cli`
 3. Did you encounter this recently, or has this bug always been there: recently
 5. Command / script used to run Newman:
```
newman run src/example.postman_collection.json -e src/env/example.postman_environment.json -n 50000 > output.txt
```

**Error log:**
```
Iteration 2000/50000

→ 1 Example collection
  POST https://example/ _tls_wrap.js:546
  self._destroySSL();
       ^

TypeError: Cannot read property '_destroySSL' of undefined
    at Timeout.destroySSL [as _onTimeout] (_tls_wrap.js:546:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

I cannot share more details at the time, since info is sensitive, but you should be able to reproduce this with a simple collection, for example, calling a `POST /some-endpoint`

/cc @kunagpal @codenirvana @shamasis

**Comment by codenirvana** [comment] 2019-06-24 15:52
@filfreire Thanks for reporting.
This is a known issue in Node v12, Refer: https://github.com/postmanlabs/newman/issues/2015

Can you confirm the Node version (`node -v`) used for the Newman run?

**Comment by filfreire** [comment] 2019-06-24 15:54
@codenirvana I have version `12.3.1`

**Comment by codenirvana** [comment] 2019-06-24 16:03
@filfreire Thanks for the confirmation.

We are aware of this issue but facing trouble reproducing this in isolation because it's happening at the very low-level library (and specifically in Node v12).

For now, can you try using Newman in Node v10 ([nvm](https://github.com/nvm-sh/nvm/blob/master/README.md) is a great tool to switch between Node versions)?
We'll fix this as soon as possible! 😅 

Closing as duplicate of #2015

**Closed by codenirvana** 2019-06-24 16:03 UTC

**Comment by filfreire** [comment] 2019-06-24 16:05
@codenirvana ok, I'm trying now with node 10, thanks mate! 👍

**Comment by wibobm** [comment] 2019-09-09 23:45
It's September and newman is still incompatible with node 12 which will be LTS very soon...
