### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by krabidzus** [postmanlabs/newman#2101] opened 2019-08-23 14:32 UTC
Hi, 
In new versions (4.5.4) of newman I cannot upload files by put path to src in collection.json. I am able to do that in version 4.5.0 but not in new verison. Is there some change of uploading files?

**Comment by codenirvana** [comment] 2019-08-26 05:46
Possible duplicate of #2081

Try removing the `Content-Type` header from the failing request with `formdata` body.

Refer: https://github.com/postmanlabs/newman/issues/2081#issuecomment-519149629 for more detail.

**Closed by codenirvana** 2019-08-26 05:46 UTC
