### ISSUE TITLE
Newman refuses csv data with double quotes in the values

### ISSUE THREAD

**Issue by mgroeneweg** [postmanlabs/newman#1344] opened 2017-12-14 07:22 UTC
1. Newman Version (can be found via `newman -v`): 3.9.1
 2. OS details (type, version, and architecture): Windows 10 64 bits
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Today
 4. Expected behaviour: Handle  values with "" in them correctly
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

We need to pass a JSON array to a service. When I use a value like **"[""BE"", ""NL"", ""FR"", ""LU"", ""EN"", ""GB"", ""DE""]"** in the CSV the collection runner picks it up as a single value and changes the "" to \" in the preview. The test runs fine.

Newman throws an error:
Invalid closing quote at line 2; found "\"" instead of delimiter ","

**Comment by kunagpal** [comment] 2017-12-14 07:40
You'll have to escape `"` in CSV values by prefixing them with a `\`. For instance, the appropriate way to represent your sample data above would be:
```
"["\"BE\"", "\"NL\"", "\"FR\"", "\"LU\"", "\"EN\"", "\"GB\"", "\"DE\""]"
```

Additionally, since the values themselves are surrounded by double quotes, a workaround is to add the quotes yourself within pre-request scripts.

**Comment by mgroeneweg** [comment] 2017-12-14 07:48
Thanks for the quick follow up!

I tried escaping them but a little differently. I will experiment further or fix this using a pre-request script.

But still, test data that is picked up correctly in the collection runner results in an error when used in NewMan.

**Comment by davecanderson** [comment] 2018-01-08 05:39
I have a similar issue and no combination of escaping seems to work;

`CSV Test,{ Prop: \"Value\" }` truncates to `{ Prop:`
`CSV Test,{ Prop: ""Value"" }` newman : Invalid opening quote at line 2
`CSV Test,"{ Prop: ""Value"" }"` newman : Invalid closing quote at line 2; found "\"" instead of delimiter ","
`CSV Test,"{ Prop: \"Value\" }"` truncates to `{ Prop:`
CSV Test,"{ Prop: \"\"Value\"\" }" truncates to `{ Prop:`

I'm using ServiceStack to deserialize the request into an object and using `"{ Prop: \"Value\" }"` works fine in the body from Postman but not when substituted from the CSV file with Newman.

**Comment by kunagpal** [comment] 2018-01-11 12:25
@davecanderson I was able to get the following CSV file working:
```
a,b
1,{\"Prop\": \"Value\"}
```

In order to use this value as JSON inside your scripts, you can use the following:
```js
var object = JSON.parse(data.b);
object.Prop // "Value"
```
Here, `data` is an inbuilt variable, which contains the set of iteration data values for the current iteration.

**Comment by codenirvana** [comment] 2018-08-24 10:15
@mgroeneweg Could you confirm if this issue persists with Newman v4?

**Comment by codenirvana** [comment] 2018-08-24 10:34
@mgroeneweg Thanks for the response, I am also not able to reproduce this issue.
A lot of CSV parsing issues are fixed in [Newman v4](https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md#csv-auto-parse). Closing this for now.

**Closed by codenirvana** 2018-08-24 10:34 UTC
Labels: app parity, bug, question

**Comment by devil91221** [comment] 2019-07-17 11:51
I had similar kind of issue, wanted to use data from CSV in Newman for an Arraylist field-
"state": ["ABC","DEF","GHI"]

**So in CSV file, I used data as:** ABC|DEF|GHI
**In pre-request:** `pm.environment.set("arr_state" , pm.variables.get("state").replace(/\|/g,"\",\""));`
**In body:** `"state" : ["{{arr_state}}"]`

This worked for me, Hope it is helpful for someone else too.
