### ISSUE TITLE
How to work with long number with csv file?

### ISSUE THREAD

**Issue by amnoman** [postmanlabs/newman#1215] opened 2017-09-22 14:22 UTC
1. Newman Version (can be found via `newman -v`): 3.8.0
 2. OS details (type, version, and architecture):  Microsoft Windows [Version 10.0.15063], AMD64
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Always been there
 4. Expected behaviour: Suppose to parse the Long number without changing last 3-4 digit with 0.
 5. Command / script used to run Newman:  newman run "xxxx.postman_collection.json" -n 2 --f testFolder -e xxxx.postman_environment.json -d "TestData.csv" --ssl-client-cert xxxx.crt --ssl-client-key xxxx.key --ssl-client-passphrase xxxx
 6. Sample collection, and auxilliary files (minus the sensitive details):

TestData.csv
Iteration, expectedXXX
1,"89111702272002019559"
2, 89111702272002019542

-----------------------------------

when script executed "89111702272002019559" changes to 89111702272002020000 and 89111702272002019542 changes to 89111702272002020000

The same csv file works fine in Postman runner when use with double quotes for Iteration 1 but Iteration 2 that is 89111702272002019542 changes to 89111702272002020000

7. Screenshots (if applicable):

**Comment by kunagpal** [comment] 2017-09-26 07:50
@amnoman Thanks for reporting this, I was able to reproduce the bug with the details you provided. I'll update this thread when a fix is being worked on.

**Comment by kunagpal** [comment] 2017-09-26 10:53
I've opened a dedicated issue here: https://github.com/adaltas/node-csv-parse/issues/152

**Comment by saswatds** [comment] 2018-03-19 09:31
Hi @amnoman, we are now actively trying to resolve this issue, as a temporary fix you can quote numbers within a single quote `'89111702272002019559'` instead of double quote, in newman to preserve the number as a string and not loose precision.

The issue is the underlying `csv-parse` library which newman uses to parse csv files, for which we have raised an issue at https://github.com/adaltas/node-csv-parse/issues/182

**Comment by codenirvana** [comment] 2018-08-07 05:35
@amnoman a fix has been added in #1609 which will be rolled out with the v4 release.

You can test this using [v4.0.0-beta.2](https://www.npmjs.com/package/newman/v/4.0.0-beta.2).

**Comment by codenirvana** [comment] 2018-08-07 12:02
@amnoman This has been fixed in Newman v4.0.0.

**Closed by codenirvana** 2018-08-07 12:02 UTC
Labels: bug, csv, pending-close

**Comment by manojattal** [comment] 2019-10-23 14:54
I am facing this issue. I am on Postman 7.9.0. I am trying to read 19 digit number from csv file. But it rounding the number.
