### ISSUE TITLE
Newman not using authentication helpers?

### ISSUE THREAD

**Issue by neillboyd** [postmanlabs/newman#178] opened 2015-02-03 00:03 UTC
Quick query / issue - is there any known issue with Newman not using the authentication helpers from Postman?

The scenario is this - I have a collection that runs fine in Postman collection runner that uses the basic authentication helper for generated a Basic auth header from a username / password (these are pulled from environment variables from previous requests). As soon as I run these from Newman, it appears to use the Authorization header verbatim as from the collection (without applying the helper). I was able to prove this out by using a blank Auth header with the helpers defined and capturing the traffic showed blank auth headers and a 401 from the target server.

Apologies but I am unable to provide the full request details at the moment however, I feel the information provided is fairly self explanatory - authentication helpers using environment variables don't appear to be picked up from Newman - unless I'm doing something wrong?

$ newman --version
1.2.9

**Comment by abhijitkane** [comment] 2015-02-03 11:25
Auth Helpers are currently not supported in Newman. We're working on this, and hope to have it released  soon.

**Comment by neillboyd** [comment] 2015-02-19 10:40
Thanks for the feedback, anything to track this feature request or any estimated delivery? Just curious, as it would make a really neat feature :+1:

**Comment by abhijitkane** [comment] 2015-02-23 09:12
There's no concrete timeline as of now.

**Comment by ViBiOh** [comment] 2015-02-24 08:50
We have fixed this for basic auth, the one natively supported by request.js, here https://github.com/a85/Newman/pull/186

**Comment by neillboyd** [comment] 2015-03-09 13:15
Thanks @ViBiOh - that works - basic auth is all I'm really concerned about.

**Comment by Pr0ph3ta** [comment] 2015-03-18 14:37
Hi,
It seems that the Helpers for Basic Authentication isn't working again.
This is the sample request that i'm trying to use:

>{
	"id": "8db85b7f-318f-7e9e-a986-9e69f5c18a82",
      "headers": "Authorization: Basic REVGQVVMVFxBZG1pbjpBZG1pbg==\nContent-Type: application/xml\n",
			"url": "http://{{server}}:{{port}}/ism/2/infomodinstances/com.lopes.tt.cpp.drivers.winer-{{winerNum}}-312096207/fbinstances/currentSetpoint/operations",
			"preRequestScript": "",
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"version": 2,
			"tests": "tests[\"Status code is 204\"] = responseCode.code === 204;",
			"currentHelper": "basicAuth",
			"helperAttributes": {
				"username": "DEFAULT\\Admin",
				"password": "Admin",
				"id": "basic",
				"timestamp": 1423830417702
			},
			"time": 1426687002662,
			"name": "Current Setpoint",
			"description": "",
			"collectionId": "b6a2fdc0-babe-7773-f8ca-43a846a2b839",
			"responses": [],
			"synced": false,
			"rawModeData": "<?xml version=\"1.0\" encoding=\"UTF-8\"?\><tns:refreshSetPoint xmlns:tns=\"http://tt.lopes.com/functionblock/LevelsAndSetpoints/TemperatureSetpoint/1\"\></tns:refreshSetPoint\>"
		}

**Comment by abhijitkane** [comment] 2015-03-18 16:51
@Pr0ph3ta The base version of Newman doesn't support Authentication Helpers yet.  The one referred to by @Pr0ph3ta above is a pull request - https://github.com/a85/Newman/pull/186. You can checkout the pull request for Basic Auth capabilities.

**Comment by abhijitkane** [comment] 2015-03-19 11:08
@Pr0ph3ta The latest version of Newman (v1.2.15) has support for Basic, Digest, OAuth1 (if the request saved from Postman has the helper data saved).

**Comment by Pr0ph3ta** [comment] 2015-03-24 09:07
I tried moments ago and it seems to not working correctly with basicAuth like the comment i did before. No idea about what's happening.

**Comment by abhijitkane** [comment] 2015-03-24 09:09
Are you on the latest version of Newman? (newman --version)

**Comment by Pr0ph3ta** [comment] 2015-03-24 11:53
Yes I'm using newman 1.2.15

**Comment by abhijitkane** [comment] 2015-03-24 12:06
What's the exact problem? Is the signature not being generated, or are you getting a wrong signature?

Newman has a test for the Basic Auth helper - not sure why it's failing.

**Comment by neillboyd** [comment] 2015-03-24 12:27
@abhijitkane @Pr0ph3ta I was using the changes from @ViBiOh and it works fine - switched to master here and it still works fine. Does the same request work in Postman itself?

**Comment by Pr0ph3ta** [comment] 2015-03-24 12:29
Yes it works inside Postman. I'm guessing is because of my user have domain included "DEFAULT\Admin".
How can i debug what authorization header is being generated?

**Comment by abhijitkane** [comment] 2015-03-24 12:39
In the test script, you can include this - 
`console.log("Auth header: " + postman.getResponseHeader("Authorization"));`

**Comment by Pr0ph3ta** [comment] 2015-03-24 14:21
I was trying few options until now and my guess is that the problem is that I'm beyond an NTLM proxy.
Inside Postman when I remove the authorization header it gaves me an 401 authorization error and not a 403 forbidden like newman.
Also the "postman.getResponseHeader("Authorization") gaves me an null object.

**Comment by abhijitkane** [comment] 2015-03-24 17:33
@Pr0ph3ta Apologies - this is what you can use - `console.log(JSON.stringify(request.headers["Authorization"]));`

The earlier script will print the response headers. It's the request headers that we need to check.

**Comment by Pr0ph3ta** [comment] 2015-03-25 09:26
@abhijitkane I tried again a few moments ago and the request.headers is generated perfectly like inside Postman.
The request generated inside Postman works like it supposed inside newman it gaves an 403 Forbidden. This can only be related being behind a corporate proxy and newman is not aware of that situation.

**Comment by czardoz** [comment] 2015-10-02 09:52
This issue has been fixed, and tests have been added: https://github.com/postmanlabs/newman/blob/develop/tests%2Finteg_tests%2Fhelper.postman_collection

Closing the issue, feel free to reopen in case anyone is still facing problems.

**Closed by czardoz** 2015-10-02 09:52 UTC
Labels: bug
