### ISSUE TITLE
cannot install newman (postinstall jsdom issue)

### ISSUE THREAD

**Issue by Fr4ncis** [postmanlabs/newman#288] opened 2015-11-05 12:07 UTC
fmattia$ sudo npm install -g jsdom newman@beta
/usr/local/bin/newman -> /usr/local/lib/node_modules/newman/bin/newman

> newman@2.0.0-beta.1 postinstall /usr/local/lib/node_modules/newman
> node scripts/postinstall.js

Could not install "jsdom"
/usr/local/lib/node_modules/newman/scripts/postinstall.js:25
                throw err; // Will cause the script to exit with a non zero code
                ^

Error: EACCES: permission denied, open '/Users/fmattia/.npm/jsdom/6.3.0/package/package.json.a89506cc8fde07a209689a5e8f6336fd'
    at Error (native)

**Comment by czardoz** [comment] 2015-11-05 12:11
Looks like a permissions issue. Any reason why you are installing jsdom along with Newman?
Newman will take care of installing jsdom itself.

**Comment by Fr4ncis** [comment] 2015-11-05 12:14
fmattia:Documents fmattia$ sudo npm install -g jsdom

goes well, while

fmattia:Documents fmattia$ sudo npm install -g newman@beta

has the same issue reported above.

As you can see I am performing the command as root.

**Comment by czardoz** [comment] 2015-11-05 12:15
Can you remove the jsdom you installed globally and then install just newman?

**Comment by Fr4ncis** [comment] 2015-11-05 12:16
fmattia:Documents fmattia$ sudo npm uninstall -g jsdom
unbuild jsdom@7.0.2
fmattia:Documents fmattia$ sudo npm install -g newman@beta
/usr/local/bin/newman -> /usr/local/lib/node_modules/newman/bin/newman

> newman@2.0.0-beta.1 postinstall /usr/local/lib/node_modules/newman
> node scripts/postinstall.js

Could not install "jsdom"
/usr/local/lib/node_modules/newman/scripts/postinstall.js:25
                throw err; // Will cause the script to exit with a non zero code
                ^

Error: EACCES: permission denied, open '/Users/fmattia/.npm/jsdom/6.3.0/package/package.json.ec46814a100f9f1556cdf8ca9d9fa5e4'
    at Error (native)

**Comment by czardoz** [comment] 2015-11-05 12:17
That's weird.. what's the output of 
``ls -l '/Users/fmattia/.npm/jsdom/6.3.0/package/package.json.ec46814a100f9f1556cdf8ca9d9fa5e4'``

**Comment by Fr4ncis** [comment] 2015-11-05 12:21
Sorted as non root user, probably I installed some modules as root and some as normal user. Changed permissions to ~/node_modules/ and it worked as normal user. Thanks!

**Comment by cyrildubus** [comment] 2015-11-23 10:41
Hi same problem here, 

When we try as root, we got a permission problem. Tested on debian 8 and debian 7 with nodejs v4.2.2.

Here is the trace

/usr/local/bin/newman -> /usr/local/lib/node_modules/newman/bin/newman

> newman@2.0.0-beta.2 postinstall /usr/local/lib/node_modules/newman
> node scripts/postinstall.js

Could not install "jsdom"
/usr/local/lib/node_modules/newman/scripts/postinstall.js:25
                throw err; // Will cause the script to exit with a non zero code
                ^

Error: EACCES: permission denied, mkdir '/root/.npm/jsdom/6.3.0/package'
    at Error (native)
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "newman@beta"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! newman@2.0.0-beta.2 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the newman@2.0.0-beta.2 postinstall script 'node scripts/postinstall.js'.
npm ERR! This is most likely a problem with the newman package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls newman
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cyril/sandbox/npm-debug.log

[npm-debug.txt](https://github.com/postmanlabs/newman/files/41479/npm-debug.txt)

**Comment by czardoz** [comment] 2015-11-23 11:22
I think I see what the problem is. Will fix this in the next release. Thanks for the detailed stack trace!

**Comment by czardoz** [comment] 2015-12-01 10:40
Fixed with cc0dd557eb9bc387cfa1fe84bc36ed00363f98d5

**Closed by czardoz** 2015-12-01 10:40 UTC
