### ISSUE TITLE
Newman docker returns AssertionError

### ISSUE THREAD

**Issue by tomisaacson** [postmanlabs/newman#2008] opened 2019-05-16 20:23 UTC
1. Newman Version (can be found via `newman -v`):
I'm using the docker postman/newman:alpine
 2. OS details (type, version, and architecture):
Docker is running on Ubuntu 18.04
 3. Are you using Newman as a library, or via the CLI?
CLI
 4. Did you encounter this recently, or has this bug always been there:
Recently.
 5. Expected behaviour:
No assert.
 6. Command / script used to run Newman:
I'm running from Python so my code is:
```
    output_file = 'output.json'
    command = "run " + test_file + " -e " + test_environment
    if test_timeout > 0:
        command += " --timeout-request " + str(test_timeout)
    command += " --reporters cli,json --reporter-json-export " + output_file
    try:
        client.containers.run(
            "postman/newman:alpine",
            command,
            volumes={dir: {'bind': '/etc/newman', 'mode': 'rw'}})
```
The request is just a POST to an API with an API key then a test on the result to make sure it's 200.
This was working fine a few weeks ago and I don't think I've changed anything. It works fine if I just call the API using cURL or if I use Postman v6.7.1. But if I run in the Docker instance I get:
```
          {
            "assertion": "Status code is 200",
            "skipped": false,
            "error": {
              "name": "AssertionError",
              "index": 0,
              "test": "Status code is 200",
              "message": "expected { Object (id, _details, ...) } to have property 'code'",
              "stack": "AssertionError: expected { Object (id, _details, ...) } to have property 'code'\n   at Object.eval sandbox-script.js:1:1)"
            }
          },

```

**Comment by codenirvana** [comment] 2019-05-16 20:39
@tomisaacson What's the assertion? Is it just `pm.response.to.have.status(200)` ?
Also, is this started failing recently?

**Comment by tomisaacson** [comment] 2019-05-16 20:43
Yes, the test is just:
```
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});
```
Where should I get more information about the assertion?

**Comment by adrijshikhar** [comment] 2020-03-12 10:00
@codenirvana does this issue still persist?

**Comment by codenirvana** [comment] 2020-05-25 22:18
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 22:18 UTC
Labels: getting-started, pull request needed
