### ISSUE TITLE
Newman Blows Up on Tests

### ISSUE THREAD

**Issue by kulisics** [postmanlabs/newman#396] opened 2016-05-05 02:40 UTC
I created a path in Postman as follows.

{{BASEURL}}/{{FILES_SERVICE}}/{{FILES_VERSION}}media/system/{{storageSystemId}}/{{TEST_DIR_ENCODED}}/apps

I created a directory, wc-1.00, at the resulting location.

I then access the constructed directory to upload a file. The URL is:

{{BASEURL}}/{{FILES_SERVICE}}/{{FILES_VERSION}}media/system/{{storageSystemId}}/{{TEST_DIR_ENCODED}}/apps/wc-1.00

When the test is run in Newman, it blows up with the following error.

201 768ms Create Directory for apps/wc-1.00 https://public.tenants.prod.agaveapi.co/files/v2/media/system/storage-postman.systems-sandbox.tacc.utexas.edu/postman-test-apitest-1462414601958/apps
    ✔ Create Directory for apps: Status code 201 . . . 
    ✔ Create Directory for apps: Result is JSON . . . 
    ✔ Create Directory for apps: Checking status . . . 
    ✔ Create Directory for apps: Checking message . . . 

path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:265:21
    at Function._.each._.forEach (/usr/local/lib/node_modules/newman/node_modules/underscore/underscore.js:153:9)
    at Object.jsface.Class._setFormDataIfParamsInRequest (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:260:9)
    at Object.jsface.Class._execute (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:202:9)
    at null._onTimeout (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:222:11)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

The error is on the test following the successes. As you can see from the URLs, the variables in the URL resolve to string names.

Is there any way to get more information about the problem like what specifically is upsetting newman? Thanks.

**Comment by czardoz** [comment] 2016-05-05 07:45
Weird, I'm not able to reproduce this. Can you share a sample collection that blows up this way?
I think that it's the request _after_ this one that's causing the failure.

**Comment by kulisics** [comment] 2016-05-05 13:53
I'd send you the collections, but they'd probably be of little help if I
strip out the authentication information required to run them. In any case,
I have found the exact problem.

Here is the Postman version:

4.1.3
linux / x86-64
Chrome 50.0.2661.75

The problem is that when you use 'form-data` as the body type and choose a
file to upload as a field, (called 'fileToUpload' in my case, for example),
and then save the test, Postman fails to write out a string for the
filename. In the exported collection run with newman, I get the following
lines for the file that should have been saved as 'wrapper.sh'.

2615                         "data": [
2616                                 {
2617                                         "key": "size",
2618                                         "value": "original",
2619                                         "type": "text",
2620                                         "enabled": true
2621                                 },
2622                                 {
2623                                         "key": "fileName",
2624                                         "value": "wrapper.sh",
2625                                         "type": "text",
2626                                         "enabled": true
2627                                 },
2628                                 {
2629                                         "key": "fileToUpload",
2630                                         "value": {
2631                                                 "0": {}
2632                                         },
2633                                         "type": "file",
2634                                         "enabled": true
2635                                 }
2636                         ],


You can see that the value field is not correct. If I use vi to change it
to "wrapper.sh", the uncaught exception no longer occurs.

To me, this seems like kind of a serious user interface defect. The problem
can be reproduced 100% of the time by simply making any modification to a
test that has a file for upload, saving the modification, and exporting the
set to a file to run with Newman. To get the values back into the interface
in a persistent way, you have to delete the local collection and reload the
corrected collection from a file---obviously, if you just correct the
exported file, modify the collection again, and reexport the tests, you
lose the corrections---and all of the deletions seem like risky operations.

**Comment by czardoz** [comment] 2016-05-06 07:14
File uploads are actually a known limitation for which we've not yet found a good solution. The problem is, collections are meant to be shared amongst teams, and everyone keeps files in different directories, so storing the file path does not make sense. 

Another option is to store the file content in the collection itself, but that can become just too big, so we don't do that. 

This use case is documented here: https://www.getpostman.com/docs/run_file_post_requests

**Comment by kulisics** [comment] 2016-05-06 17:01
I don't think that you understand the problem. This is not a problem with
my understanding of the use cases. ** This is a real bug. **

I was running the collection from newman as described in the link, and the
uncaught exception and application fault in my original post was from a
newman run.

The problem is that Postman produced a JSON file that was incorrect. It
didn't include a filename for the value key in the black that I pasted into
my last message.

** This used to work in the last version of Postman. **

In the last version, the interface was terribly clunky---every time that
you edited a test uploading a file, you had to reselect the file to upload
or it would get no value in the output JSON---but the work around was
relatively simple. I just reselected the file any time that I edited a test
with a file upload. This problem is much more severe. No matter what I
select for the file upload, Postman writes out value in JSON that causes
the newman run to blow up with the uncaught exception in my original post.
I have to edit the JSON by hand, which seems like a serious problem since
this didn't happen in the last version.

Just to reemphasize:
** This is a problem with the way that Postman writes JSON when the user
constructs a test to upload a file using the Postman interface.
** This used to work albeit with some workarounds.

**Comment by deardooley** [comment] 2016-05-06 17:52
+1 this is the reason we're not onboarding our entire dev team to a paid annual cloud subscription. Sync regularly deletes tests we're writing in different collections and import/export changes the tests we've written so we can't effectively collaborate and still maintain integration with our existing build/test process. Great tool, just stuff like this keep it from being enterprise ready...as much as we'd love for it to be.

**Comment by a85** [comment] 2016-05-06 17:59
@deardooley We'd like to see why sync is regularly deleting stuff for you or your team. Can you email us at help@getpostman.com. Post video calls what we have found out is people keeping old requests open and then overwriting someone else's tests. We have an activity feed in the website now that should help in diagnosing these issues. This + notifications is coming in the app in May.

@kulisics We are investigating the issue. Might be a bug introduced in a recent version.

**Comment by abhijitkane** [comment] 2016-05-09 07:24
@kulisics Right. We'll be pushing a fix for this in the next version of the app.

**Comment by abhijitkane** [comment] 2016-05-16 09:36
@kulisics Can you confirm this fixed in the latest version of the app?

**Comment by kulisics** [comment] 2016-05-18 14:15
As far as I can tell so far, the problem appears resolved. Thanks.

**Closed** 2016-05-18 14:16 UTC
Labels: bug, non-newman
