### ISSUE TITLE
Newman doesn't take environment variables with updated value for second run instance

### ISSUE THREAD

**Issue by SarathkumarRajendran** [postmanlabs/newman#2199] opened 2019-12-20 00:04 UTC
1. Newman Version (can be found via `newman -v`): 4.5.7
 2. OS details (type, version, and architecture): Mac 10.14.3
 3. Are you using Newman as a library, or via the CLI? Library
 4. Expected behaviour: Updated environment value should be used

Steps to reproduce the problem:

 - Instead of having pre-requisite scripts in postman collection request, passing the value from node js script to update environment variable json file
 - Then calling newman runner with some folders to get executed
 - Again updating environment file for same keys with different input value
 - Again calling  newman runner with same folders to get executed
  
so the test will be executed as follows,
 - update environment json file
 - call newman runner
 - again update environment json file
 - again call newman runner

Issue facing: For the second call of newman runner, it still runs the test with previously updated environment file values, NOT TAKING THE NEWLY UPDATED ENVIRONMENT VARIABLE VALUE
Though, when we open the environment file, could see that new value is updated 

NOTE:
 - **updateEnvironmentVariable** is a function to read environment variable json file and update values
 - **readWriteJSON** is a function to read the Main JSON collection containing N number of folders and create new JSON with only the required list of folders

Test Scripts:

    **var testuuid = uuid();
    await updateEnvironmentVariable('testuuid', testuuid);
    var phone = '81' + Math.floor(Math.random() * 9000000000)
    await updateEnvironmentVariable('phone', phone); 

    var blocks = ['CreateAndGetMember', 'GetProfile']; 
    var file = readWriteJSON(blocks);

    await newmanRun(file).then(function ([responseList, envVariables]) {
      var idResponse = JSON.parse(responseList.get('GET_Member'));
      assert.equal(phone, idResponse.phones[0].phoneNumber)
    })

    var phone_updated = '81' + Math.floor(Math.random() * 9000000000);
    await updateEnvironmentVariable('phone', phone_updated);  
      

    await newmanRun(file).then(function ([responseList, envVariables]) {
        var idResponse = JSON.parse(responseList.get('GET_Member'));
        assert.equal(phone_updated, idResponse.phones[0].phoneNumber)
    })**

**Below is newman run function:**

**async function newmanRun(filename) {
  return new Promise((resolve, reject) => {
    let map = new Map()
    newman.run({
      collection: require('../test/archive/'+ filename +'.json'),
      environment: require('../test/archive/test.postman_environment.json'),
    }).on('request', function (err, args) {
      if (err) { reject(err) } else {
        map.set(args.item.name, args.response.stream.toString())
      }
    }).on('done', function (err, summary) {
      if (err) { reject(err) } else {
        var env = JSON.stringify(summary.environment)
        resolve([map, env])
      }
    })
  })
}**

Can you please check this and help me with the solution?

**Comment by arkadiyala** [comment] 2020-02-14 21:22
Hey SharathKumar - I'm sorry, i'm unable to help you. But looks like you could help me on below.

My script is not updating token into environment.json and retrieving same token from environment.json to use the same in next POST request.  Could you please help me

Here is my ticket: https://github.com/postmanlabs/newman/issues/2225

**Comment by codenirvana** [comment] 2020-05-25 22:58
Promises and async/await are not supported at the moment.
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/4131

**Closed by codenirvana** 2020-05-25 22:58 UTC
