### ISSUE TITLE
Newman formdata POST not passing 'file' key

### ISSUE THREAD

**Issue by jimlinx** [postmanlabs/newman#2093] opened 2019-08-15 06:11 UTC
1. Newman Version (can be found via `newman -v`):
4.5.4

 2. OS details (type, version, and architecture):
macOS Mojave

 3. Are you using Newman as a library, or via the CLI?
CLI

 3. Did you encounter this recently, or has this bug always been there:
This is working fine if I use v4.5.1, but v4.5.2 / v4.5.3 / v4.5.4 will run into this issue.

 4. Expected behaviour:
Upload of file using formdata mode should pass the 'file' key, it looks like that is not happening in ^4.5.2

 5. Command / script used to run Newman:
newman run uploadFile.json -e environment.json -g globals.json --insecure

 6. Sample collection, and auxiliary files (minus the sensitive details):

`
{
  "info": {
    "name": "QA_Debug",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "item": [
    {
      "name": "Simple Test",
      "item": [
        {
          "name": "Upload Trial",
          "event": [
            {
              "listen": "test",
              "script": {
                "exec": [
                  "(pm.response.code != 201) ? console.log('[' + pm.response.code + ']: ' + JSON.parse(responseBody).message): {};",
                  "var response = JSON.parse(responseBody);",
                  "var jsonStr = JSON.stringify(response.errors);",
                  "console.log(jsonStr);"
                ],
                "type": "text/javascript"
              }
            },
            {
              "listen": "prerequest",
              "script": {
                "exec": [
                  ""
                ],
                "type": "text/javascript"
              }
            }
          ],
          "request": {
            "method": "POST",
            "header": [
              {
                "key": "Authorization",
                "type": "text",
                "value": "Bearer {{JWT_TOKEN}}"
              },
              {
                "key": "Content-Type",
                "name": "Content-Type",
                "value": "application/json",
                "type": "text"
              }
            ],
            "body": {
              "mode": "formdata",
              "formdata": [
                {
                  "key": "file",
                  "type": "file",
                  "src": "dummy.pdf"
                }
              ]
            },
            "url": {
              "raw": "{{TEST_HOST}}/files",
              "host": [
                "{{TEST_HOST}}"
              ],
              "path": [
                "files"
              ]
            },
            "description": "Upload a file"
          },
          "response": [
            
          ]
        }
      ]
    }
  ]
}
`

 7. Screenshots (if applicable):
↳ Upload Trial
  POST https://staging.api.xclaim.xcover.com/files [422 Unprocessable Entity, 11.74KB, 727ms]
  ┌
  │ '[422]: 422 Unprocessable Entity'
  │ '{"file":["The file field is required."]}'
  └

**Comment by codenirvana** [comment] 2019-08-16 08:11
Duplicate of #2081

The `Content-Type` is different than the type of request body selected.
Removing the `Content-Type` request header will fix your issue.

Refer https://github.com/postmanlabs/newman/issues/2081#issuecomment-519149629 for more details.

**Closed by codenirvana** 2019-08-16 08:11 UTC
