### ISSUE TITLE
not able to run individual test folders when running collections from URL

### ISSUE THREAD

**Issue by srbangre** [postmanlabs/newman#338] opened 2016-02-25 18:08 UTC
few things here - 

1. 

 My collection is stored in stash. so i am using -u command to run the collection. but when i give -f 'folder name' i get error - The folder does not exist.
How to run test folders inside collection if run using -u command?

2. My environment variable files are also stored in stash. so to run the collection from url, i cannot specify -e 'environment variable'. 
to run it i have to go to particular folder in my local machin where the env variables are stored, then run the -u command.

how do i resolve this.

**Comment by czardoz** [comment] 2016-02-26 06:33
Environments contain secrets, which should not be exposed over a public endpoint. That's why Newman does not support using an environment from a URL.

**Comment by czardoz** [comment] 2016-02-26 11:40
Also, I am not able to reproduce the issue with URLs and folders. I ran this command:

```
newman -u https://www.getpostman.com/collections/3a9d6e11dc9dd943d948 -f Headers
```

and it only ran the folder with the name "Headers".

**Comment by kmacharg** [comment] 2016-03-04 18:52
@czardoz 

I was having the same issue as @srbangre about the "folder not found error".  I was able to resolve it by going to the parent collection and clicking "Update Link" under the sharing options.  Is it possible something isn't being updated / synced about a collection if you have previously generated a collection URL?

**Comment by abhijitkane** [comment] 2016-03-04 21:03
@kmacharg A collection link is not automatically updated. You'll need to click 'Update Link' everytime you want Postman's changes to be reflected.

**Comment by czardoz** [comment] 2016-03-08 07:24
@srbangre Closing this issue, feel free to reopen if you're still having issues! :)

**Closed by czardoz** 2016-03-08 07:24 UTC
