### ISSUE TITLE
Remove newline insertion when outputting console logs

### ISSUE THREAD

**Issue by betson-nuovo** [postmanlabs/newman#1413] opened 2018-02-07 06:26 UTC
When outputting to console using the various console output streams, executing the collection using newman and redirecting that output to a file, newman inserts newlines within a single console output statement after about 54 chars (give or take my quick counting).  When allowing results to print to terminal, a newline will be inserted depending on the terminal width.

In Pre-request or Test script:
`console.info("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum");`

Resulting output in redirected file:
  │ [90m'Lorem ipsum dolor sit amet, consectetur adipisci
  │ ng elit, sed do eiusmod tempor incididunt ut labore et
  │  dolore magna aliqua. Ut enim ad minim veniam, quis no
  │ strud exercitation ullamco laboris nisi ut aliquip ex 
  │ ea commodo consequat. Duis aute irure dolor in reprehe
  │ nderit in voluptate velit esse cillum dolore eu fugiat
  │  nulla pariatur. Excepteur sint occaecat cupidatat non
  │  proident, sunt in culpa qui officia deserunt mollit a
  │ nim id est laborum'[39m

Is there a way to disable this newline insertion, especially for the case of redirecting output to a file? We have an automated process that is being impacted by having the console output split into multiple lines when it is expecting that to be found on a single line.

 1. Newman Version (can be found via `newman -v`): 3.9.3
 2. OS details (type, version, and architecture): OSX 10.12.6
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Only tested with this version
 4. Expected behaviour: No newlines are artificially inserted by newman
 5. Command / script used to run Newman: `newman run LogNewline.postman_collection.json > cliresults.txt`
 6. Sample collection, and auxiliary files (minus the sensitive details):
[LogNewline.zip](https://github.com/postmanlabs/newman/files/1701972/LogNewline.zip)

**Comment by kunagpal** [comment] 2018-05-18 12:30
Closing as a duplicate of #1203

**Closed by kunagpal** 2018-05-18 12:30 UTC
Labels: reporters
