### ISSUE TITLE
Hi, total assertions in alltest cases of a test suite

### ISSUE THREAD

**Issue by pragyaparashar** [postmanlabs/newman#1847] opened 2019-01-03 05:11 UTC
Hi,

I want to show total no. of assertions in all test cases of a test suite in my newman report. Can anyone please help me doing that.

issue example:
I have a collection with 2 test suites and each test suite contains 10 test cases with multiple assertions. say:
 test suite 1 - test cases 10- total assertions in 10 test cases 50- 20 pass and 30 fail
test suite 2 - test cases 9- total assertions in 9 test cases 45- 20 pass and 25 fail

i want to show report suite wise in a table like below attached format:

Test | Pass | Fail
-- | -- | --
1 Test suite   name | 20 | 30
2 Test suite   name | 20 | 25

**Comment by codenirvana** [comment] 2019-01-03 08:17
@pragyaparashar When an assertion fails, it throws an exception and stops the further execution of that particular suite. So, getting the count for failed assertions is not possible.

Its expected behavior in most of the testing frameworks, I suggest you divide your test suites into multiple atomic `pm.test` blocks.

Also, share your use case where this kind of behavior is required so we better understand your problem.

**Comment by pragyaparashar** [comment] 2019-01-03 23:12
@codenirvana, I have script with multiple pm.test only but I want to count them and display in total.

Currently I am getting like this
![image](https://user-images.githubusercontent.com/46336748/50666475-9b1e2800-1000-11e9-9c7a-dc2e578719d6.png)
 but I want total of all fail and pass test cases.

I hope this will help you and if you need furthur information, please let me know.

**Comment by pragyaparashar** [comment] 2019-01-07 00:37
Hi, 

Do you have any update on this?

**Comment by pragyaparashar** [comment] 2019-01-07 01:18
or instead of assertions you can help me with number of test cases in both suites. Below is example for clarity of issue:

If I have two suites A and B
A suite contains 10 test cases out of which 4 are passed and 6 are failed and test suite B contains 12 test cases among which all are pass and 0 is failed and I want to show them as below table:


Test Suite | Pass Testcases | Fail Test cases
-- | -- | --
A | 4 | 6
B | 12 | 0

**Comment by pragyaparashar** [comment] 2019-01-07 01:51
Hi @codenirvana @kunagpal , could you please help me with this.

**Comment by codenirvana** [comment] 2019-01-07 06:55
@pragyaparashar Here, a test suite means a `request` or `pm.test`?

I assume a test suite is a `pm.test.` block and from test cases, you mean assertions (`pm.expect`).
As mentioned above, it's not possible to count the number of passed & failed assertions.

Can you share a sample collection to refer from?

**Comment by pragyaparashar** [comment] 2019-01-08 01:46
@codenirvana , is there any update?

**Comment by pragyaparashar** [comment] 2019-01-08 03:49
FOr More clarification if my collection structure is like below table:
Collection
--
Test Suite A |   |  
Tc_001 | Pass |  
TC_002 | Pass |  
TC_003 | Pass |  
TC_004 | Fail |  
Test Suite B |   |  
Tc_001 | PAss |  
TC_002 | PAss |  
TC_003 | Fail |  
TC_004 | Fail |  

I want table in report like below:
Output   I want to show
--
Table | Pass | Fail
Test Suite A | 3 | 1
Test SuiteB | 2 | 2

I am not able to show these pass fail count. Please help me in that.

I hope it will help

**Comment by codenirvana** [comment] 2019-01-09 00:52
@pragyaparashar Got it.
It is a very specific use case, you have to fork the required reporter and make these custom changes on top.

Which reporter are you referring here?

**Comment by pragyaparashar** [comment] 2019-01-09 01:51
html reporter i am using

**Comment by codenirvana** [comment] 2019-01-09 03:50
@pragyaparashar You need to first compute the required stats, which can be done by iterating the `this.summary` which holds both the collection as well as failure object. And pass that result to the handlebars compiler:
https://github.com/postmanlabs/newman-reporter-html/blob/v1.0.2/lib/index.js#L161

Finally, use the resultant in the handlebars template:
https://github.com/postmanlabs/newman-reporter-html/blob/develop/lib/template-default.hbs

**Comment by codenirvana** [comment] 2019-01-09 04:31
@pragyaparashar Reporters works independently, you don't need to make any changes in Newman.

**Comment by pragyaparashar** [comment] 2019-01-09 04:53
Hi @codenirvana , Implementing this i am still not getting count of requests. I am getting all the failures in all requests but I don't need that..I need just the count. Please help me if I am getting it wrong

**Comment by codenirvana** [comment] 2019-01-09 06:03
@pragyaparashar There's no update step, changes made in reporter are independent of Newman.

Closing this issue for now, since this is not related to Newman. We have an active user community forum that will help to solve further issues. Visit: https://community.getpostman.com/

**Closed by codenirvana** 2019-01-09 06:03 UTC
Labels: question

**Comment by pragyaparashar** [comment] 2019-01-09 06:58
If you are working on assissting then you should complete it...why you closed it before confirmimng that it is working or not

**Comment by numaanashraf** [comment] 2019-01-09 07:47
@pragyaparashar This is a public issue tracker for `newman` where we track feature requests and issues. We do not provide continued support and assistance regarding how to use `newman` or debug your specific use cases here. As @codenirvana mentioned, we recommend reaching out to the wider Postman community at https://community.getpostman.com/ for continued assistance or support.

Issue Guidelines: https://github.com/postmanlabs/newman#community-support

**Comment by pragyaparashar** [comment] 2019-01-09 23:09
Okay...thank you

**Comment by toolmania1** [comment] 2019-12-05 13:22
Can someone please paste a link to the post man community where this issue has been continued?  This was a very useful thread until it was killed right at the important point unfortunately.   Thanks in advance!
