### ISSUE TITLE
Saving Collections not possible

### ISSUE THREAD

**Issue by debjchak** [postmanlabs/newman#1852] opened 2019-01-08 13:33 UTC
Newman Version:4.0.2,Postman Version:6.2.5
OS details (type, version, and architecture): Windows 7,64 bit production Imagev1.16.00.AO.B19
Newman via the CLI
Did you encounter this recently, or has this bug always been there: Recently started using
Expected behaviour: Scripts modified in one workspace should not reflect in others

I modified my scripts and saved the collections. A day later I see my scripts depicting the last data and not the newly modified ones. Could you please let me know why this happens?

Thanks
Debjani

**Comment by kamalaknn** [comment] 2019-01-09 05:38
@debjchak If you are editing the same collection that exists in more than one workspace the changes would propagate to all the worksapces. If you do not want this, you can duplicate the collection in one of your worksapces.

I'm closing this because this is the expected behavior and not a bug or a feature request.

Thanks

**Closed by kamalaknn** 2019-01-09 05:38 UTC
