### ISSUE TITLE
Memory leaks over multiple iterations of Newman.run

### ISSUE THREAD

**Issue by mailtogj** [postmanlabs/newman#1497] opened 2018-04-11 11:27 UTC
1. Newman Version (can be found via `newman -v`): 3.8.3
 2. OS details (type, version, and architecture): Win 7 Enterprise SP1
 3. Are you using Newman as a library, or via the CLI? Using as a library
 3. Did you encounter this recently, or has this bug always been there:  encountered recently but after spinning cycles with existing code
 4. Expected behaviour: No memory leaks or spike in heapUsed
 5. Command / script used to run Newman: Newman.run
 6. Sample collection, and auxiliary files (minus the sensitive details):

[Newman run options.txt](https://github.com/postmanlabs/newman/files/1898440/Newman.run.options.txt)

[Newman run code snippet.txt](https://github.com/postmanlabs/newman/files/1898453/Newman.run.code.snippet.txt)

[memoryLeakTrace.txt](https://github.com/postmanlabs/newman/files/1898477/memoryLeak.txt)

This is just a simple collection with a call to a url that does not exists thereby generating an error.
I am iterating it in soak cycles, each cycle generates a memory spike of around 2.9-3 MB and does not release it. 
After first run heapUsed is 8.8 mb and after tenth run it reaches 20.45 mb.

Each run cycle is run with [pre-generated option set](https://github.com/postmanlabs/newman/files/1898440/Newman.run.options.txt)

I have implemented a small heapUse tracer along with the Newman run code [Newman.run.code.snippet.txt](https://github.com/postmanlabs/newman/files/1898453/Newman.run.code.snippet.txt)

For memory trace for ten iterations Refer [memoryLeakTrace.txt](https://github.com/postmanlabs/newman/files/1898477/memoryLeak.txt)

I also implemented a recursive event emitter gc util but it did not help much.

Already an existing [issue](https://github.com/postmanlabs/newman/issues/290) with similar behavior was logged but closed 

Is this an issue with Newman module run function else how may I fix this.

**Comment by r3ticuli** [comment] 2018-05-14 17:37
Hi @kunagpal ,

I'm trying to use newman in an AWS lambda, and this "statistical aggregation" default setting may be the reason why I keep butting heads with the allocated lambda memory limit. Is there a way to disable this setting?

**Comment by kunagpal** [comment] 2018-05-15 06:40
@r3ticuli In that case, a way to fix this would be to add a 'light mode' flag that disables aggregation and only holds data for the current request.

**Comment by codenirvana** [comment] 2020-05-25 21:05
Closing as duplicate of #941

**Closed by codenirvana** 2020-05-25 21:05 UTC
Labels: feature request, performance, runtime
