### ISSUE TITLE
Postman - Newman Error: tunneling socket could not be established, statusCode=403

### ISSUE THREAD

**Issue by bhanupinninti** [postmanlabs/newman#1581] opened 2018-06-13 03:54 UTC
Team,

I am running my postman collection from postman runner (chrome extension) by passing my input csv file and it is executing successfully.

When I run the same collection with same input file using newman or native postman app (V6.1.3) it is failing with the "Error: tunneling socket could not be established, statusCode=403". Please find the screenshots below..

Console log:
![image](https://user-images.githubusercontent.com/38074414/41329436-0fa348cc-6f11-11e8-8b00-97795a52dd86.png)

![image](https://user-images.githubusercontent.com/38074414/41329461-3c1f2466-6f11-11e8-9897-fa278ad6c1f9.png)

**Comment by bhanupinninti** [comment] 2018-06-13 04:06
adding @kunagpal

**Comment by kunagpal** [comment] 2018-06-15 08:47
@bhanupinninti Are you running behind a proxy that requires authentication? This isn't currently supported by postman-runtime, the underlying library that powers both: the Postman App, as well as Newman.

If not, could you confirm that the `HTTP_PROXY` and `HTTPS_PROXY` environment variables are set appropriately? The `HTTP_PROXY` environment variable should point to a http proxy endpoint, while the `HTTPS_PROXY` variable should go to a https proxy endpoint.

(On a different note, these variables should be cleared if a proxy isn't being used)

More details can be found here: https://github.com/postmanlabs/newman#proxy

**Comment by bhanupinninti** [comment] 2018-06-19 00:51
I am running behind the proxy :(..so do u recommend me to wait until postman give support for this

**Comment by kunagpal** [comment] 2018-06-28 19:21
@bhanupinninti Closing as a duplicate of #1599, we'll track progress over there 😄

Thanks again for reporting this!

**Closed by kunagpal** 2018-06-28 19:21 UTC
Labels: feature request, runtime
