### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by cchretien** [postmanlabs/newman#2295] opened 2020-04-03 14:14 UTC
Performance of newman has degraded.

 1. Newman Version (can be found via `newman -v`): 4.5.7
 2. OS details (type, version, and architecture): Window 10.0.18362 N/A Build 18362
 3. Are you using Newman as a library, or via the CLI? Using it as a library. Script attached
 3. Did you encounter this recently, or has this bug always been there: Recently, moving to 4.5.7 from 4.4.0
 4. Expected behaviour: Expecting it to stand up like it does in 4.4.0
 5. Command / script used to run Newman:
     * `json-server.js` - http server
     * `dataset.json` - json data served by http server
     * `memleak-bug.js` - newman script
     * [newman-test.zip](https://github.com/postmanlabs/newman/files/4167828/newman-test.zip)
 6. Sample collection, and auxiliary files (minus the sensitive details):
     * `MemLeakJson.postman_collection.json`
 7. Screenshots (if applicable):
**Failure**
```
Iteration 600/1000

└ DataSet
  GET http://localhost:8090/dataset.json [200 OK, 1.52MB, 10ms]

<--- Last few GCs --->

[14828:0000029DC4B37E10]   316144 ms: Mark-sweep 1379.8 (1431.3) -> 1379.8 (1431.3) MB, 49.7 / 0.0 ms  allocation failure GC in old space requested
[14828:0000029DC4B37E10]   316195 ms: Mark-sweep 1379.8 (1431.3) -> 1379.8 (1400.3) MB, 51.5 / 0.0 ms  last resort GC in old space requested
[14828:0000029DC4B37E10]   316257 ms: Mark-sweep 1379.8 (1400.3) -> 1379.8 (1400.3) MB, 61.3 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000007606AA5879 <JSObject>
    1: utf8Slice(aka utf8Slice) [evalmachine.<anonymous>:~13329] [pc=000000F493FBDF9E](this=000000FDE9F822D1 <undefined>,e=000001D1EAFE7A99 <Uint8Array map = 0000000B77B9DE79>,t=0,r=1594707)
    2: slowToString [evalmachine.<anonymous>:13329] [bytecode=0000023BF86C0FC9 offset=207](this=000001D1EAFE7A99 <Uint8Array map = 0000000B77B9DE79>,e=0000007606AB5001 <String[4]: utf8>,t=0,r=1594707)
    ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewUninitializedFixedArray
 5: v8::internal::WasmDebugInfo::SetupForTesting
 6: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 7: 000000F493E043C1

C:\workspace>
C:\workspace>
C:\workspace>
C:\workspace>node --version
v8.11.3

C:\workspace>node_modules\.bin\newman -v
4.5.7
```

**Success with 4.4.0**
```
Iteration 1000/1000

└ DataSet
  GET http://localhost:8090/dataset.json [200 OK, 1.52MB, 10ms]
  ┌
  │ 'Number of records: 1064'
  │ 'JSON keys: _id,index,guid,isActive,balance,picture,age,eyeColor,name,company,email,phone,address,about,registered,latitude,lon       
  │ gitude,tags,range,friends,greeting,favoriteFruit'
  │ 'Saved JSON data'
  └
  √  Obtained JSON

┌─────────────────────────┬───────────────────┬──────────────────┐
│                         │          executed │           failed │
├─────────────────────────┼───────────────────┼──────────────────┤
│              iterations │              1000 │                0 │
├─────────────────────────┼───────────────────┼──────────────────┤
│                requests │              1000 │                0 │
├─────────────────────────┼───────────────────┼──────────────────┤
│            test-scripts │              1000 │                0 │
├─────────────────────────┼───────────────────┼──────────────────┤
│      prerequest-scripts │                 0 │                0 │
├─────────────────────────┼───────────────────┼──────────────────┤
│              assertions │              1000 │                0 │
├─────────────────────────┴───────────────────┴──────────────────┤
│ total run duration: 56m 13.9s                                  │
├────────────────────────────────────────────────────────────────┤
│ total data received: 1.49GB (approx)                           │
├────────────────────────────────────────────────────────────────┤
│ average response time: 17ms [min: 8ms, max: 550ms, s.d.: 59ms] │
└────────────────────────────────────────────────────────────────┘
collection run complete!

C:\workspace\postman\newman\target>
C:\workspace\postman\newman\target>node --version
v8.11.3

C:\workspace\postman\newman\target>node_modules\.bin\newman --version
4.4.0
```
[newman-test.zip](https://github.com/postmanlabs/newman/files/4167828/newman-test.zip)

To run:
* launch the http server `node json-server.js`
* In another shell, launch script `node memleak-bug.js`

_Originally posted by @cchretien in https://github.com/postmanlabs/newman/issues/2166#issuecomment-583122681_

**Comment by codenirvana** [comment] 2020-05-25 22:51
Duplicate of #941

**Closed by codenirvana** 2020-05-25 22:51 UTC

**Comment by cchretien** [comment] 2020-05-26 12:51
I hope the information provided at least narrows down something introduced in the minor release  4.4.0 < x <= 4.5.7 
We've been using newman up to 4.4.0 quite heavily in our CI and it's been pretty solid despite the performance issue 941

**Comment by codenirvana** [comment] 2020-05-28 07:59
@cchretien Thanks for providing the sample test suit to reproduce this issue.
You are right, It started failing from v4.5.6 onwards. So, I spent some time looking into every change made in Newman and it's dependencies and I can't find anything which might cause this.

However, I see the execution has 1000 iterations with every request having 1.5 MB of response payload, and since Newman internally accumulates all the iteration data to generate the report... that causes the Node process to crash after taking nearly 2GB of memory. Which is similar to #941.

There's a workaround though, using `--max-old-space-size` Node.js option to increase the max memory size of V8's old memory section.
```
NODE_OPTIONS="--max-old-space-size=4096" node memleak-bug.js
```
