### ISSUE TITLE
Collection variable as a JSON object is not working in newman

### ISSUE THREAD

**Issue by swastikmu** [postmanlabs/newman#2359] opened 2020-05-21 09:35 UTC
I am working on a test script where i am using collection variables to for storing tokens and use it in subsequent calls. Now instead of single variable I used JSON object to make sure one type of data stores in one object. It is working fine in collection Runner. However , in newman it is showing undefined. is new newman unable to handle json var
call 1: pre requisite 👍 

![image](https://user-images.githubusercontent.com/59292353/82545272-163f9a00-9b74-11ea-81a8-215df546499c.png)

set the value in test call 1
![image](https://user-images.githubusercontent.com/59292353/82545618-8ea65b00-9b74-11ea-9ffe-325f36f83841.png)

getting the value in value in call2

![image](https://user-images.githubusercontent.com/59292353/82545338-31aaa500-9b74-11ea-89eb-157ed2cd28ed.png)

**Comment by codenirvana** [comment] 2020-05-21 09:52
Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by swastikmu** [comment] 2020-05-21 10:14
HI @codenirvana  , You cannot execute the coll as it is meant to run in closed environment . I am still attaching the colll to view the structure.


[github_collection.json.txt](https://github.com/postmanlabs/newman/files/4661859/github_collection.json.txt)

**Comment by codenirvana** [comment] 2020-05-21 10:18
@swastikmu please use a [echo endpoint](http://postman-echo.com/) to mimic the behavior in a way we can execute and reproduce this issue locally.

**Comment by swastikmu** [comment] 2020-05-21 10:29
Okay. I will check and as i told you cannot use urls as such. i will try to use open apis and mimic the behavior. by the mean time i will use single variable instead of json in coll variables.

**Comment by swastikmu** [comment] 2020-05-26 04:03
HI ,sorry for my late reply. i was trying from my end. i have taken a small example to simulate the same as i cannot share the actual api as it is private business data and i do not have permission.
when i run the coll using postman runner it is working fine. However, the newman unable to parse the json object which i defined in the pre-requisite of the first call.

[northwind.json.txt](https://github.com/postmanlabs/newman/files/4679831/northwind.json.txt)

please find the coll file in .txt format.

**Comment by codenirvana** [comment] 2020-05-28 08:13
@swastikmu Thanks for providing the sample collection!

This is happening because the exported collection has variable type `string` which is casting the updates on these variables to string as well.
```json
"variable ": [{
  "id": "cdcbeab8-2443-4719-acc7-2f44def7156d",
  "key": "businessData",
  "value": "",
  "type": "string"
}, {
  "id": "5fa8ed18-06be-4a3a-839b-e29b900997f7",
  "key": "customer",
  "value": "",
  "type": "string"
}]
```

As a workaround, you can either remove the `type` property complete from the exported collection JSON or change `type` to `any`.

Marking this as a bug and will let you know if there's any update on this.

**Comment by codenirvana** [comment] 2020-07-08 08:32
This is fixed in the latest version of the Postman app, exported collection variables will no longer have the explicit `type` value which caused this issue.

**Closed by codenirvana** 2020-07-08 08:32 UTC
Labels: bug
