### ISSUE TITLE
Request failing with 400 response code in Newman versions greater than 4.5.1

### ISSUE THREAD

**Issue by manu4rhyme** [postmanlabs/newman#2116] opened 2019-09-09 11:10 UTC
Hi,

We recently upgraded our packages (including Newman), and observed one request failing in the new version only. 

Earlier we were on 4.5.1, and everything was working correctly and as expected from corresponding postman runs.

However, since our recent upgrades: 
1) Everything is working correctly on postman
2) One request is throwing a 400 when the same collection is run on Newman

Comparisons in below images:

Newman v4.5.1: ![image](https://user-images.githubusercontent.com/6754924/64526092-03f03980-d320-11e9-8526-c8ba316beaac.png)

Newman v4.5.4: ![image](https://user-images.githubusercontent.com/6754924/64526146-34d06e80-d320-11e9-93bc-71a58e7a784a.png)

As you can see the OTPSubmission request is now returning a 400. We don't understand this behaviour, since we haven't changed these APIs or the tests. Moreover, the same request is working correctly on Postman: 
![image](https://user-images.githubusercontent.com/6754924/64526550-42d2bf00-d321-11e9-8054-bcb41b4601bd.png)

I did not find any breaking changes documented for these new versions. Please look into the issue and guide us further.

**Comment by codenirvana** [comment] 2020-05-25 22:37
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 22:37 UTC
