### ISSUE TITLE
Newman/postman parsing a string with \n\t ' and " characters does not work

### ISSUE THREAD

**Issue by wvivek** [postmanlabs/newman#2095] opened 2019-08-16 04:23 UTC
I have a JSON response that contains \n\t \' and " characters. The raw response looks good.

Example:
{ "test": "/\*\n* Copyright (c) */ // End of 'Import Package'(\\"name\\")"}

I am trying to parse this response get the value of test and use it in another request body.
To do so I am using JSON.parser and setting this to environment variable.

var testData = JSON.parser(responseBody);\
postman.setEnvironmentVariable("TEST", testData.test);

When the use {{TEST}} in the next request i get a failure (BAD REQUEST).
When looked into this further I see that the {{TEST}} has the following content.

In Postman when inspecting the environment variable

/** Copyright (c) */ // End of 'Import Package'("name")

In newman when logging the environment variable using console.log(environment.TEST);

'/** Copyright (c) */ // End of \\'Import Package\\'("name")'

How can i ensure to pass the encoded string as i received in the response to the next request?

Postman Version: Postman v7.5.0  on Mac

Error Reported from WebServer is as follows:

{"timestamp":"2019-08-16T04:46:19.952+0000","status":400,"error":"Bad Request","message":"JSON parse error: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value\n at [Source: (PushbackInputStream); line: 7, column: 32]

**Comment by codenirvana** [comment] 2019-08-16 08:07
@wvivek Try setting the variable `TEST` as JSON string i.e, don't parse (JSON.parser) the response.

**Comment by codenirvana** [comment] 2020-05-25 22:33
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 22:33 UTC
Labels: question
