### ISSUE TITLE
Unable to Run Newman on Ubuntu 18.04

### ISSUE THREAD

**Issue by tdonovic** [postmanlabs/newman#1756] opened 2018-10-16 23:51 UTC
Version and environment information:

 1. Newman Version: 4.1.0
 2. OS details: Ubuntu 18.04 in a container, tried with Node 8.latest and 10.latest
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Only started using recently.
 4. Expected behaviour: Runs my job successfully.
 5. Command / script used to run Newman: `newman run "backup-service.postman_collection.json" --reporters="junit,cli" --reporter-junit-export="results/newman-report.xml"`
 6. Sample collection, and auxiliary files (minus the sensitive details):[backup-service.postman_collection.json.zip](https://github.com/postmanlabs/newman/files/2485334/backup-service.postman_collection.json.zip)
 7. Screenshots (if applicable):
<img width="963" alt="screen shot 2018-10-17 at 10 48 59 am" src="https://user-images.githubusercontent.com/8356825/47053780-4980b100-d1fa-11e8-863e-e1905862cb2d.png">

Steps to reproduce the problem:

1. Run Command
2. See it fail.

**Comment by bassie1995** [comment] 2018-11-30 15:11
Something seems wrong with your file, I couldn't import it in Postman. The error seems to indicate the same thing: an invalid character in the collection or something?

**Comment by codenirvana** [comment] 2020-05-25 21:40
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Closed by codenirvana** 2020-05-25 21:40 UTC
