### ISSUE TITLE
-Memory leak error while running Newman command in Jenkins

### ISSUE THREAD

**Issue by svarshney2311** [postmanlabs/newman#2520] opened 2020-09-25 18:37 UTC
1m
I have a 1500+ request to execute through Jenkins, while executing this I am getting below error
after running 1400+ tests:
There is no html report generated in the end.

<— Last few GCs —> 13:52:18 13:52:18 [249:0x3922f20] 2221349 ms: Mark-sweep 1281.7 (1447.1) -> 1265.1 (1446.6) MB, 1133.7 / 0.0 ms (average mu = 0.368, current mu = 0.441) allocation failure scavenge might not succeed 13:52:18 [249:0x3922f20] 2222969 ms: Mark-sweep 1282.7 (1447.6) -> 1265.8 (1447.6) MB, 1155.4 / 0.0 ms (average mu = 0.330, current mu = 0.287) allocation failure scavenge might not succeed 13:52:18 13:52:18 13:52:18 <— JS stacktrace —> 13:52:18 13:52:18 ==== JS stack trace ========================================= 13:52:18 13:52:18 0: ExitFrame [pc: 0x205a2f0dbe1d] 13:52:18 Security context: 0x35839701e6e9 13:52:18 1: zi [0x9c1bd5b7c79] [evalmachine.:~13813] [pc=0x205a2f92456a](this=0x194628e85889 ,n=0x37fa01b562a1 ) 13:52:18 2: Ue [0x9c1bd5b79d1] [evalmachine.:~13813] [pc=0x205a2fc65e98](this=0x194628e85889 ,t=0x37fa01b562a1 ,r=5,e=0x11c3644f0139 <JSFunctio… 13:52:18 13:52:18 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory 13:52:18 1: 0x8fa060 node::Abort() [node] 13:52:18 2: 0x8fa0ac [node] 13:52:18 3: 0xaff7ee v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node] 13:52:18 4: 0xaffa24 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node] 13:52:18 5: 0xef3f32 [node] 13:52:18 6: 0xef4038 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node] 13:52:18 7: 0xf00112 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node] 13:52:18 8: 0xf00a44 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node] 13:52:18 9: 0xf036b1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node] 13:52:18 10: 0xeccb34 v8::internal::factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node] 13:52:18 11: 0x116ccbe v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node] 13:52:18 12: 0x205a2f0dbe1d 13:52:26 node_modules/.bin/newman: line 14: 249 Aborted (core dumped) node “basedir/../newman/bin/newman.js" "@”

**Comment by DannyDainton** [comment] 2020-09-25 20:29
This is a duplicate of #941

You will be able to follow the conversation on that thread.

**Closed** 2020-09-25 20:29 UTC
