### ISSUE TITLE
Newman process dies after processing about 10K requests

### ISSUE THREAD

**Issue by jainishan** [postmanlabs/newman#2108] opened 2019-09-02 08:48 UTC
1. Newman Version: 4.5.4
 2. OS details: Alpine
 3. Using newman as CLI
 3. Encountered it recently (when i started using it)
 4. Expected behaviour: Should be able to process as many request as applicable in the case.
 5. Command / script used to run Newman: newman run -e <env_file> --verbose <collection>

I created an alpine based docker image and installed latest version of node and newman there. This docker image is being used as a jenkins agent where i run my collections.
Everything works fine, except when i have a larger data set. When the number of requests reach somewhere around 10K, the newman process dies. I have no idea why.
I confirmed it in my Jenkins settings and also after some test runs, that it is not the Jenkins who is killing the process. Newman seems to give up. It is not time bound as i tried adding delays, it sometimes dies within 30 mins and sometimes in 10 hours, but always after processing around 10K requests.

To Reproduce

Install latest version of newman on alpine
Run any collection with some input data. Make sure eventually newman gets to call the API endpoint(s) well over 10K times.
Newman fails after around 10K requests.
Expected behavior
Newman process must not die until it finishes all the given iterations.

**Comment by rwuttke-dxc** [comment] 2019-12-04 23:54
I have seen this behaviour as well.

Using the Memory tab in Chrome Developer Tools, I can see the amount of memory being used is seriously increasing and the main culprit seems to be strings.


Mb of Application | 4 | 77.2 | 90.9 | 98.1 | 115 | 168
-- | -- | -- | -- | -- | -- | --
Iteration | 1 | 2 | 3 | 4 | 5 | 6
(string) | 1,059,224 | 32,880,056 | 37,655,296 | 40,282,168 | 46,405,456 | 65,776,944
~Mb used by (string) | 1 | 31 | 36 | 38 | 44 | 63
% of Application | 25% | 41% | 40% | 39% | 38% | 37%

From the above table I can see that the amount of memory allocated for strings is rapidly increasing.

Having looked at the strings, I can see multiple versions of the code for Requests and Collection level scripts.

What is interesting is that the garbage collector in all that time (from iteration 1 to 6) only cleaned up 12 strings.

This problem was consistent over hours of testing.

**Comment by codenirvana** [comment] 2020-05-25 22:36
Closing as duplicate of #941

**Closed by codenirvana** 2020-05-25 22:36 UTC
